### ISSUE TITLE
Explicitouter crash on empty specialized class

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#1]
Fallout from the scalac changes:

```
package benchmarks

import miniboxing.plugin.minispec

class MBList[@minispec T]() {}
```

Spits out:

```
error: no-symbol does not have an owner

     while compiling: ../miniboxing-plugin/test/benchmarks/MBList.scala
        during phase: global=explicitouter, atPhase=erasure
     library version: version 2.10.0-20121014-154054-f3550d25e0
    compiler version: version 2.10.0-20121014-154054-f3550d25e0
  reconstructed args: -Xprint:minibox -Xprint:selectiveanf -Xprint:specialize -d mboxing -classpath /home/sun/workspace/dev/miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar:/home/sun/workspace/dev/miniboxing-plugin/components/runtime/target/scala-2.10/miniboxing-runime_2.10-0.1-SNAPSHOT.jar -uniqid -Xplugin:/home/sun/workspace/dev/miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar

  last tree to typer: term benchmarks
              symbol: package benchmarks#6919 (flags: final <module> <package> <java> <triedcooking>)
   symbol definition: final package benchmarks#6919
                 tpe: <notype>
       symbol owners: package benchmarks#6919 -> package <root>#2
      context owners: value T_TypeTag#12799 -> constructor MBList_L#12794 -> class MBList_L#12791 -> package benchmarks#6920

== Enclosing template or block ==

DefDef( // def <init>#12794(val T_TypeTag#12795: Byte#1217): benchmarks#6920.MBList_L#12791[Tsp#12792] in class MBList_L#12791
  <method> <synchronized>
  "<init>"
  []
  // 1 parameter list
  ValDef( // val T_TypeTag#12799: Byte#1217
    <synthetic>
    "T_TypeTag"
    <tpt> // tree.tpe=Byte#1217
    <empty>
  )
  <tpt> // tree.tpe=benchmarks#6920.MBList_L#12791[Tsp#12792]
  Block( // tree.tpe=Unit#614
    Apply( // def <init>#4677(): Object#1728 in class Object#1728, tree.tpe=Object#1728
      MBList#6922.super."<init>" // def <init>#4677(): Object#1728 in class Object#1728, tree.tpe=()Object#1728
      Nil
    )
    ()
  )
)

== Expanded type of tree ==

<notype>

unhandled exception while transforming MBList.scala
error: 
     while compiling: ../miniboxing-plugin/test/benchmarks/MBList.scala
        during phase: explicitouter
     library version: version 2.10.0-20121014-154054-f3550d25e0
    compiler version: version 2.10.0-20121014-154054-f3550d25e0
  reconstructed args: -Xprint:minibox -Xprint:selectiveanf -Xprint:specialize -d mboxing -classpath /home/sun/workspace/dev/miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar:/home/sun/workspace/dev/miniboxing-plugin/components/runtime/target/scala-2.10/miniboxing-runime_2.10-0.1-SNAPSHOT.jar -uniqid -Xplugin:/home/sun/workspace/dev/miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar

  last tree to typer: term benchmarks
              symbol: package benchmarks#6919 (flags: final <module> <package> <java> <triedcooking>)
   symbol definition: final package benchmarks#6919
                 tpe: <notype>
       symbol owners: package benchmarks#6919 -> package <root>#2
      context owners: value T_TypeTag#12799 -> constructor MBList_L#12794 -> class MBList_L#12791 -> package benchmarks#6920

== Enclosing template or block ==

DefDef( // def <init>#12794(val T_TypeTag#12795: Byte#1217): benchmarks#6920.MBList_L#12791[Tsp#12792] in class MBList_L#12791
  <method> <synchronized>
  "<init>"
  []
  // 1 parameter list
  ValDef( // val T_TypeTag#12799: Byte#1217
    <synthetic>
    "T_TypeTag"
    <tpt> // tree.tpe=Byte#1217
    <empty>
  )
  <tpt> // tree.tpe=benchmarks#6920.MBList_L#12791[Tsp#12792]
  Block( // tree.tpe=Unit#614
    Apply( // def <init>#4677(): Object#1728 in class Object#1728, tree.tpe=Object#1728
      MBList#6922.super."<init>" // def <init>#4677(): Object#1728 in class Object#1728, tree.tpe=()Object#1728
      Nil
    )
    ()
  )
)

== Expanded type of tree ==

<notype>

uncaught exception during compilation: scala.reflect.internal.FatalError
error: scala.reflect.internal.FatalError: 
     while compiling: ../miniboxing-plugin/test/benchmarks/MBList.scala
        during phase: global=explicitouter, atPhase=erasure
     library version: version 2.10.0-20121014-154054-f3550d25e0
    compiler version: version 2.10.0-20121014-154054-f3550d25e0
  reconstructed args: -Xprint:minibox -Xprint:selectiveanf -Xprint:specialize -d mboxing -classpath /home/sun/workspace/dev/miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar:/home/sun/workspace/dev/miniboxing-plugin/components/runtime/target/scala-2.10/miniboxing-runime_2.10-0.1-SNAPSHOT.jar -uniqid -Xplugin:/home/sun/workspace/dev/miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar

  last tree to typer: term benchmarks
              symbol: package benchmarks#6919 (flags: final <module> <package> <java> <triedcooking>)
   symbol definition: final package benchmarks#6919
                 tpe: <notype>
       symbol owners: package benchmarks#6919 -> package <root>#2
      context owners: value T_TypeTag#12799 -> constructor MBList_L#12794 -> class MBList_L#12791 -> package benchmarks#6920

== Enclosing template or block ==

DefDef( // def <init>#12794(val T_TypeTag#12795: Byte#1217): benchmarks#6920.MBList_L#12791[Tsp#12792] in class MBList_L#12791
  <method> <synchronized>
  "<init>"
  []
  // 1 parameter list
  ValDef( // val T_TypeTag#12799: Byte#1217
    <synthetic>
    "T_TypeTag"
    <tpt> // tree.tpe=Byte#1217
    <empty>
  )
  <tpt> // tree.tpe=benchmarks#6920.MBList_L#12791[Tsp#12792]
  Block( // tree.tpe=Unit#614
    Apply( // def <init>#4677(): Object#1728 in class Object#1728, tree.tpe=Object#1728
      MBList#6922.super."<init>" // def <init>#4677(): Object#1728 in class Object#1728, tree.tpe=()Object#1728
      Nil
    )
    ()
  )
)

== Expanded type of tree ==

<notype>

no-symbol does not have an owner
    at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:48)
    at scala.tools.nsc.Global.abort(Global.scala:253)
    at scala.reflect.internal.Symbols$NoSymbol.owner(Symbols.scala:3193)
    at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.outerSelect(ExplicitOuter.scala:231)
    at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.outerValue(ExplicitOuter.scala:215)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:499)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:335)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1226)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2816)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:274)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:562)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:335)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1175)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2816)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:274)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:512)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:335)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1177)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2816)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:274)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:562)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:335)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2846)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2844)
    at scala.collection.immutable.List.loop$1(List.scala:164)
    at scala.collection.immutable.List.mapConserve(List.scala:180)
    at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2844)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1196)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2816)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:274)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:562)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:335)
    at scala.reflect.internal.Trees$$anonfun$itransform$2.apply(Trees.scala:1193)
    at scala.reflect.internal.Trees$$anonfun$itransform$2.apply(Trees.scala:1191)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2855)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1190)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2816)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:274)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:492)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:335)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2846)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2844)
    at scala.collection.immutable.List.loop$1(List.scala:164)
    at scala.collection.immutable.List.mapConserve(List.scala:180)
    at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2844)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1234)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2816)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.scala$tools$nsc$transform$TypingTransformers$TypingTransformer$$super$transform(TypingTransformers.scala:44)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$1.apply(TypingTransformers.scala:44)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$1.apply(TypingTransformers.scala:44)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2855)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
    at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:274)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:473)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:335)
    at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2823)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1238)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1237)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2855)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1236)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2816)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:274)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:562)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:335)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2846)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2844)
    at scala.collection.immutable.List.loop$1(List.scala:164)
    at scala.collection.immutable.List.mapConserve(List.scala:180)
    at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2844)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1256)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1256)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2855)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1255)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2816)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.scala$tools$nsc$transform$TypingTransformers$TypingTransformer$$super$transform(TypingTransformers.scala:44)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$2.apply(TypingTransformers.scala:46)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$2.apply(TypingTransformers.scala:46)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2855)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:46)
    at scala.tools.nsc.transform.ExplicitOuter$OuterPathTransformer.transform(ExplicitOuter.scala:274)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:562)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transform(ExplicitOuter.scala:335)
    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:227)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.scala$tools$nsc$transform$ExplicitOuter$ExplicitOuterTransformer$$super$transformUnit(ExplicitOuter.scala:570)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer$$anonfun$transformUnit$1.apply$mcV$sp(ExplicitOuter.scala:570)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer$$anonfun$transformUnit$1.apply(ExplicitOuter.scala:570)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer$$anonfun$transformUnit$1.apply(ExplicitOuter.scala:570)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:201)
    at scala.reflect.internal.SymbolTable.afterPhase(SymbolTable.scala:210)
    at scala.tools.nsc.Global.afterExplicitOuter(Global.scala:1098)
    at scala.tools.nsc.transform.ExplicitOuter$ExplicitOuterTransformer.transformUnit(ExplicitOuter.scala:570)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:461)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:428)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:428)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1156)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:428)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1574)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1548)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1544)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1654)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:33)
    at scala.tools.nsc.Main$.doCompile(Main.scala:79)
    at scala.tools.nsc.Driver.process(Driver.scala:54)
    at scala.tools.nsc.Driver.main(Driver.scala:67)
    at scala.tools.nsc.Main.main(Main.scala)

error: fatal error: 
     while compiling: ../miniboxing-plugin/test/benchmarks/MBList.scala
        during phase: global=explicitouter, atPhase=erasure
     library version: version 2.10.0-20121014-154054-f3550d25e0
    compiler version: version 2.10.0-20121014-154054-f3550d25e0
  reconstructed args: -Xprint:minibox -Xprint:selectiveanf -Xprint:specialize -d mboxing -classpath /home/sun/workspace/dev/miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar:/home/sun/workspace/dev/miniboxing-plugin/components/runtime/target/scala-2.10/miniboxing-runime_2.10-0.1-SNAPSHOT.jar -uniqid -Xplugin:/home/sun/workspace/dev/miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar

  last tree to typer: term benchmarks
              symbol: package benchmarks#6919 (flags: final <module> <package> <java> <triedcooking>)
   symbol definition: final package benchmarks#6919
                 tpe: <notype>
       symbol owners: package benchmarks#6919 -> package <root>#2
      context owners: value T_TypeTag#12799 -> constructor MBList_L#12794 -> class MBList_L#12791 -> package benchmarks#6920

== Enclosing template or block ==

DefDef( // def <init>#12794(val T_TypeTag#12795: Byte#1217): benchmarks#6920.MBList_L#12791[Tsp#12792] in class MBList_L#12791
  <method> <synchronized>
  "<init>"
  []
  // 1 parameter list
  ValDef( // val T_TypeTag#12799: Byte#1217
    <synthetic>
    "T_TypeTag"
    <tpt> // tree.tpe=Byte#1217
    <empty>
  )
  <tpt> // tree.tpe=benchmarks#6920.MBList_L#12791[Tsp#12792]
  Block( // tree.tpe=Unit#614
    Apply( // def <init>#4677(): Object#1728 in class Object#1728, tree.tpe=Object#1728
      MBList#6922.super."<init>" // def <init>#4677(): Object#1728 in class Object#1728, tree.tpe=()Object#1728
      Nil
    )
    ()
  )
)

== Expanded type of tree ==

<notype>

no-symbol does not have an owner

```

**Comment by VladUreche** [comment]
Culprit was:

```
  class MBList_L[Tsp >: Nothing <: Any] extends Object with benchmarks.MBList_interface[Tsp] {
    <synthetic> <paramaccessor> <synchronized> private[this] val T_TypeTag: Byte = _;
    <synchronized> def <init>(T_TypeTag: Byte): benchmarks.MBList_L[Tsp] = {
      MBList.super.<init>(); // Uh-oh - MBList instead of MBList_L
      ()
    }
  };
```
