### ISSUE TITLE
NPE when casting null

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#103]
```
$ cat gh-bug-102.scala 

package miniboxing.tests.compile.bug102

class C[@specialized T] {
  def foo(t: T): T = null.asInstanceOf[T]
}

object Test extends App {
  println((new C[Int]).foo(3))
}

$ ../mb-scalac gh-bug-102.scala -P:minibox:no-logo

$ ../mb-scala miniboxing.tests.compile.bug102.Test
0

$ ../mb-scalac gh-bug-102.scala -P:minibox:no-logo -P:minibox:hijack

$ ../mb-scala miniboxing.tests.compile.bug102.Test
java.lang.NullPointerException
    at miniboxing.runtime.MiniboxConversions.box2minibox_tt(MiniboxConversions.java:106)
    at miniboxing.tests.compile.bug102.C_J.foo_J(gh-bug-102.scala:4)
    at miniboxing.tests.compile.bug102.Test$delayedInit$body.apply(gh-bug-102.scala:7)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.App$$anonfun$main$1.apply(App.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:32)
    at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
    at scala.App$class.main(App.scala:71)
    at miniboxing.tests.compile.bug102.Test$.main(gh-bug-102.scala:7)
    at miniboxing.tests.compile.bug102.Test.main(gh-bug-102.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:71)
    at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
    at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:139)
    at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:71)
    at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:139)
    at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:28)
    at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
    at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:35)
    at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
    at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:74)
    at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
    at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:105)
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

The underlying translation:

```
$ ../mb-scalac gh-bug-102.scala -P:minibox:no-logo -P:minibox:hijack -Xprint:minibox-spec
[[syntax trees at end of              minibox-spec]] // gh-bug-102.scala
package miniboxing.tests.compile.bug102 {
  abstract trait C[@miniboxed T >: Nothing <: Any] extends Object {
    def foo(t: T): T;
    def foo_J(T_TypeTag: Byte, t: Long): Long
  };
  class C_J[Tsp >: Nothing <: Any] extends Object with miniboxing.tests.compile.bug102.C[Tsp] {
    def <init>(miniboxing|tests|compile|bug102|C_J|T_TypeTag: Byte): miniboxing.tests.compile.bug102.C_J[Tsp] = {
      C_J.super.<init>();
      ()
    };
    def foo(t: Tsp): Tsp = MiniboxConversions.this.minibox2box[Tsp](C_J.this.foo_J(C_J.this.miniboxing|tests|compile|bug102|C_J|T_TypeTag, MiniboxConversions.this.box2minibox_tt[Tsp](t, C_J.this.miniboxing|tests|compile|bug102|C_J|T_TypeTag)), C_J.this.miniboxing|tests|compile|bug102|C_J|T_TypeTag);
    def foo_J(T_TypeTag: Byte, t: Long): Long = MiniboxConversions.this.box2minibox_tt[Tsp](null.asInstanceOf[Tsp](), T_TypeTag);
    <paramaccessor> private[this] val miniboxing|tests|compile|bug102|C_J|T_TypeTag: Byte = _
  };
  class C_L[Tsp >: Nothing <: Any] extends Object with miniboxing.tests.compile.bug102.C[Tsp] {
    def <init>(): miniboxing.tests.compile.bug102.C_L[Tsp] = {
      C_L.super.<init>();
      ()
    };
    def foo(t: Tsp): Tsp = null.asInstanceOf[Tsp]();
    def foo_J(T_TypeTag: Byte, t: Long): Long = MiniboxConversions.this.box2minibox_tt[Tsp](C_L.this.foo(MiniboxConversions.this.minibox2box[Tsp](t, T_TypeTag)), T_TypeTag)
  };
  object Test extends Object with App {
    def <init>(): miniboxing.tests.compile.bug102.Test.type = {
      Test.super.<init>();
      ()
    };
    scala.this.Predef.println(MiniboxConversions.this.minibox2int(new miniboxing.tests.compile.bug102.C_J[Int](5).foo_J(5, MiniboxConversions.this.int2minibox(3))))
  }
}
```

**Comment by VladUreche** [comment]
Duplicate of #102 :))
