### ISSUE TITLE
Duplicators invalid label param owner

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#107]
```
sun@sun-cpu:/mnt/data1/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ cat gh-bug-107.scala 
package miniboxing.tests.compile.bug107

import annotation.tailrec

object Test {
  def foldDigitsLeft[@miniboxed A](a: A)(f: (A, Int) => A): A = {
    @tailrec def recur(next: Natural, sofar: A): A = next match {
      case End(d) => f(a, d)
      case Digit(d, tail) => recur(tail, f(a, d))
    }
    recur(???, a)
  }

  abstract class Natural
  case class End(d: Int) extends Natural
  case class Digit(d: Int, tl: Natural) extends Natural
}
sun@sun-cpu:/mnt/data1/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ ../mb-scalac gh-bug-107.scala 
Picked up _JAVA_OPTIONS: -Xms2g -Xmx2g -Xss4m -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=256m -XX:PermSize=256m -XX:+TieredCompilation -XX:+UseNUMA
error: symbol value x does not exist in miniboxing.tests.compile.bug107.Test.foldDigitsLeft_n_J
error: scala.reflect.internal.FatalError:
  symbol value x does not exist in miniboxing.tests.compile.bug107.Test.foldDigitsLeft_n_J
     while compiling: gh-bug-107.scala
        during phase: icode
     library version: version 2.11.1-20140519-130118-1e1defd99c
    compiler version: version 2.11.1-20140519-130118-1e1defd99c
  reconstructed args: -bootclasspath /home/sun/workspace/dev/miniboxing-plugin//components/runtime/target/scala-2.11/miniboxing-runtime_2.11-0.3-SNAPSHOT.jar:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.11/miniboxing-plugin_2.11-0.3-SNAPSHOT.jar -Xplugin:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.11/miniboxing-plugin_2.11-0.3-SNAPSHOT.jar

  last tree to typer: Ident(tl)
       tree position: line 16 of gh-bug-107.scala
            tree tpe: miniboxing.tests.compile.bug107.Test$Natural
              symbol: value tl
   symbol definition: tl: miniboxing.tests.compile.bug107.Test$Natural (a TermSymbol)
      symbol package: miniboxing.tests.compile.bug107
       symbol owners: value tl -> constructor Test$Digit -> class Test$Digit
           call site: constructor Test$Digit in object Test$Digit in package bug107

== Source file context for tree position ==

    13   abstract class Natural
    14   case class End(d: Int) extends Natural
    15   case class Digit(d: Int, tl: Natural) extends Natural
    16 }
    at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:58)
    at scala.tools.nsc.Global.abort(Global.scala:269)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase.genLoadIdent$1(GenICode.scala:885)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase.scala$tools$nsc$backend$icode$GenICode$ICodePhase$$genLoad(GenICode.scala:891)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase$$anonfun$genLoadArguments$1.apply(GenICode.scala:1133)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase$$anonfun$genLoadArguments$1.apply(GenICode.scala:1131)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:110)
    at scala.collection.immutable.List.foldLeft(List.scala:83)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase.genLoadArguments(GenICode.scala:1131)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase.genLoadApply6$1(GenICode.scala:778)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase.scala$tools$nsc$backend$icode$GenICode$ICodePhase$$genLoad(GenICode.scala:809)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase.gen(GenICode.scala:123)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase$$anonfun$gen$1.apply(GenICode.scala:71)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase$$anonfun$gen$1.apply(GenICode.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:383)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase.gen(GenICode.scala:71)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase.gen(GenICode.scala:148)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase.gen(GenICode.scala:98)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase$$anonfun$gen$1.apply(GenICode.scala:71)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase$$anonfun$gen$1.apply(GenICode.scala:71)
    at scala.collection.immutable.List.foreach(List.scala:383)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase.gen(GenICode.scala:71)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase.gen(GenICode.scala:89)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase.gen(GenICode.scala:67)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase.apply(GenICode.scala:63)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:430)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:397)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:397)
    at scala.collection.Iterator$class.foreach(Iterator.scala:743)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:397)
    at scala.tools.nsc.backend.icode.GenICode$ICodePhase.run(GenICode.scala:55)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1625)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1610)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1605)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1703)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:34)
    at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
    at scala.tools.nsc.Driver.process(Driver.scala:55)
    at scala.tools.nsc.Driver.main(Driver.scala:68)
    at scala.tools.nsc.Main.main(Main.scala)
```

**Comment by VladUreche** [comment]
Hmm, seems to compile now. Need to investigate.

**Comment by VladUreche** [comment]
The current solution, although more relaxed than necessary, did not cause any issues in the last 100 commits. Making it more strict, on the other hand, is known to cause issues like the one above. Therefore, I'd rather keep the relaxed solution, unless someone complains about it.
