### ISSUE TITLE
Don't mix specializations

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#117]
```
$ cat mb_spec_hijack_3.scala 
package miniboxing.tests.compile.mark.all.flag

class C[T, @specialized U, @miniboxed V]


 ../mb-scalac mb_spec_hijack_3.scala 

mb_spec_hijack_3.scala:3: warning: Class miniboxing.tests.compile.mark.all.flag.C_D differs only in case from miniboxing.tests.compile.mark.all.flag.C_D. Such classes will overwrite one another on case-insensitive filesystems.
class C[T, @specialized U, @miniboxed V]
      ^
mb_spec_hijack_3.scala:3: warning: Class miniboxing.tests.compile.mark.all.flag.C_J differs only in case from miniboxing.tests.compile.mark.all.flag.C_J. Such classes will overwrite one another on case-insensitive filesystems.
class C[T, @specialized U, @miniboxed V]
      ^
mb_spec_hijack_3.scala:3: warning: Class miniboxing.tests.compile.mark.all.flag.C_L differs only in case from miniboxing.tests.compile.mark.all.flag.C_L. Such classes will overwrite one another on case-insensitive filesystems.
class C[T, @specialized U, @miniboxed V]
      ^
error: java.lang.AssertionError: assertion failed:
  Different class symbols have the same bytecode-level internal name:
     name: miniboxing/tests/compile/mark/all/flag/C_D
   oldsym: miniboxing.tests.compile.mark.all.flag.C_D
  tracked: miniboxing.tests.compile.mark.all.flag.C_D

     while compiling: mb_spec_hijack_3.scala
        during phase: jvm
     library version: version 2.11.1-20140519-130118-1e1defd99c
    compiler version: version 2.11.1-20140519-130118-1e1defd99c
  reconstructed args: -Xplugin:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.11/miniboxing-plugin_2.11-0.4-SNAPSHOT.jar -bootclasspath /home/sun/workspace/dev/miniboxing-plugin//components/runtime/target/scala-2.11/miniboxing-runtime_2.11-0.4-SNAPSHOT.jar:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.11/miniboxing-plugin_2.11-0.4-SNAPSHOT.jar

  last tree to typer: term miniboxing|tests|compile|mark|all|flag|C_J|V_TypeTag
       tree position: line 3 of mb_spec_hijack_3.scala
            tree tpe: <notype>
              symbol: private[this] value miniboxing|tests|compile|mark|all|flag|C_J|V_TypeTag in class C_J
   symbol definition: private[this] val miniboxing|tests|compile|mark|all|flag|C_J|V_TypeTag: Byte (a TermSymbol)
      symbol package: miniboxing.tests.compile.mark.all.flag
       symbol owners: value miniboxing|tests|compile|mark|all|flag|C_J|V_TypeTag -> class C_J
           call site: method $init$ in object C$mcZ$sp$class in package flag

== Source file context for tree position ==

     0 package miniboxing.tests.compile.mark.all.flag
     1
     2 class C[T, @specialized U, @miniboxed V]
    at scala.tools.nsc.Global.assert(Global.scala:252)
    at scala.tools.nsc.backend.jvm.GenASM$JBuilder.javaName(GenASM.scala:556)
    at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genClass(GenASM.scala:1196)
    at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.emitFor$1(GenASM.scala:135)
    at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.run(GenASM.scala:141)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1625)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1610)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1605)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1703)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:34)
    at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
    at scala.tools.nsc.Driver.process(Driver.scala:55)
    at scala.tools.nsc.Driver.main(Driver.scala:68)
    at scala.tools.nsc.Main.main(Main.scala)
Exception in thread "main" java.lang.AssertionError: assertion failed: 
  Different class symbols have the same bytecode-level internal name:
     name: miniboxing/tests/compile/mark/all/flag/C_D
   oldsym: miniboxing.tests.compile.mark.all.flag.C_D
  tracked: miniboxing.tests.compile.mark.all.flag.C_D

     while compiling: mb_spec_hijack_3.scala
        during phase: jvm
     library version: version 2.11.1-20140519-130118-1e1defd99c
    compiler version: version 2.11.1-20140519-130118-1e1defd99c
  reconstructed args: -Xplugin:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.11/miniboxing-plugin_2.11-0.4-SNAPSHOT.jar -bootclasspath /home/sun/workspace/dev/miniboxing-plugin//components/runtime/target/scala-2.11/miniboxing-runtime_2.11-0.4-SNAPSHOT.jar:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.11/miniboxing-plugin_2.11-0.4-SNAPSHOT.jar

  last tree to typer: term miniboxing|tests|compile|mark|all|flag|C_J|V_TypeTag
       tree position: line 3 of mb_spec_hijack_3.scala
            tree tpe: <notype>
              symbol: private[this] value miniboxing|tests|compile|mark|all|flag|C_J|V_TypeTag in class C_J
   symbol definition: private[this] val miniboxing|tests|compile|mark|all|flag|C_J|V_TypeTag: Byte (a TermSymbol)
      symbol package: miniboxing.tests.compile.mark.all.flag
       symbol owners: value miniboxing|tests|compile|mark|all|flag|C_J|V_TypeTag -> class C_J
           call site: method $init$ in object C$mcZ$sp$class in package flag

== Source file context for tree position ==

     0 package miniboxing.tests.compile.mark.all.flag
     1 
     2 class C[T, @specialized U, @miniboxed V]
    at scala.tools.nsc.Global.assert(Global.scala:252)
    at scala.tools.nsc.backend.jvm.GenASM$JBuilder.javaName(GenASM.scala:556)
    at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genClass(GenASM.scala:1196)
    at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.emitFor$1(GenASM.scala:135)
    at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.run(GenASM.scala:141)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1625)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1610)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1605)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1703)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:34)
    at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
    at scala.tools.nsc.Driver.process(Driver.scala:55)
    at scala.tools.nsc.Driver.main(Driver.scala:68)
    at scala.tools.nsc.Main.main(Main.scala)
```

**Comment by VladUreche** [comment]
Insight: even if the translation would succeed, one would still not be able to benefit the specialization, as rewiring wouldn't be able to use the doubly-specialized members :|

**TODO:** Also protect against:

``` scala
class C[@miniboxed @specialized T]
```

:))
