### ISSUE TITLE
Compiler crash when adding miniboxing (even when not using the annotation)

### ISSUE THREAD

**Issue by pstutz** [miniboxing/miniboxing-plugin#118]
Hi, thanks for the interesting work on this.
I tried to use miniboxing, but adding the compiler plugin and dependency leads to a compiler crash on my project (https://travis-ci.org/uzh/signal-collect/builds/31350365), even when I don't actually use the miniboxing annotation:

```
scala.reflect.internal.Types$TypeError: type mismatch;
 found   : (some other)_$9(in value v)
 required: _$9(in value v)
    at scala.tools.nsc.typechecker.Contexts$Context.issue(Contexts.scala:560)
    at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueTypeError(ContextErrors.scala:97)
    at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueNormalTypeError(ContextErrors.scala:86)
    at scala.tools.nsc.typechecker.ContextErrors$TyperContextErrors$TyperErrorGen$.AdaptTypeError(ContextErrors.scala:197)
    at scala.tools.nsc.typechecker.Typers$Typer.adaptMismatchedSkolems$1(Typers.scala:1006)
    at scala.tools.nsc.typechecker.Typers$Typer.fallbackAfterVanillaAdapt$1(Typers.scala:1075)
    at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1112)
    at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1155)
    at miniboxing.plugin.transform.interop.coerce.InteropCoerceTreeTransformer$TreeAdapters$TreeAdapter.adapt(InteropCoerceTreeTransformer.scala:95)
    at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5307)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
    at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
    at miniboxing.plugin.transform.interop.coerce.InteropCoerceTreeTransformer$TreeAdapters$TreeAdapter.typed(InteropCoerceTreeTransformer.scala:135)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$81.apply(Typers.scala:4108)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$81.apply(Typers.scala:4108)
    at scala.collection.immutable.List.loop$1(List.scala:172)
    at scala.collection.immutable.List.mapConserve(List.scala:188)
    at scala.tools.nsc.typechecker.Typers$Typer.typedArrayValue$1(Typers.scala:4108)
    at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5228)
    at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5250)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5257)
    at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
    at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
    at miniboxing.plugin.transform.interop.coerce.InteropCoerceTreeTransformer$TreeAdapters$TreeAdapter.typed(InteropCoerceTreeTransformer.scala:135)
    at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:3102)
    at scala.tools.nsc.typechecker.PatternTypers$PatternTyper$class.typedArgWithFormal$1(PatternTypers.scala:112)
    at scala.tools.nsc.typechecker.PatternTypers$PatternTyper$$anonfun$2.apply(PatternTypers.scala:115)
    at scala.tools.nsc.typechecker.PatternTypers$PatternTyper$$anonfun$2.apply(PatternTypers.scala:115)
    at scala.runtime.Tuple2Zipped$$anonfun$map$extension$1.apply(Tuple2Zipped.scala:42)
    at scala.runtime.Tuple2Zipped$$anonfun$map$extension$1.apply(Tuple2Zipped.scala:40)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.runtime.Tuple2Zipped$.map$extension(Tuple2Zipped.scala:40)
    at scala.tools.nsc.typechecker.PatternTypers$PatternTyper$class.typedArgsForFormals(PatternTypers.scala:115)
    at scala.tools.nsc.typechecker.Typers$Typer.typedArgsForFormals(Typers.scala:107)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$handleMonomorphicCall$1(Typers.scala:3393)
    at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3418)
    at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4449)
    at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4482)
    at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5240)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5257)
    at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
    at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
    at miniboxing.plugin.transform.interop.coerce.InteropCoerceTreeTransformer$TreeAdapters$TreeAdapter.typed(InteropCoerceTreeTransformer.scala:135)
    at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:3102)
    at scala.tools.nsc.typechecker.PatternTypers$PatternTyper$class.typedArgWithFormal$1(PatternTypers.scala:112)
    at scala.tools.nsc.typechecker.PatternTypers$PatternTyper$$anonfun$2.apply(PatternTypers.scala:115)
    at scala.tools.nsc.typechecker.PatternTypers$PatternTyper$$anonfun$2.apply(PatternTypers.scala:115)
    at scala.runtime.Tuple2Zipped$$anonfun$map$extension$1.apply(Tuple2Zipped.scala:42)
    at scala.runtime.Tuple2Zipped$$anonfun$map$extension$1.apply(Tuple2Zipped.scala:40)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.runtime.Tuple2Zipped$.map$extension(Tuple2Zipped.scala:40)
    at scala.tools.nsc.typechecker.PatternTypers$PatternTyper$class.typedArgsForFormals(PatternTypers.scala:115)
    at scala.tools.nsc.typechecker.Typers$Typer.typedArgsForFormals(Typers.scala:107)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$handleMonomorphicCall$1(Typers.scala:3393)
    at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3418)
    at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4449)
    at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4482)
    at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5240)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5257)
    at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
    at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
    at miniboxing.plugin.transform.interop.coerce.InteropCoerceTreeTransformer$TreeAdapters$TreeAdapter.typed(InteropCoerceTreeTransformer.scala:135)
    at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:5502)
    at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:2177)
    at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5205)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5256)
    at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
    at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
    at miniboxing.plugin.transform.interop.coerce.InteropCoerceTreeTransformer$TreeAdapters$TreeAdapter.typed(InteropCoerceTreeTransformer.scala:135)
    at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5349)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2985)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
    at scala.collection.immutable.List.loop$1(List.scala:172)
    at scala.collection.immutable.List.mapConserve(List.scala:188)
    at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3089)
    at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1892)
    at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1738)
    at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5206)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5256)
    at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
    at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
    at miniboxing.plugin.transform.interop.coerce.InteropCoerceTreeTransformer$TreeAdapters$TreeAdapter.typed(InteropCoerceTreeTransformer.scala:135)
    at scala.tools.nsc.typechecker.Typers$Typer.typedByValueExpr(Typers.scala:5349)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2985)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3089)
    at scala.collection.immutable.List.loop$1(List.scala:172)
    at scala.collection.immutable.List.mapConserve(List.scala:188)
    at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3089)
    at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:4916)
    at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5209)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5256)
    at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5293)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5320)
    at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5267)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5271)
    at miniboxing.plugin.transform.interop.coerce.InteropCoerceTreeTransformer$TreeAdapters$TreeAdapter.typed(InteropCoerceTreeTransformer.scala:135)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5345)
    at miniboxing.plugin.transform.interop.coerce.InteropCoerceTreeTransformer$TreeAdapters.adapt(InteropCoerceTreeTransformer.scala:55)
    at miniboxing.plugin.transform.interop.coerce.InteropCoerceTreeTransformer$CoercePhase$$anonfun$1.apply(InteropCoerceTreeTransformer.scala:42)
    at miniboxing.plugin.transform.interop.coerce.InteropCoerceTreeTransformer$CoercePhase$$anonfun$1.apply(InteropCoerceTreeTransformer.scala:42)
    at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:235)
    at scala.reflect.internal.SymbolTable.exitingPhase(SymbolTable.scala:256)
    at miniboxing.plugin.ScalacCrossCompilingLayer$RichGlobal.afterPhase(ScalacCrossCompilingLayer.scala:19)
    at miniboxing.plugin.InteropCoerceComponent$class.afterInteropCoerce(Minibox.scala:65)
    at miniboxing.plugin.Minibox$InteropCoercePhase$.afterInteropCoerce(Minibox.scala:294)
    at miniboxing.plugin.transform.interop.coerce.InteropCoerceTreeTransformer$CoercePhase.apply(InteropCoerceTreeTransformer.scala:42)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:410)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:377)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:377)
    at scala.collection.Iterator$class.foreach(Iterator.scala:743)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1177)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:377)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1542)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1537)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1644)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:123)
    at xsbt.CachedCompiler0.run(CompilerInterface.scala:99)
    at xsbt.CompilerInterface.run(CompilerInterface.scala:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:102)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:48)
    at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
    at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply$mcV$sp(AggressiveCompile.scala:98)
    at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:98)
    at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:98)
    at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:159)
    at sbt.compiler.AggressiveCompile$$anonfun$3.compileScala$1(AggressiveCompile.scala:97)
    at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:142)
    at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:86)
    at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:38)
    at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:36)
    at sbt.inc.Incremental$.cycle(Incremental.scala:73)
    at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:33)
    at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:32)
    at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:41)
    at sbt.inc.Incremental$.compile(Incremental.scala:32)
    at sbt.inc.IncrementalCompile$.apply(Compile.scala:26)
    at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:150)
    at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:70)
    at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:45)
    at sbt.Compiler$.apply(Compiler.scala:70)
    at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:722)
    at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:716)
    at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:716)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:744)
[error] (compile:compile) scala.reflect.internal.Types$TypeError: type mismatch;
[error]  found   : (some other)_$9(in value v)
[error]  required: _$9(in value v)
```

**Comment by VladUreche** [comment]
@pstutz, thank you for the bug report! 
I can confirm just adding the miniboxing plugin without activating the transformation can lead to this crash, although I thought I solved the problem a while ago. I will try to reduce it down to a small example, so I can diagnose further.

**Comment by VladUreche** [comment]
@pstutz, I made a patch that fixes the error, but compilation ends up in an infinite loop now. I'll debug this further once I'm back in Lausanne on Wednesday.

**Comment by pstutz** [comment]
Thanks a lot, I'm looking forward to trying it out again.

**Comment by VladUreche** [comment]
@pstutz, I isolated the problem (let's treat the infinite loop as another issue, to simplify things):

```
sun@sun-cpu:/mnt/data1/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ cat gh-bug-112.scala 
package miniboxing.tests.compile.bug112


class Vertex[@specialized(Int, Long) +Id]{
  def id: Id = ???
}

class SampleVertexIds {
  def extract(v: Vertex[_]): List[Any] = {
    List(v.id)
  }
}

sun@sun-cpu:/mnt/data1/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ ../mb-scalac gh-bug-112.scala 
error: scala.reflect.internal.Types$TypeError: type mismatch;
 found   : (some other)_$1(in value v)
 required: _$1(in value v)
    at scala.tools.nsc.typechecker.Contexts$Context.issueCommon(Contexts.scala:555)
    at scala.tools.nsc.typechecker.Contexts$Context.issue(Contexts.scala:560)
    at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueTypeError(ContextErrors.scala:97)
    at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueNormalTypeError(ContextErrors.scala:86)
    at scala.tools.nsc.typechecker.ContextErrors$TyperContextErrors$TyperErrorGen$.AdaptTypeError(ContextErrors.scala:197)
    at scala.tools.nsc.typechecker.Typers$Typer.adaptMismatchedSkolems$1(Typers.scala:1022)
    at scala.tools.nsc.typechecker.Typers$Typer.fallbackAfterVanillaAdapt$1(Typers.scala:1090)
    at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1127)
    at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1170)
        ....
```

I'll file another bug for the infinite loop, even if the two may be related.

**Comment by pstutz** [comment]
Oh wow, it sounds like a quest chain in an adventure game. Thanks a lot for looking into this so quickly!

**Comment by VladUreche** [comment]
> Oh wow, it sounds like a quest chain in an adventure game.

I really hope I won't encounter a boss at the end of the quest chain. :p
