### ISSUE TITLE
Side-effecting statements should not refer to class fields

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#127]
``` scala
$ cat gh-bug-127.scala 
package miniboxing.tests.compile.bug126

class Config

class Graph[@miniboxed Id](b: Config) {
  println(b)
}

object Test {
  def main(args: Array[String]): Unit = {
    new Graph[Int](new Config)
  }
}

$ ../mb-scalac gh-bug-127.scala 
gh-bug-127.scala:6: warning: Side-effecting constructor statement will not be specializedin miniboxed class/trait Graph.
This is a technical limitation that can be worked around: https://github.com/miniboxing/miniboxing-plugin/issues/64
  println(b)
         ^
one warning found

$ ../mb-scala miniboxing.tests.compile.bug126.Test
java.lang.NoSuchFieldError: miniboxing$tests$compile$bug126$Graph$$b
    at miniboxing.tests.compile.bug126.Graph$class.$init$(gh-bug-127.scala:6)
    at miniboxing.tests.compile.bug126.Graph_J.<init>(gh-bug-127.scala:9)
    at miniboxing.tests.compile.bug126.Test$.main(gh-bug-127.scala)
    at miniboxing.tests.compile.bug126.Test.main(gh-bug-127.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    ...
```

**Comment by VladUreche** [comment]
Ping #64.

**Comment by VladUreche** [comment]
Another one:

``` scala
$ cat gh-bug-127b.scala 
package miniboxing.tests.compile.bug127b

class Config

class Graph[@miniboxed Id](b: Config) {
  class GraphImpl[@miniboxed Id] {
    println(b)
  }
  new GraphImpl[Id]
}

object Test {
  def main(args: Array[String]): Unit = {
    new Graph[Int](new Config)
  }
}

$ ../mb-scalac gh-bug-127b.scala 
gh-bug-127b.scala:9: warning: Side-effecting constructor statement will not be specializedin miniboxed class/trait Graph.
This is a technical limitation that can be worked around: https://github.com/miniboxing/miniboxing-plugin/issues/64
  new GraphImpl[Id]
  ^
gh-bug-127b.scala:7: warning: Side-effecting constructor statement will not be specializedin miniboxed class/trait GraphImpl.
This is a technical limitation that can be worked around: https://github.com/miniboxing/miniboxing-plugin/issues/64
    println(b)
           ^
two warnings found

$ ../mb-scala miniboxing.tests.compile.bug127b.Test
java.lang.NoSuchFieldError: miniboxing$tests$compile$bug127b$Graph$$b
    at miniboxing.tests.compile.bug127b.Graph$GraphImpl$class.$init$(gh-bug-127b.scala:7)
    at miniboxing.tests.compile.bug127b.Graph$GraphImpl_L.<init>(gh-bug-127b.scala:9)
    at miniboxing.tests.compile.bug127b.Graph$class.$init$(gh-bug-127b.scala:5)
    at miniboxing.tests.compile.bug127b.Graph_J.<init>(gh-bug-127b.scala:12)
    at miniboxing.tests.compile.bug127b.Test$.main(gh-bug-127b.scala)
    at miniboxing.tests.compile.bug127b.Test.main(gh-bug-127b.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```
