### ISSUE TITLE
SI-4971 also affects miniboxing

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#128]
https://issues.scala-lang.org/browse/SI-4971

**Comment by VladUreche** [comment]
At least specialization doesn't crash:

``` scala
error: scala.reflect.internal.Types$TypeError: illegal inheritance;
 self-type B_D[Vsp] does not conform to A[Int,V]'s selftype A[Int,V]
    at scala.tools.nsc.typechecker.Contexts$Context.issueCommon(Contexts.scala:555)
    at scala.tools.nsc.typechecker.Contexts$Context.issue(Contexts.scala:560)
    at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueTypeError(ContextErrors.scala:97)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$validateParentClasses$3.apply(Typers.scala:1724)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$validateParentClasses$3.apply(Typers.scala:1724)
    at scala.collection.immutable.List.foreach(List.scala:383)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
    at scala.tools.nsc.typechecker.Typers$Typer.validateParentClasses(Typers.scala:1724)
    at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1879)
    at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1753)
    at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5218)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5268)
    at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5305)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5332)
    at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5279)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5283)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5357)
    at miniboxing.plugin.transform.inject.MiniboxInjectTreeTransformation$MiniboxTreeTransformer$$anonfun$13.apply(MiniboxDuplTreeTransformation.scala:152)
    at miniboxing.plugin.transform.inject.MiniboxInjectTreeTransformation$MiniboxTreeTransformer$$anonfun$13.apply(MiniboxDuplTreeTransformation.scala:147)
    at scala.collection.immutable.List.map(List.scala:274)
    at miniboxing.plugin.transform.inject.MiniboxInjectTreeTransformation$MiniboxTreeTransformer.rewrite(MiniboxDuplTreeTransformation.scala:147)
    at miniboxing.plugin.transform.inject.TreeRewriters$TreeRewriter$$anonfun$transformStats$1.apply(TreeRewriter.scala:44)
    at miniboxing.plugin.transform.inject.TreeRewriters$TreeRewriter$$anonfun$transformStats$1.apply(TreeRewriter.scala:42)
    at scala.collection.immutable.List.flatMap(List.scala:329)
    at miniboxing.plugin.transform.inject.TreeRewriters$TreeRewriter.transformStats(TreeRewriter.scala:42)
    at miniboxing.plugin.transform.inject.TreeRewriters$TreeRewriter.transformStats(TreeRewriter.scala:25)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1419)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1419)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:17)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1418)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.scala$tools$nsc$transform$TypingTransformers$TypingTransformer$$super$transform(TypingTransformers.scala:40)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$2.apply(TypingTransformers.scala:42)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$2.apply(TypingTransformers.scala:42)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:42)
    at miniboxing.plugin.transform.inject.TreeRewriters$TreeRewriter.transform(TreeRewriter.scala:35)
    at miniboxing.plugin.Minibox$MiniboxInjectPhase$$anon$4$$anonfun$1.apply(Minibox.scala:381)
    at miniboxing.plugin.Minibox$MiniboxInjectPhase$$anon$4$$anonfun$1.apply(Minibox.scala:381)
    at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:242)
    at scala.reflect.internal.SymbolTable.exitingPhase(SymbolTable.scala:263)
    at miniboxing.plugin.ScalacCrossCompilingLayer$RichGlobal.afterPhase(ScalacCrossCompilingLayer.scala:19)
    at miniboxing.plugin.MiniboxInjectComponent$class.afterMiniboxInject(Minibox.scala:115)
    at miniboxing.plugin.Minibox$MiniboxInjectPhase$.afterMiniboxInject(Minibox.scala:359)
    at miniboxing.plugin.Minibox$MiniboxInjectPhase$$anon$4.transform(Minibox.scala:381)
    at miniboxing.plugin.Minibox$MiniboxInjectPhase$$anon$4.transform(Minibox.scala:378)
    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:147)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:430)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:397)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:397)
    at scala.collection.Iterator$class.foreach(Iterator.scala:743)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1174)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:397)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1625)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1610)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1605)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1703)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:34)
    at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
    at scala.tools.nsc.Driver.process(Driver.scala:55)
    at scala.tools.nsc.Driver.main(Driver.scala:68)
    at scala.tools.nsc.Main.main(Main.scala)
```
