### ISSUE TITLE
`@strict` annotation for miniboxed type parameters

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#130]
Or something similar -- to say it needs to be miniboxed:

``` scala
class C[@strict @miniboxed T] 

object Test extends App {
  // no warning, the type argument is a subtype of AnyRef:
  new C[String] // => unspecialized C_L

  // warning, the type parameter is not a subtype of AnyRef, but it's not miniboxed and is not a primitive:
  new C[T forSome { type T <: Int }] // => unspecialized C_L

  // no warning, the type argument is specialized:
  new C[Int] // => specialized C_J
}
```

I propose the following steps:
- Add a `@strict` annotation in the miniboxing library;
- Issue an error for any `@strict` type paramter:
  - if the argument has not been specialized;
  - subtypes of `AnyRef` are accepted as shown before;
- Add two compiler plugin flags, similar to `-P:minibox:mark`:
  - `-P:minibox:all-strict` which adds a `@strict` annotation to **all miniboxed type parameters in the current compilation run (not the classpath)**;
  - `-P:minibox:all-strict-cp` which adds a `@strict` annotation to **all miniboxed type parameters, regardless where they come from**;

Thanks @pstutz for the idea!

**Comment by VladUreche** [comment]
Or this could be the default behavior, with a compiler flag to disable it :)

**Comment by pstutz** [comment]
Cool, that would be very useful. It would be nice if one had the option of throwing an exception if the class is instantiated with a boxed primitive. This way I could add regression tests that fail when miniboxing is no longer working.

**Comment by VladUreche** [comment]
This is information we have at compile-time, so why defer it to runtime?

**Comment by VladUreche** [comment]
@dragos @axel22 @non @tixxit @DarkDimius @ichoran, WDYT? Any idea where this may fall short?

**Comment by dragos** [comment]
Would this concern only instantiations, or also other uses?

**Comment by Ichoran** [comment]
I think this idea looks good, but the example is not likely to be helpful for people wanting to use this annotation.  Not very many people manually write subtypes of Int using foreach notation in comparison to how many might have an Any floating around.  Also, I vote for strict being default.  Regular specialization is plagued by despecializing without noticing it.  Rather, use an unchecked annotation if you want it to not be miniboxed.

I second Iulian's question about other uses (specifically I'd like to know how inheritance and annotated methods work).

**Comment by VladUreche** [comment]
> Would this concern only instantiations, or also other uses?

Sorry for underspecifying. The warning concerns four cases:
- instantiations
- method rewrites based on the receiver (specialization)
- method rewrites based on type arguments (normalization)
- parent type rewrites

>  Not very many people manually write subtypes of Int using foreach notation in comparison to how many might have an Any floating around.

Right. But for example, the same warning would be triggered by this code:

``` scala
class C[@strict @miniboxed T]

class D[X] extends C[X] { // <= warning, X is not subtype of AnyRef, primitive or miniboxed
  val c = new C[X]        // <= warning, X is not subtype of AnyRef, primitive or miniboxed
}
```

> Also, I vote for strict being default. Regular specialization is plagued by despecializing without noticing it. Rather, use an unchecked annotation if you want it to not be miniboxed.

I see, though I'd hate to drop tens of warnings on the users when they switch from specialization to miniboxing. WDYT about hiding this under a `-deprecation`-like warning?

**Comment by Ichoran** [comment]
For me, those tens of warnings would probably all elicit an "oh THANK you, so that's why it was so unexpectedly slow!".  (Or maybe it would just magically start being a lot faster, if the boxing was unnecessary in the specialized case.)  But being able to customize warnings is always a great feature.

**Comment by VladUreche** [comment]
Relevant discussion: https://groups.google.com/forum/#!topic/scala-user/oL-4Bldxu1M
An example derived from the discussion:

``` scala
trait KeyObserver[@miniboxed -A] {
  def keyUp(key: A) : Unit = {
    println((new Exception()).getStackTrace().toList.take(4).mkString("in ", "\n\tat ", "\n"))
  }
}
object NoKeyObserver extends KeyObserver[Any]

trait TestX[@miniboxed A] {
  def lala : A
  def obs : KeyObserver[A]

  def test() = obs.keyUp(lala)
}

object Test {
  def main(args: Array[String]): Unit = {
    new TestX[Int]{ def lala = 3; def obs = NoKeyObserver }.test()
    new TestX[Any]{ def lala = 3; def obs = NoKeyObserver }.test()
    new TestX[Int]{ def lala = 3; def obs = new KeyObserver[Any]{} }.test()
    new TestX[Int]{ def lala = 3; def obs = new KeyObserver[Int]{} }.test()
    new TestX[Any]{ def lala = 3; def obs = new KeyObserver[Any]{} }.test()
  }
}
```

Running the tests outputs:

```
in KeyObserver_L$class.keyUp(xxx.scala:3)
    at NoKeyObserver$.keyUp(xxx.scala:6)
    at KeyObserver_L$class.keyUp_J(xxx.scala)
    at NoKeyObserver$.keyUp_J(xxx.scala:6)

in KeyObserver_L$class.keyUp(xxx.scala:3)
    at NoKeyObserver$.keyUp(xxx.scala:6)
    at TestX_L$class.test(xxx.scala:12)
    at Test$$anon$2.test(xxx.scala:18)

in KeyObserver_L$class.keyUp(xxx.scala:3)
    at Test$$anon$3$$anon$4.keyUp(xxx.scala:19)
    at KeyObserver_L$class.keyUp_J(xxx.scala)
    at Test$$anon$3$$anon$4.keyUp_J(xxx.scala:19)

in KeyObserver_J$class.keyUp_J(xxx.scala:3)
    at Test$$anon$5$$anon$6.keyUp_J(xxx.scala:20)
    at TestX_J$class.test(xxx.scala:12)
    at Test$$anon$5.test(xxx.scala:20)

in KeyObserver_L$class.keyUp(xxx.scala:3)
    at Test$$anon$7$$anon$8.keyUp(xxx.scala:21)
    at TestX_L$class.test(xxx.scala:12)
    at Test$$anon$7.test(xxx.scala:21)
```

so we should be seeing at least 4 warnings :|

**Comment by VladUreche** [comment]
Closed by mistake, was referring to #131.

**Comment by VladUreche** [comment]
Almost there:

```
class C[@miniboxed T]
def boo[@miniboxed X] = new C[X]
def baz[X] = new C[X]
def baz[X] = boo[X]
class D[X] { new C[X] }
class D[X] { boo[X] }
```

Execution:

```
Welcome to Scala version 2.11.1-20140519-130118-1e1defd99c (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_72).
Type in expressions to have them evaluated.
Type :help for more information.

scala> class C[@miniboxed T]
defined class C

scala> def boo[@miniboxed X] = new C[X]
boo: [X]=> C[X]

scala> def baz[X] = new C[X]
<console>:8: warning: The following code could benefit from miniboxing specialization if the type parameter X of method baz would be marked as @miniboxed X
(it would be used to instantiate miniboxed type parameter T of C)
       def baz[X] = new C[X]
                    ^
baz: [X]=> C[X]

scala> def baz[X] = boo[X]
<console>:9: warning: The following code could benefit from miniboxing specialization if the type parameter X of method baz would be marked as @miniboxed X
(it would be used to instantiate miniboxed type parameter X of boo)
       def baz[X] = boo[X]
                       ^
baz: [X]=> C[X]

scala> class D[X] { new C[X] }
<console>:8: warning: The following code could benefit from miniboxing specialization if the type parameter X of class D would be marked as @miniboxed X
(it would be used to instantiate miniboxed type parameter T of C)
       class D[X] { new C[X] }
                    ^
defined class D

scala> class D[X] { boo[X] }
<console>:9: warning: The following code could benefit from miniboxing specialization if the type parameter X of class D would be marked as @miniboxed X
(it would be used to instantiate miniboxed type parameter X of boo)
       class D[X] { boo[X] }
                       ^
defined class D
```

**Comment by VladUreche** [comment]
And for the test in https://groups.google.com/forum/#!topic/scala-user/oL-4Bldxu1M:

```
scala> trait KeyObserver[@miniboxed -A] {
     |   def keyUp(key: A) : Unit = {
     |     println((new Exception()).getStackTrace().toList.take(4).mkString("in ", "\n\tat ", "\n"))
     |   }
     | }
defined trait KeyObserver

scala> object NoKeyObserver extends KeyObserver[Any]
<console>:8: warning: Using the type argument Any for the miniboxed type parameter A of trait KeyObserver is not specific enough, since it could mean either a primitive or a reference-based value.
       object NoKeyObserver extends KeyObserver[Any]
              ^
defined object NoKeyObserver

scala> 

scala> trait TestX[@miniboxed A] {
     |   def lala : A
     |   def obs : KeyObserver[A]
     | 
     |   def test() = obs.keyUp(lala)
     | }
defined trait TestX

scala> 

scala> object Test {
     |   def main(args: Array[String]): Unit = {
     |     new TestX[Int]{ def lala = 3; def obs = NoKeyObserver }.test()
     |     new TestX[Any]{ def lala = 3; def obs = NoKeyObserver }.test()
     |     new TestX[Int]{ def lala = 3; def obs = new KeyObserver[Any]{} }.test()
     |     new TestX[Int]{ def lala = 3; def obs = new KeyObserver[Int]{} }.test()
     |     new TestX[Any]{ def lala = 3; def obs = new KeyObserver[Any]{} }.test()
     |   }
     | }
<console>:13: warning: Using the type argument Any for the miniboxed type parameter A of trait TestX is not specific enough, since it could mean either a primitive or a reference-based value.
           new TestX[Any]{ def lala = 3; def obs = NoKeyObserver }.test()
               ^
<console>:13: warning: Using the type argument Any for the miniboxed type parameter A of trait TestX is not specific enough, since it could mean either a primitive or a reference-based value.
           new TestX[Any]{ def lala = 3; def obs = NoKeyObserver }.test()
                                                                   ^
<console>:14: warning: Using the type argument Any for the miniboxed type parameter A of trait KeyObserver is not specific enough, since it could mean either a primitive or a reference-based value.
           new TestX[Int]{ def lala = 3; def obs = new KeyObserver[Any]{} }.test()
                                                       ^
<console>:16: warning: Using the type argument Any for the miniboxed type parameter A of trait TestX is not specific enough, since it could mean either a primitive or a reference-based value.
           new TestX[Any]{ def lala = 3; def obs = new KeyObserver[Any]{} }.test()
               ^
<console>:16: warning: Using the type argument Any for the miniboxed type parameter A of trait KeyObserver is not specific enough, since it could mean either a primitive or a reference-based value.
           new TestX[Any]{ def lala = 3; def obs = new KeyObserver[Any]{} }.test()
                                                       ^
<console>:16: warning: Using the type argument Any for the miniboxed type parameter A of trait TestX is not specific enough, since it could mean either a primitive or a reference-based value.
           new TestX[Any]{ def lala = 3; def obs = new KeyObserver[Any]{} }.test()
                                                                            ^
defined object Test
```
