### ISSUE TITLE
PartialFunction + MiniboxedFunctionX => crash

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#135]
One of the concrete bugs in the #134 meta-bug:

```
$ cat gh-bug-XX.scala 

package miniboxing.tests.compile.bugXX

object Test {
  def main(args: Array[String]): Unit = {
    val pf: PartialFunction[Int, Int] = {
      case 0 => 1
      case 1 => 2
    }
    println(pf(0))
    println(pf(1))
    println(pf(2))
  }
}

$ ../mb-scalac gh-bug-XX.scala 

$ ../mb-scala miniboxing.tests.compile.bugXX.Test
java.lang.StackOverflowError
    at java.lang.Integer.intValue(Integer.java:701)
    at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:105)
    at miniboxing.tests.compile.bugXX.Test$$anonfun$1.isDefinedAt(gh-bug-XX.scala:5)
    at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118)
    at scala.runtime.AbstractPartialFunction.applyOrElse(AbstractPartialFunction.scala:28)
    at scala.runtime.AbstractPartialFunction$mcII$sp.apply$mcII$sp(AbstractPartialFunction.scala:36)
    at scala.runtime.AbstractPartialFunction$mcII$sp.apply(AbstractPartialFunction.scala:36)
    at scala.runtime.AbstractPartialFunction$mcII$sp.apply(AbstractPartialFunction.scala:28)
    at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118)
    at scala.runtime.AbstractPartialFunction.applyOrElse(AbstractPartialFunction.scala:28)
    at scala.runtime.AbstractPartialFunction$mcII$sp.apply$mcII$sp(AbstractPartialFunction.scala:36)
    at scala.runtime.AbstractPartialFunction$mcII$sp.apply(AbstractPartialFunction.scala:36)
    at scala.runtime.AbstractPartialFunction$mcII$sp.apply(AbstractPartialFunction.scala:28)
    at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:118)
```

**Comment by VladUreche** [comment]
The problem is that by transforming `FunctionX` parameters to `MiniboxedFunctionX`we break the overriding relationship:

```
def applyOrElse[A1 <: Int, B1 >: Int](x1: A1, default: MiniboxedFunction1[A1,B1]): B1
```

does not override

```
def applyOrElse[A1 <: Int, B1 >: Int](x1: A1, default: A1 => B1): B1
```

And this results in the ugly stacktrace seen above.

**Comment by VladUreche** [comment]
There are 2 approaches to fixing this issue:
1. Generate bridges (the solution in value classes)
2. Do not transform the signature when overriding (the solution in miniboxing, when transforming nested classes)

Of course, (1) is too heavyweight, so that leaves only (2) as a decent contender.

**Comment by VladUreche** [comment]
One more test case:

``` scala
$ cat question2.scala 
package miniboxing.tests.compile.question2

class C[U,V] {
  def foo(u: U, v: V) = true
}

class D[U] extends C[U, Int => Int] {
  override def foo(u: U, v: Int => Int) = false
  // the following method will become:
  //   override def foo(u: U, v: MbFunction1[Int, Int]) = true
  // and it should have 1 bridge:
  //   @bridge  def foo(u: U, v: Int => Int) = ...
}

class E extends D[String => String] {
  override def foo(u: String => String, v: Int => Int) = true
  // the following method will become:
  //   override def foo(u: MbFunction1[String, String], v: MbFunction1[Int, Int]) = true
  // and it should have 2 bridges:
  //   @bridge  def foo(u: String => String, v: MbFunction1[Int, Int]) = ...
  //   @bridge  def foo(u: String => String, v: Int => Int) = ...
}

$ ../mb-scalac question2.scala -Xprint:interop-commit
[[syntax trees at end of            interop-commit]] // question2.scala
package miniboxing.tests.compile.question2 {
  class C[U, V] extends Object {
    def foo(u: U, v: V): Boolean = true
  };
  class D[U] extends miniboxing.tests.compile.question2.C[U,Int => Int] {
    override def foo(u: U, v: miniboxing.runtime.MiniboxedFunction1[Int,Int]): Boolean = false
  };
  class E extends miniboxing.tests.compile.question2.D[String => String] {
    override def foo(u: miniboxing.runtime.MiniboxedFunction1[String,String], v: miniboxing.runtime.MiniboxedFunction1[Int,Int]): Boolean = true
  }
}
```
