### ISSUE TITLE
Add bridges to transformed methods in Duplicators

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#138]
Now, there are two rules:
(1) if the method is not overridden, transform it
(2) if the method is overridden, don't touch it

It's a good first approximation, but it could be better, since the current scheme is easy to defeat.

Here's the set of rulez:
(1) transform the method, encoding the type parameter
(2) add bridges where necessary, calling the unboxed version

And here's how to defeat the current scheme, also related to #135:

``` scala
$ cat bridges.scala 
package miniboxing.tests.compile.bugXXX

class Mb[@miniboxed T] {
  def foo(t: T) = { 

    class Fun1[R] {
      def apply(t: T): R = ???
    }

    class Fun2 extends Fun1[T] {
      override def apply(t: T): T = t
    }

    val f2 = new Fun2()
    val f1: Fun1[T] = f2
    println(f2.apply(t))
    println(f1.apply(t))
  }
}

object Test {
  def main(args: Array[String]): Unit = {
    new Mb[Int].foo(4)
    new Mb[String].foo("x")
    new Mb[Double].foo(3.0)
  }
}
$ ../mb-scalac bridges.scala 
$ ../mb-scala miniboxing.tests.compile.bugXXX.Test
4
scala.NotImplementedError: an implementation is missing
    at scala.Predef$.$qmark$qmark$qmark(Predef.scala:225)
    at miniboxing.tests.compile.bugXXX.Mb_J$Fun1$2.apply(bridges.scala:7)
    at miniboxing.tests.compile.bugXXX.Mb_J.foo_J(bridges.scala:17)
    at miniboxing.tests.compile.bugXXX.Test$.main(bridges.scala:23)
    at miniboxing.tests.compile.bugXXX.Test.main(bridges.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:68)
    at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
    at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:99)
    at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:68)
    at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:99)
    at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
    at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
    at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
    at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
    at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:72)
    at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:94)
    at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by VladUreche** [comment]
Closed by mistake, only added the infrastructure necessary to address this bug.

**Comment by VladUreche** [comment]
One more reason the fix is incorrect:

``` scala
$ cat gh-bug-138b.scala 
package miniboxing.tests.compile.bug138

abstract class Fun[T, R] {
  def apply(t: T): R
}

object Test {

  def foo[@miniboxed T] = {
    def bar[@miniboxed R] = {
      class D extends Fun[T, R] {
        def apply(t: T): R = ???
      }
    }
  }
}

$ mb-scalac gh-bug-138b.scala 
gh-bug-138b.scala:12: error: [ occured while creating miniboxed method bar_n_D ]
method apply is defined twice
  conflicting symbols both originated in file '/mnt/data1/Work/Workspace/dev/miniboxing-plugin/sandbox/gh-bug-138b.scala'
        def apply(t: T): R = ???
            ^
one error found
```
