### ISSUE TITLE
Follow-up on #138: we still need the name mangling

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#148]
Example:

``` scala
$ cat name-mangl.scala 
package miniboxing.tests.compile.bugXXX

abstract class Iterator[@miniboxed T] {
  def next(): T
}

object Test {
  def foo[@miniboxed V](v: V) = new Iterator[V] {
    def next(): V = v
  }

  def main(args: Array[String]): Unit = {
    val it: Iterator[_] = foo[Char]('a')
    println(it.next()) // expected: 'a'
                       // printed:   97
  }
}

$ ../mb-scalac name-mangl.scala

$ ../mb-scala miniboxing.tests.compile.bugXXX.Test
97
```

**Comment by VladUreche** [comment]
To see the bug in action, remove the `@miniboxed` annotation from `IterableLike` in `collection.scala`, which was added in https://github.com/miniboxing/miniboxing-plugin/commit/e13db8ca07eedb90f5d2794bb11d289c8e8b3f01. It should crash with:

```
java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Double
    at miniboxing.runtime.MiniboxConversions.box2minibox_deep(MiniboxConversions.java:175)
    at miniboxing.runtime.MiniboxConversions.box2minibox_tt(MiniboxConversions.java:152)
    at miniboxing.tests.compile.collctions1.Tuple2_LJ._1_JJ(newSource1.scala)
    at miniboxing.tests.compile.collctions1.LeastSquaresBenchmark$$anon$2.apply_LJ(newSource1.scala:247)
    at miniboxing.tests.compile.collctions1.LeastSquaresBenchmark$$anon$2.apply_LJ(newSource1.scala:252)
    at miniboxing.tests.compile.collctions1.TraversableLike_L$$anon$9.apply_LJ(newSource1.scala:72)
    at miniboxing.tests.compile.collctions1.List_L.foreach_n_J(newSource1.scala:166)
    at miniboxing.tests.compile.collctions1.TraversableLike_L$class.mapTo_n_J(newSource1.scala:72)
    at miniboxing.tests.compile.collctions1.List_L.mapTo_n_J(newSource1.scala:148)
    at miniboxing.tests.compile.collctions1.TraversableLike_L$class.map_n_J(newSource1.scala:76)
    at miniboxing.tests.compile.collctions1.List_L.map_n_J(newSource1.scala:148)
    at miniboxing.tests.compile.collctions1.LeastSquaresBenchmark$.delayedEndpoint$miniboxing$tests$compile$collctions1$LeastSquaresBenchmark$1(newSource1.scala:255)
    at miniboxing.tests.compile.collctions1.LeastSquaresBenchmark$delayedInit$body.apply(newSource1.scala:215)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at miniboxing.tests.compile.collctions1.LeastSquaresBenchmark$.main(newSource1.scala:215)
    at miniboxing.tests.compile.collctions1.LeastSquaresBenchmark.main(newSource1.scala)
```

**Comment by VladUreche** [comment]
Btw, this crash is related: https://travis-ci.org/miniboxing/miniboxing-plugin/builds/41561372
