### ISSUE TITLE
Interop-inject doesn't work for the REPL

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#152]
It was a test case in #135, but it's really a different bug:

```
scala> val f = (x: Int) => x
java.lang.NoSuchMethodError: .f()Lscala/Function1;
  at .$print$lzycompute(<console>:10)
  at .$print(<console>:6)
  at $print(<console>)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:606)
  at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:755)
  at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1002)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:609)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:608)
  at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
  at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:608)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:540)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:536)
  at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:750)
  at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:795)
  at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:662)
  at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:407)
  at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:430)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:864)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:850)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:850)
  at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
  at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:850)
  at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:74)
  at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
  at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
  at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
  at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by VladUreche** [comment]
No surprise here, it works perfectly on 2.10:

```
$ mb-scala -2.10
Welcome to Scala version 2.10.5-20140407-165700-ec05aeb3d6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_72).
Type in expressions to have them evaluated.
Type :help for more information.

scala> val f = (x: Int) => x
f: Int => Int = <function1>
```

Root cause is a change that recomputes the symbol signatures in the REPL:
https://github.com/scala/scala/commit/24a0777219d647ec310a0b6da305f619f69950cd
