### ISSUE TITLE
MiniboxedFunctions should be serializable

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#158]
Otherwise parallel test won't work. Little pricks...

**Comment by VladUreche** [comment]
```
$ cat gh-bug-158.scala 
package miniboxing.tests.compile.bug158

import java.io._

class NullOutputStream extends OutputStream {
  def write(b: Int): Unit = ()
}

object Test {
  def main(args: Array[String]): Unit = {
    val f = (x: Int) => x + 1

    val out = new ObjectOutputStream(new NullOutputStream());
    out.writeObject(f);
  }
}

$ mb-scalac gh-bug-158.scala 

$ mb-scala miniboxing.tests.compile.bug158.Test
java.io.NotSerializableException: miniboxing.runtime.AbstractMiniboxedFunction1_JJ$$anon$8
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1183)
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
    at miniboxing.tests.compile.bug158.Test$.main(gh-bug-158.scala:14)
    at miniboxing.tests.compile.bug158.Test.main(gh-bug-158.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
    at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
    at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
    at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
    at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
    at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
    at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
    at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
    at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
    at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
    at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
    at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
    at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```
