### ISSUE TITLE
"Duplicate method name&signature in class" when overriding in trait using super

### ISSUE THREAD

**Issue by nicolasstucki** [miniboxing/miniboxing-plugin#166]
**For the workaround, please see the comment below.**

When overriding a method inside a trait and using the super of that method. The method super$getStr method seams to have two declarations, one as abstract and one with the implementation.

```
trait A[@miniboxed T] {
    def getStr: String = "aaa"
}
trait B[@miniboxed T] extends A[T] {
    override def getStr: String = super.getStr
}
class C extends B[Int]
println(new C) /* force ClassLoader to try and load C */
```

```
....
 public java.lang.String super$getStr();
    Code:
       0: aload_0       
       1: invokestatic  #16                 // Method A_J$class.getStr:(LA_J;)Ljava/lang/String;
       4: areturn       
....
  public abstract java.lang.String super$getStr();
....
```

**Comment by VladUreche** [comment]
Gracias @nicolasstucki! Looking into it.

**Comment by VladUreche** [comment]
# Workaround

``` scala
$ cat gh-bug-166b.scala 
package miniboxing.tests.compile.bug166b

trait A[@miniboxed T] {
  def getStr: String = "aaa"
}
trait B[@miniboxed T] extends A[T] {
  override def getStr: String = super.getStr
  class X {
    def baz = println(B.super.getStr)
  }
}

$ mb-scalac gh-bug-166b.scala 
gh-bug-166b.scala:8: warning: The class X will not be miniboxed based on type parameter(s) T of miniboxed trait B. To have it specialized, add the type parameters of trait B, marked with "@miniboxed" to the definition of class X and instantiate it explicitly passing the type parameters from trait B:
  class X {
        ^
gh-bug-166b.scala:9: error: You ran into a fundamental limitation of the miniboxing transformation. When miniboxing trait B, the miniboxing plugin moves all the fields and super-accessors to the specialized subclasses. Therefore, trying to access them in the nested method miniboxing.tests.compile.bug166b.B.X.baz is not a valid pattern anymore. Please read https://github.com/miniboxing/miniboxing-plugin/issues/166 for a thorough explanation and some workarounds for the problem. Thanks and sorry!
    def baz = println(B.super.getStr)
                              ^
one warning found
one error found
```

Notice the error which prevents you from compiling. To work around it, add a method `def BsuperGetStr` in `B` which calls `super.getStr`. Then call that method from `X`:

``` scala
$ cat gh-bug-166b-workaround.scala 
package miniboxing.tests.compile.bug166b

trait A[@miniboxed T] {
  def getStr: String = "aaa"
}
trait B[@miniboxed T] extends A[T] {
  override def getStr: String = super.getStr

  // add a direct accessor in B:
  def BsuperGetStr = B.super.getStr

  class X {
    // call it from X:
    def baz = println(BsuperGetStr)
  }
}

$ mb-scalac gh-bug-166b-workaround.scala 
gh-bug-166b-workaround.scala:12: warning: The class X will not be miniboxed based on type parameter(s) T of miniboxed trait B. To have it specialized, add the type parameters of trait B, marked with "@miniboxed" to the definition of class X and instantiate it explicitly passing the type parameters from trait B:
  class X {
        ^
gh-bug-166b-workaround.scala:14: warning: The following code could benefit from miniboxing specialization (the reason was explained before).
    def baz = println(BsuperGetStr)
                      ^
two warnings found
```

Now, you still have warnings saying `X` should not be nested. Nevertheless, it's up to you whether you want to nest it or not.

# Old comment

Weird. It looks like phase mixin is creating 2 different superaccessors, with different symbols:

``` scala
$ cat gh-bug-166.scala
trait A[@miniboxed T] {
    def getStr: String = "aaa"
}
trait B[@miniboxed T] extends A[T] {
    override def getStr: String = super.getStr
}
class C extends B[Int]

object Test {
  def main(args: Array[String]): Unit =
    println(new C) /* force ClassLoader to try and load C */
}

$ mb-scalac gh-bug-166.scala -Xprint:mixin -uniqid
[[syntax trees at end of                     mixin]] // gh-bug-166.scala
package <empty>#4 {
  ...
  class C#7877 extends Object#130 with B_J#17719 {
    <superaccessor> <artifact> def super$getStr#33169(): String#232 = A_J$class#7887.getStr#33130(C#7877.this);
    override def getStr#33170(): String#232 = B_J$class#7842.getStr#33141(C#7877.this);
    <superaccessor> <artifact> def super$getStr#33171(): String#232 = A_J$class#7887.getStr#33130(C#7877.this);
    def A_J|T_TypeTag#17741(): Byte#2468 = 5;
    def B_J|T_TypeTag#17742(): Byte#2468 = 5;
    def <init>#16175(): C#7877 = ...
  };
  ...
}
$ mb-scala Test
java.lang.ClassFormatError: Duplicate method name&signature in class file C
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
```

**Comment by VladUreche** [comment]
Okay, I have a possible fix, but I'm not sure it's correct. I'm looking into this now.

**Comment by VladUreche** [comment]
And I've got a correct solution, not only for this bug, but also for #127. Coding it now.

**Comment by VladUreche** [comment]
Ping @nicolasstucki: Should work now :)

**Comment by VladUreche** [comment]
Btw, thanks a lot for reducing this, I agree it must have been crazy difficult!
