### ISSUE TITLE
Universal trait crasher

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#169]
The bug was found by @tixxit in https://github.com/non/algebra/pull/30#issuecomment-69285133:

```
$ cat gh-bug-169.scala 
package miniboxing.tests.compile.bug169

trait CommutativeSemigroup[@miniboxed A] extends Any { self =>
  def foo = ???
}

trait Semilattice[@miniboxed A] extends Any with CommutativeSemigroup[A] { self =>
  def bar = ???
}

trait BoundedSemilattice[@miniboxed A] extends Any with Semilattice[A] { self =>

  override def foo = ???
  override def bar = ???
}

$ mb-scalac gh-bug-169.scala 

error: scala.reflect.internal.Types$TypeError: secondary constructor is not allowed in universal trait extending from class Any
    at scala.tools.nsc.typechecker.Contexts$ThrowingReporter.handleError(Contexts.scala:1389)
    at scala.tools.nsc.typechecker.Contexts$ContextReporter.info0(Contexts.scala:1285)
    at scala.tools.nsc.typechecker.Contexts$ContextReporter.info0(Contexts.scala:1237)
    at scala.reflect.internal.Reporter.error(Reporting.scala:82)
    at scala.tools.nsc.typechecker.Contexts$Context.error(Contexts.scala:576)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$checkEphemeral$1.notAllowed$1(Typers.scala:1308)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$checkEphemeral$1.apply(Typers.scala:1317)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$checkEphemeral$1.apply(Typers.scala:1307)
    at scala.collection.immutable.List.foreach(List.scala:380)
    at scala.tools.nsc.typechecker.Typers$Typer.checkEphemeral(Typers.scala:1307)
    at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1726)
    at scala.tools.nsc.typechecker.Typers$Typer.typedMemberDef$1(Typers.scala:5210)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5260)
    at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5297)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5324)
    at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5271)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5275)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5349)
    at miniboxing.plugin.transform.minibox.inject.MiniboxInjectTreeTransformation$MiniboxTreeTransformer$$anonfun$18.apply(MiniboxDuplTreeTransformation.scala:265)
    at miniboxing.plugin.transform.minibox.inject.MiniboxInjectTreeTransformation$MiniboxTreeTransformer$$anonfun$18.apply(MiniboxDuplTreeTransformation.scala:260)
    at scala.collection.immutable.List.map(List.scala:272)
    at miniboxing.plugin.transform.minibox.inject.MiniboxInjectTreeTransformation$MiniboxTreeTransformer.rewrite(MiniboxDuplTreeTransformation.scala:260)
    at miniboxing.plugin.transform.infrastructure.TreeRewriters$TreeRewriter$$anonfun$transformStats$1.apply(TreeRewriter.scala:45)
    at miniboxing.plugin.transform.infrastructure.TreeRewriters$TreeRewriter$$anonfun$transformStats$1.apply(TreeRewriter.scala:43)
    at scala.collection.immutable.List.flatMap(List.scala:326)
    at miniboxing.plugin.transform.infrastructure.TreeRewriters$TreeRewriter.transformStats(TreeRewriter.scala:43)
    at miniboxing.plugin.transform.infrastructure.TreeRewriters$TreeRewriter.transformStats(TreeRewriter.scala:26)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1426)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1426)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:17)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1425)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.scala$tools$nsc$transform$TypingTransformers$TypingTransformer$$super$transform(TypingTransformers.scala:40)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$2.apply(TypingTransformers.scala:42)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$2.apply(TypingTransformers.scala:42)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:42)
    at miniboxing.plugin.transform.infrastructure.TreeRewriters$TreeRewriter.transform(TreeRewriter.scala:36)
    at miniboxing.plugin.Minibox$MiniboxInjectPhase$$anon$4$$anonfun$1.apply(Minibox.scala:487)
    at miniboxing.plugin.Minibox$MiniboxInjectPhase$$anon$4$$anonfun$1.apply(Minibox.scala:487)
    at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:235)
    at scala.reflect.internal.SymbolTable.exitingPhase(SymbolTable.scala:256)
    at miniboxing.plugin.ScalacCrossCompilingLayer$RichGlobal.afterPhase(ScalacCrossCompilingLayer.scala:22)
    at miniboxing.plugin.MiniboxInjectComponent$class.afterMiniboxInject(Minibox.scala:140)
    at miniboxing.plugin.Minibox$MiniboxInjectPhase$.afterMiniboxInject(Minibox.scala:461)
    at miniboxing.plugin.Minibox$MiniboxInjectPhase$$anon$4.transform(Minibox.scala:487)
    at miniboxing.plugin.Minibox$MiniboxInjectPhase$$anon$4.transform(Minibox.scala:484)
    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:147)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:427)
    at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:418)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:427)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:385)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:385)
    at scala.collection.Iterator$class.foreach(Iterator.scala:743)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1195)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:385)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1336)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1323)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1318)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1416)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:32)
    at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
    at scala.tools.nsc.Driver.process(Driver.scala:51)
    at scala.tools.nsc.Driver.main(Driver.scala:64)
    at scala.tools.nsc.Main.main(Main.scala)
```

**Comment by tixxit** [comment]
:D Thanks!
