### ISSUE TITLE
REPL invalid class created (only on 2.11)

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#170]
Following the tests in https://github.com/miniboxing/miniboxing-plugin/commit/017c6c85da57139825326ea1545c2d37b9d2b33c I found the following corner case, which needs a series of elements in order to occur:
- version 2.11 of the compiler
- REPL started manually, not via [ReplTest](https://github.com/miniboxing/miniboxing-plugin/blob/wip/tests/correctness/test/miniboxing/infrastructure/ReplTest.scala) [(see this test, which passes)](https://github.com/miniboxing/miniboxing-plugin/blob/wip/tests/correctness/resources/miniboxing/tests/compile/gh-bug-67-2.repl)
- rows need to be separate:

``` scala
scala> trait T[@miniboxed X]; class C extends T[Int]
```

does not exhibit the bug while

``` scala
scala> trait T[@miniboxed X]
scala> class C extends T[Int]
```

does:

``` scala
$ mb-scala
Welcome to Scala version 2.11.5-20141107-114204-b1e6f57b2b (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_72).
Type in expressions to have them evaluated.
Type :help for more information.

scala> trait T[@miniboxed X]; class C extends T[Int]
defined trait T
defined class C

scala> new C
res0: C = C@fbaa45c

scala> trait T[@miniboxed X]
defined trait T

scala> class C extends T[Int]
defined class C

scala> new C
java.lang.ClassFormatError: Illegal class modifiers in class C: 0x209
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
  at scala.reflect.internal.util.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:64)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
  at java.lang.Class.getDeclaredMethods0(Native Method)
  at java.lang.Class.privateGetDeclaredMethods(Class.java:2615)
  at java.lang.Class.privateGetPublicMethods(Class.java:2733)
  at java.lang.Class.getMethods(Class.java:1472)
  at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.evalMethod(IMain.scala:816)
  at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:750)
  at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1002)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:609)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:608)
  at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
  at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:608)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:540)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:536)
  at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:750)
  at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:795)
  at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:662)
  at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:407)
  at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:430)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:864)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:850)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:850)
  at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
  at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:850)
  at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:74)
  at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
  at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
  at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
  at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

CC #67.

**Comment by VladUreche** [comment]
The Java flags `0x209` correspond to `ACC_PUBLIC | ACC_PRIVATE | ACC_PROTECTED | ACC_INTERFACE`. Aside from `ACC_PUBLIC`, none of the flags should appear there:

``` scala

  /** (see http://java.sun.com/docs/books/jvms/second_edition/jvms-clarify.html)
   *
   *  If the `ACC_INTERFACE` flag is set, the `ACC_ABSTRACT` flag must also
   *  be set (ch. 2.13.1).
   *
   *  A class file cannot have both its `ACC_FINAL` and `ACC_ABSTRACT` flags
   *  set (ch. 2.8.2).
   *
   *  A field may have at most one of its `ACC_PRIVATE`, `ACC_PROTECTED`,
   *  `ACC_PUBLIC` flags set (ch. 2.7.4).
   *
   *  A field may not have both its `ACC_FINAL` and `ACC_VOLATILE` flags set
   *  (ch. 2.9.1).
   *
   *  If a method has its `ACC_ABSTRACT` flag set it must not have any of its
   *  `ACC_FINAL`, `ACC_NATIVE`, `ACC_PRIVATE`, `ACC_STATIC`, `ACC_STRICT`,
   *  or `ACC_SYNCHRONIZED` flags set (ch. 2.13.3.2).
   *
   *  All interface methods must have their `ACC_ABSTRACT` and
   *  `ACC_PUBLIC` flags set.
   *
   *  Note for future reference: see this thread on ACC_SUPER and
   *  how its enforcement differs on the android vm.
   *    https://groups.google.com/forum/?hl=en#!topic/jvm-languages/jVhzvq8-ZIk
   *
   */                                        // Class   Field   Method
  final val JAVA_ACC_PUBLIC       = 0x0001   //   X       X        X
  final val JAVA_ACC_PRIVATE      = 0x0002   //           X        X
  final val JAVA_ACC_PROTECTED    = 0x0004   //           X        X
  final val JAVA_ACC_STATIC       = 0x0008   //           X        X
  final val JAVA_ACC_FINAL        = 0x0010   //   X       X        X
  final val JAVA_ACC_SUPER        = 0x0020   //   X
  final val JAVA_ACC_SYNCHRONIZED = 0x0020   //                    X
  final val JAVA_ACC_VOLATILE     = 0x0040   //           X
  final val JAVA_ACC_BRIDGE       = 0x0040   //                    X
  final val JAVA_ACC_TRANSIENT    = 0x0080   //           X
  final val JAVA_ACC_VARARGS      = 0x0080   //                    X
  final val JAVA_ACC_NATIVE       = 0x0100   //                    X
  final val JAVA_ACC_INTERFACE    = 0x0200   //   X
  final val JAVA_ACC_ABSTRACT     = 0x0400   //   X                X
  final val JAVA_ACC_STRICT       = 0x0800   //                    X
  final val JAVA_ACC_SYNTHETIC    = 0x1000   //   X       X        X
  final val JAVA_ACC_ANNOTATION   = 0x2000   //   X
  final val JAVA_ACC_ENUM         = 0x4000   //   X       X
```

(taken from https://github.com/scala/scala/blob/2.11.x/src/reflect/scala/reflect/internal/ClassfileConstants.scala)
