### ISSUE TITLE
REPL crasher after #170 fix

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#175]
Looks like fallout from the fix to #170:

``` scala
$ mb-scala
Welcome to Scala version 2.11.5-20141107-114204-b1e6f57b2b (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_76).
Type in expressions to have them evaluated.
Type :help for more information.

scala> class C[@miniboxed T]
defined class C

scala> new C[Int]
scala.reflect.internal.Types$TypeError: trait C_J is abstract; cannot be instantiated
    at scala.tools.nsc.typechecker.Contexts$ThrowingReporter.handleError(Contexts.scala:1389)
    at scala.tools.nsc.typechecker.Contexts$ContextReporter.issue(Contexts.scala:1241)
    at scala.tools.nsc.typechecker.Contexts$Context.issue(Contexts.scala:572)
    at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueTypeError(ContextErrors.scala:98)
    at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueNormalTypeError(ContextErrors.scala:91)
    at scala.tools.nsc.typechecker.ContextErrors$TyperContextErrors$TyperErrorGen$.IsAbstractError(ContextErrors.scala:385)
    at scala.tools.nsc.typechecker.Typers$Typer.typedNew$1(Typers.scala:4291)
    at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5224)
    at scala.tools.nsc.typechecker.Typers$Typer.typedInAnyMode$1(Typers.scala:5254)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5261)
    at scala.tools.nsc.typechecker.Typers$Typer.runTyper$1(Typers.scala:5297)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedInternal(Typers.scala:5324)
    at scala.tools.nsc.typechecker.Typers$Typer.body$2(Typers.scala:5271)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5275)
    at scala.tools.nsc.interpreter.ReplGlobal$$anon$1$$anon$2.typed(ReplGlobal.scala:36)
    at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5373)
    at scala.tools.nsc.typechecker.Typers$Typer.typedQualifier(Typers.scala:5381)
    at miniboxing.plugin.transform.minibox.inject.MiniboxInjectTreeTransformation$MiniboxTreeTransformer.rewrite(MiniboxDuplTreeTransformation.scala:515)
    at miniboxing.plugin.transform.infrastructure.TreeRewriters$TreeRewriter.transform(TreeRewriter.scala:35)
    at miniboxing.plugin.transform.minibox.inject.MiniboxInjectTreeTransformation$MiniboxTreeTransformer.rewrite(MiniboxDuplTreeTransformation.scala:546)
    at miniboxing.plugin.transform.infrastructure.TreeRewriters$TreeRewriter.transform(TreeRewriter.scala:35)
    at miniboxing.plugin.transform.minibox.inject.MiniboxInjectTreeTransformation$MiniboxTreeTransformer.rewrite(MiniboxDuplTreeTransformation.scala:617)
    at miniboxing.plugin.transform.infrastructure.TreeRewriters$TreeRewriter.transform(TreeRewriter.scala:35)
    at miniboxing.plugin.transform.infrastructure.TreeRewriters$TreeRewriter.transform(TreeRewriter.scala:26)
    at scala.reflect.internal.Trees$$anonfun$itransform$1.apply(Trees.scala:1357)
    at scala.reflect.internal.Trees$$anonfun$itransform$1.apply(Trees.scala:1356)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:17)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1355)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
    at miniboxing.plugin.transform.infrastructure.TreeRewriters$TreeRewriter.miniboxing$plugin$transform$infrastructure$TreeRewriters$TreeRewriter$$super$transform(TreeRewriter.scala:46)
    at miniboxing.plugin.transform.infrastructure.TreeRewriters$TreeRewriter$$anonfun$transformStats$1.apply(TreeRewriter.scala:46)
    at miniboxing.plugin.transform.infrastructure.TreeRewriters$TreeRewriter$$anonfun$transformStats$1.apply(TreeRewriter.scala:43)
...
```

and doesn't affect 2.10:

``` scala
$ mb-scala -2.10
Welcome to Scala version 2.10.5-20140407-165700-ec05aeb3d6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_76).
Type in expressions to have them evaluated.
Type :help for more information.

scala> class C[@miniboxed T]
defined class C

scala> new C[Int]
res0: C[Int] = C_J@4dd5d6bb
```

**Comment by VladUreche** [comment]
Btw, found while testing the last point in #137: "Avoid using specialization and implicit classes"
