### ISSUE TITLE
Brique `lookup` test failing

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#189]
```
> test
...
[info] ConsListSpec:
[info] - apply
[info] - toList
[info] - foldLeft with cons reverse the list
[info] - foldMap
[info] - foldMap order
[info] - flatMap
[info] - cons - uncons
[info] - ++
[info] - append
[info] - filter
[info] - lookup *** FAILED ***
[info]   java.lang.ClassCastException: scala.None$ cannot be cast to java.lang.Integer
[info]   at miniboxing.runtime.MiniboxConversionsLong.box2minibox_deep(MiniboxConversionsLong.java:72)
[info]   at miniboxing.runtime.MiniboxConversionsLong.box2minibox_tt(MiniboxConversionsLong.java:56)
[info]   at brique.ConsList$Cons_L.head_J(ConsList.scala)
[info]   at brique.ConsList_J.map(ConsList.scala:155)
[info]   at brique.tests.ConsListSpec$$anonfun$11.apply_J(ConsListSpec.scala:90)
[info]   at miniboxing.runtime.AbstractMiniboxedFunction0_J$$anon$2.apply(MiniboxedFunction.scala:74)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
[info] - take
[info] - takeWhile
[info] - drop
[info] - dropWhile
[info] - widen
```

**Comment by VladUreche** [comment]
As of https://github.com/VladUreche/brique/commit/a13de7b05a53197d97e81311aab5cb232d27bb73

**Comment by VladUreche** [comment]
Fixed by https://github.com/VladUreche/brique/commit/1f7389c7fd40831c2d678329d18d4782eb1e70d0 -- it wasn't the miniboxing plugin, but the way I translated the extractor calls.
