### ISSUE TITLE
Crash in uncurry with tpe == null

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#2]
File:

```
package benchmarks
import miniboxing.plugin.minispec

class C[@minispec T](tail: C[T]) {
  // WORKS:
  //def length: Int = tail.length
  // CRASHES:
  def length: Int = if (tail!=null) tail.length else 0
}
```

Output:

```
$ build/quick/bin/scalac -Xplugin:/home/sun/workspace/dev/miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar -cp /home/sun/workspace/dev/miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar:/home/sun/workspace/dev/miniboxing-plugin/components/runtime/target/scala-2.10/miniboxing-runime_2.10-0.1-SNAPSHOT.jar ../miniboxing-plugin/test/benchmarks/C.scala -d mboxing -Xprint:minibox -Xprint:specialize
Specializing class C...
-------------- WIDENDED CLAZZ ----------------
C [T]Object {
  private[this] val tail: benchmarks.C[T]
  def <init>(tail: benchmarks.C[T],val T_TypeTag: Byte): benchmarks.C[T]
  def length: Int
  private[this] val T_TypeTag: Byte
  def length_J: Int
}
-------------- INTERFACE ----------------
C_interface [Tsp]AnyRef {
  def length: Int
  def length_J: Int
}
-------------- ORIGINAL CLASS ----------------
C [T]Object
        with benchmarks.C_interface[T] {
  private[this] val tail: benchmarks.C[T]
  def <init>(tail: benchmarks.C[T],val T_TypeTag: Byte): benchmarks.C[T]
  def length: Int
  private[this] val T_TypeTag: Byte
  def length_J: Int
}
------------ SPEC CLASS ------------
C_J [Tsp]Object
        with benchmarks.C_interface[Tsp] {
  private[this] val T_TypeTag: Byte
  private[this] val tail: benchmarks.C_interface[Long]
  def <init>(tail: benchmarks.C_interface[Long],val T_TypeTag: Byte): benchmarks.C_J[Tsp]
  def length_J: Int
  def length: Int
}
------------ SPEC CLASS ------------
C_L [Tsp]Object
        with benchmarks.C_interface[Tsp] {
  private[this] val T_TypeTag: Byte
  private[this] val tail: benchmarks.C_interface[Tsp]
  def <init>(tail: benchmarks.C_interface[Tsp],val T_TypeTag: Byte): benchmarks.C_L[Tsp]
  def length_J: Int
  def length: Int
}
-------------- TEMPLATE MEMBERS ----------------
benchmarks.C.<init>
benchmarks.C.length
benchmarks.C.tail
collected benchmarks.C.tail
collected benchmarks.C.<init>
collected benchmarks.C.length
method length_J ===> ForwardTo(benchmarks.C.length)
method length ===> Interface()
method length_J ===> Interface()
benchmarks.C_L.tail
constructor C_L ===> SpecializedImplementationOf2(benchmarks.C.<init>)
benchmarks.C_L.<init>
method length_J ===> ForwardTo(benchmarks.C_L.length)
method length ===> SpecializedImplementationOf2(benchmarks.C.length)
benchmarks.C_L.length
benchmarks.C_J.tail
constructor C_J ===> SpecializedImplementationOf2(benchmarks.C.<init>)
benchmarks.C_J.<init>
method length_J ===> SpecializedImplementationOf2(benchmarks.C.length)
benchmarks.C_J.length_J
method length ===> ForwardTo(benchmarks.C_J.length_J)
[[syntax trees at end of                   minibox]] // C.scala
package benchmarks {
  class C[@miniboxing.plugin.minispec T >: Nothing <: Any] extends scala.AnyRef {
    <paramaccessor> private[this] val tail: benchmarks.C[T] = _;
    def <init>(tail: benchmarks.C[T], T_TypeTag: Byte): benchmarks.C[T] = {
      C.super.<init>();
      ()
    };
    def length: Int = if (C.this.tail.!=(null))
      C.this.tail.length
    else
      0;
    <synthetic> <paramaccessor> <synchronized> private[this] val T_TypeTag: Byte = _;
    <synchronized> def length_J: Int = C.this.length
  };
  abstract trait C_interface[Tsp >: Nothing <: Any] extends Object {
    <synchronized> def length: Int;
    <synchronized> def length_J: Int
  };
  class C_L[Tsp >: Nothing <: Any] extends Object with benchmarks.C_interface[Tsp] {
    <synthetic> <paramaccessor> <synchronized> private[this] val T_TypeTag: Byte = _;
    <paramaccessor> <synchronized> private[this] val tail: benchmarks.C_interface[Tsp] = _;
    <synchronized> def <init>(tail: benchmarks.C_interface[Tsp], T_TypeTag: Byte): benchmarks.C_L[Tsp] = {
      C_L.super.<init>();
      ()
    };
    <synchronized> def length_J: Int = C_L.this.length;
    <synchronized> def length(): Int = if (C_L.this.tail.!=(null))
      C_L.this.tail.length
    else
      0
  };
  class C_J[Tsp >: Nothing <: Any] extends Object with benchmarks.C_interface[Tsp] {
    <synthetic> <paramaccessor> <synchronized> private[this] val T_TypeTag: Byte = _;
    <paramaccessor> <synchronized> private[this] val tail: benchmarks.C_interface[Long] = _;
    <synchronized> def <init>(tail: benchmarks.C_interface[Long], T_TypeTag: Byte): benchmarks.C_J[Tsp] = {
      C_J.super.<init>();
      ()
    };
    <synchronized> def length_J(): Int = if (C_J.this.tail.!=(null))
      C_J.this.tail.length_J
    else
      0;
    <synchronized> def length: Int = C_J.this.length_J
  }
}

error: 
     while compiling: ../miniboxing-plugin/test/benchmarks/C.scala
        during phase: uncurry
     library version: version 2.10.0-20121014-154054-f3550d25e0
    compiler version: version 2.10.0-20121014-154054-f3550d25e0
  reconstructed args: -Xprint:minibox -Xprint:specialize -d mboxing -classpath /home/sun/workspace/dev/miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar:/home/sun/workspace/dev/miniboxing-plugin/components/runtime/target/scala-2.10/miniboxing-runime_2.10-0.1-SNAPSHOT.jar -Xplugin:/home/sun/workspace/dev/miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar

  last tree to typer: term benchmarks
              symbol: package benchmarks (flags: final <module> <package> <java> <triedcooking>)
   symbol definition: final package benchmarks
                 tpe: <notype>
       symbol owners: package benchmarks -> package <root>
      context owners: method length -> class C_L -> package benchmarks

== Enclosing template or block ==

DefDef( // def length: Int in class C_L
  <method> <triedcooking> <synchronized>
  "length"
  []
  List(Nil)
  <tpt> // tree.tpe=Int
  If( // tree.tpe=Int
    Apply( // final def !=(x$1: AnyRef): Boolean in class Object, tree.tpe=Boolean
      C_L.this."tail"."$bang$eq" // final def !=(x$1: AnyRef): Boolean in class Object, tree.tpe=(x$1: Object)Boolean
      null
    )
    C_L.this."tail"."length" // def length: Int in trait C_interface
    0
  )
)

== Expanded type of tree ==

<notype>

uncaught exception during compilation: java.lang.AssertionError
error: java.lang.AssertionError: assertion failed: 
     while compiling: ../miniboxing-plugin/test/benchmarks/C.scala
        during phase: uncurry
     library version: version 2.10.0-20121014-154054-f3550d25e0
    compiler version: version 2.10.0-20121014-154054-f3550d25e0
  reconstructed args: -Xprint:minibox -Xprint:specialize -d mboxing -classpath /home/sun/workspace/dev/miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar:/home/sun/workspace/dev/miniboxing-plugin/components/runtime/target/scala-2.10/miniboxing-runime_2.10-0.1-SNAPSHOT.jar -Xplugin:/home/sun/workspace/dev/miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar

  last tree to typer: term benchmarks
              symbol: package benchmarks (flags: final <module> <package> <java> <triedcooking>)
   symbol definition: final package benchmarks
                 tpe: <notype>
       symbol owners: package benchmarks -> package <root>
      context owners: method length -> class C_L -> package benchmarks

== Enclosing template or block ==

DefDef( // def length: Int in class C_L
  <method> <triedcooking> <synchronized>
  "length"
  []
  List(Nil)
  <tpt> // tree.tpe=Int
  If( // tree.tpe=Int
    Apply( // final def !=(x$1: AnyRef): Boolean in class Object, tree.tpe=Boolean
      C_L.this."tail"."$bang$eq" // final def !=(x$1: AnyRef): Boolean in class Object, tree.tpe=(x$1: Object)Boolean
      null
    )
    C_L.this."tail"."length" // def length: Int in trait C_interface
    0
  )
)

== Expanded type of tree ==

<notype>

C_L.this.tail.length tpe is null
    at scala.Predef$.assert(Predef.scala:179)
    at scala.tools.nsc.Global.assert(Global.scala:238)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:669)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:122)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:82)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1198)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2816)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:658)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:122)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:82)
    at scala.reflect.internal.Trees$$anonfun$itransform$2.apply(Trees.scala:1193)
    at scala.reflect.internal.Trees$$anonfun$itransform$2.apply(Trees.scala:1191)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2855)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1190)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2816)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.scala$tools$nsc$transform$UnCurry$UnCurryTransformer$$super$transform(UnCurry.scala:598)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer$$anonfun$12.apply(UnCurry.scala:598)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer$$anonfun$12.apply(UnCurry.scala:581)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.withNeedLift$1(UnCurry.scala:534)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:580)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:122)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:82)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2846)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2844)
    at scala.collection.immutable.List.loop$1(List.scala:164)
    at scala.collection.immutable.List.mapConserve(List.scala:180)
    at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2844)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1234)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2816)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.scala$tools$nsc$transform$TypingTransformers$TypingTransformer$$super$transform(TypingTransformers.scala:44)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$1.apply(TypingTransformers.scala:44)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$1.apply(TypingTransformers.scala:44)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2855)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.scala$tools$nsc$transform$UnCurry$UnCurryTransformer$$super$transform(UnCurry.scala:598)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer$$anonfun$23.apply(UnCurry.scala:655)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer$$anonfun$23.apply(UnCurry.scala:655)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.scala$tools$nsc$transform$UnCurry$UnCurryTransformer$$withInConstructorFlag$1(UnCurry.scala:561)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:655)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:122)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:82)
    at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2823)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1238)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1237)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2855)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1236)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2816)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:658)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:122)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:82)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2846)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2844)
    at scala.collection.immutable.List.loop$1(List.scala:164)
    at scala.collection.immutable.List.mapConserve(List.scala:180)
    at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2844)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1256)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1256)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2855)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1255)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2816)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.scala$tools$nsc$transform$TypingTransformers$TypingTransformer$$super$transform(TypingTransformers.scala:44)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$2.apply(TypingTransformers.scala:46)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$2.apply(TypingTransformers.scala:46)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2855)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:46)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.mainTransform(UnCurry.scala:658)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:122)
    at scala.tools.nsc.transform.UnCurry$UnCurryTransformer.transform(UnCurry.scala:82)
    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:227)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:461)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:428)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:428)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1156)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:428)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1574)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1548)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1544)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1654)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:33)
    at scala.tools.nsc.Main$.doCompile(Main.scala:79)
    at scala.tools.nsc.Driver.process(Driver.scala:54)
    at scala.tools.nsc.Driver.main(Driver.scala:67)
    at scala.tools.nsc.Main.main(Main.scala)

Exception in thread "main" java.lang.AssertionError: assertion failed: 
     while compiling: ../miniboxing-plugin/test/benchmarks/C.scala
        during phase: uncurry
     library version: version 2.10.0-20121014-154054-f3550d25e0
    compiler version: version 2.10.0-20121014-154054-f3550d25e0
  reconstructed args: -Xprint:minibox -Xprint:specialize -d mboxing -classpath /home/sun/workspace/dev/miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar:/home/sun/workspace/dev/miniboxing-plugin/components/runtime/target/scala-2.10/miniboxing-runime_2.10-0.1-SNAPSHOT.jar -Xplugin:/home/sun/workspace/dev/miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar

  last tree to typer: term benchmarks
              symbol: package benchmarks (flags: final <module> <package> <java> <triedcooking>)
   symbol definition: final package benchmarks
                 tpe: <notype>
       symbol owners: package benchmarks -> package <root>
      context owners: method length -> class C_L -> package benchmarks

== Enclosing template or block ==

DefDef( // def length: Int in class C_L
  <method> <triedcooking> <synchronized>
  "length"
  []
  List(Nil)
  <tpt> // tree.tpe=Int
  If( // tree.tpe=Int
    Apply( // final def !=(x$1: AnyRef): Boolean in class Object, tree.tpe=Boolean
      C_L.this."tail"."$bang$eq" // final def !=(x$1: AnyRef): Boolean in class Object, tree.tpe=(x$1: Object)Boolean
      null
    )
    C_L.this."tail"."length" // def length: Int in trait C_interface
    0
  )
)

== Expanded type of tree ==

<notype>

C_L.this.tail.length tpe is null
  <stack trace again>
```

**Comment by VladUreche** [comment]
Reopened with this commit.
