### ISSUE TITLE
Crash in Tuple rewiring

### ISSUE THREAD

**Issue by Roldak** [miniboxing/miniboxing-plugin#209]
```
$ cat gh-bug-209.scala 
package mbhashmap

class MbHashmap {       
  def builder[@miniboxed U, @miniboxed V](x: (U, V)) = {
    val u = x._2
    val v = x._1
    val tup = (u, v)
    tup
  }
}

$ mb-scalac gh-bug-209.scala 
error: java.util.NoSuchElementException: key not found: type U
    at scala.collection.MapLike$class.default(MapLike.scala:228)
    at scala.collection.AbstractMap.default(Map.scala:59)
    at scala.collection.MapLike$class.apply(MapLike.scala:141)
    at scala.collection.AbstractMap.apply(Map.scala:59)
    at miniboxing.plugin.transform.minibox.commit.MiniboxCommitTreeTransformer$MiniboxTreeTransformer.transform(MiniboxCommitTreeTransformer.scala:307)
    at miniboxing.plugin.transform.minibox.commit.MiniboxCommitTreeTransformer$MiniboxTreeTransformer.transform(MiniboxCommitTreeTransformer.scala:111)
    at scala.reflect.internal.Trees$$anonfun$itransform$1.apply(Trees.scala:1357)
    at scala.reflect.internal.Trees$$anonfun$itransform$1.apply(Trees.scala:1356)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2600)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:30)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:25)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:17)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1355)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:16)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:44)
    at miniboxing.plugin.transform.minibox.commit.MiniboxCommitTreeTransformer$MiniboxTreeTransformer.transform(MiniboxCommitTreeTransformer.scala:382)
...
```

**Comment by VladUreche** [comment]
Ping @milosstojanovic: I'll be reducing the bug now, hopefully it shouldn't be too difficult.

**Comment by VladUreche** [comment]
Updated the description with a minimized test case.
