### ISSUE TITLE
`mb-tweak-erasure` is too eager at removing bridge methods

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#228]
```
$ cat gh-bug-228.scala 

trait Foo {
  def foo(f: => Int): Foo
  override def toString() = "foo"
}

class Bar extends Foo {
  def foo(f: => Int): Bar = this
  override def toString() = "bar"
}

object Test {
  def main(args: Array[String]): Unit = {
    val foo: Foo = new Bar()
    println(foo.foo(3))
  }
}

$ mb-scalac gh-bug-228.scala

$ mb-scala Test
java.lang.AbstractMethodError: Bar.foo(Lminiboxing/runtime/MiniboxedFunction0;)LFoo;
    at Test$.main(gh-bug-228.scala:16)
    at Test.main(gh-bug-228.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
    at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
    at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
    at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
    at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
    at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
    at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
    at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
    at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
    at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
    at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
    at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
    at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by VladUreche** [comment]
Quick workaround:

```
class Bar extends Foo {
  def foo(f: => Int): Foo = // replace Bar by Foo
    ...
}
```
