### ISSUE TITLE
Tailcalls error - due to labeldef nesting and unboxing

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#24]
```
sun@sun-laptop:/mnt/data-local/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ cat mb_spire_8.scala
package miniboxing.tests.compile
import miniboxing.plugin.minispec
import scala.annotation.tailrec

class TailCallsCrasher3[@minispec A] {
  @tailrec final def euclid2(a: A, b: A): A = a match {
    case _ => euclid2(a, b)
  }
}
sun@sun-laptop:/mnt/data-local/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ ../mb-scalac mb_spire_8.scala 
error: 
     while compiling: mb_spire_8.scala
        during phase: minibox
     library version: version 2.10.3-20130625-164027-d22e8d282c
    compiler version: version 2.10.3-20130627-153946-54cb6af7db
  reconstructed args: -bootclasspath /home/sun/workspace/dev/miniboxing-plugin//components/runtime/target/scala-2.10/miniboxing-runtime_2.10-0.1-SNAPSHOT.jar:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar -Xplugin:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar

  last tree to typer: term euclid2_J
              symbol: method euclid2_J in class TailCallsCrasher3_J (flags: <method> final <triedcooking>)
   symbol definition: final def euclid2_J(val TailCallsCrasher3_A_TypeTag: Byte,a: Long,b: Long): Long
       symbol owners: method euclid2_J -> class TailCallsCrasher3_J -> package compile
      context owners: method euclid2_J -> class TailCallsCrasher3_J -> package compile

== Enclosing template or block ==

Apply( // final def minibox2box[T](l: Long,tag: Byte): T in object MiniboxConversions, tree.tpe=Asp
  TypeApply( // final def minibox2box[T](l: Long,tag: Byte): T in object MiniboxConversions, tree.tpe=(l: Long, tag: Byte)Asp
    MiniboxConversions.this."minibox2box" // final def minibox2box[T](l: Long,tag: Byte): T in object MiniboxConversions, tree.tpe=[T](l: Long, tag: Byte)T
    <tpt> // tree.tpe=Asp
  )
  // 2 arguments
  "b" // b: Long, tree.tpe=Long
  "TailCallsCrasher3_A_TypeTag" // val TailCallsCrasher3_A_TypeTag: Byte, tree.tpe=Byte
)

uncaught exception during compilation: scala.reflect.internal.Types$TypeError
error: scala.reflect.internal.Types$TypeError: type mismatch;
 found   : A
 required: Asp
    at scala.tools.nsc.typechecker.Contexts$Context.issueCommon(Contexts.scala:397)
    at scala.tools.nsc.typechecker.Contexts$Context.issue(Contexts.scala:401)
    at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueTypeError(ContextErrors.scala:103)
    at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueNormalTypeError(ContextErrors.scala:87)
    at scala.tools.nsc.typechecker.ContextErrors$TyperContextErrors$TyperErrorGen$.AdaptTypeError(ContextErrors.scala:195)
    at scala.tools.nsc.typechecker.Typers$Typer.fallBack$1(Typers.scala:1277)
    at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1282)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5621)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:389)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5682)
    at scala.tools.nsc.typechecker.Typers$Typer.typedLabelDef(Typers.scala:2340)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5547)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5603)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:284)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2925)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$60.apply(Typers.scala:3029)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$60.apply(Typers.scala:3029)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3029)
    at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2429)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5531)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5531)
    at scala.tools.nsc.typechecker.Typers$Typer.typerWithLocalContext(Typers.scala:507)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5531)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5603)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:239)
    at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:5806)
    at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:2254)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5530)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5603)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:251)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5665)
    at miniboxing.plugin.Duplicators.retyped(Duplicators.scala:42)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$46.apply(MiniboxTreeTransformation.scala:727)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$46.apply(MiniboxTreeTransformation.scala:727)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
    at scala.reflect.internal.SymbolTable.beforePhase(SymbolTable.scala:215)
    at miniboxing.plugin.MiniboxPhase$class.beforeMinibox(Minibox.scala:110)
    at miniboxing.plugin.Minibox$Component$.beforeMinibox(Minibox.scala:68)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.duplicateBody(MiniboxTreeTransformation.scala:727)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.specializeDefDefBody(MiniboxTreeTransformation.scala:693)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxTreeTransformation.scala:224)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:125)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:70)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2900)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$9.apply(MiniboxTreeTransformation.scala:174)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$9.apply(MiniboxTreeTransformation.scala:174)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxTreeTransformation.scala:174)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:125)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:70)
    at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2904)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1280)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1279)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1278)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxTreeTransformation.scala:458)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:125)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:70)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2927)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2925)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2925)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$miniboxTransform$2.apply(MiniboxTreeTransformation.scala:144)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$miniboxTransform$2.apply(MiniboxTreeTransformation.scala:141)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxTreeTransformation.scala:141)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:125)
    at miniboxing.plugin.Minibox$Component$$anon$1$$anonfun$1.apply(Minibox.scala:94)
    at miniboxing.plugin.Minibox$Component$$anon$1$$anonfun$1.apply(Minibox.scala:94)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
    at scala.reflect.internal.SymbolTable.afterPhase(SymbolTable.scala:216)
    at miniboxing.plugin.MiniboxPhase$class.afterMinibox(Minibox.scala:107)
    at miniboxing.plugin.Minibox$Component$$anon$1.transform(Minibox.scala:94)
    at miniboxing.plugin.Minibox$Component$$anon$1.transform(Minibox.scala:87)
    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:227)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:431)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:33)
    at scala.tools.nsc.Main$.doCompile(Main.scala:79)
    at scala.tools.nsc.Driver.process(Driver.scala:54)
    at scala.tools.nsc.Driver.main(Driver.scala:67)
    at scala.tools.nsc.Main.main(Main.scala)

Exception in thread "main" scala.reflect.internal.Types$TypeError: type mismatch;
 found   : A
 required: Asp
    at scala.tools.nsc.typechecker.Contexts$Context.issueCommon(Contexts.scala:397)
    at scala.tools.nsc.typechecker.Contexts$Context.issue(Contexts.scala:401)
    at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueTypeError(ContextErrors.scala:103)
    at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueNormalTypeError(ContextErrors.scala:87)
    at scala.tools.nsc.typechecker.ContextErrors$TyperContextErrors$TyperErrorGen$.AdaptTypeError(ContextErrors.scala:195)
    at scala.tools.nsc.typechecker.Typers$Typer.fallBack$1(Typers.scala:1277)
    at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1282)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5621)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:389)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5682)
    at scala.tools.nsc.typechecker.Typers$Typer.typedLabelDef(Typers.scala:2340)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5547)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5603)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:284)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2925)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$60.apply(Typers.scala:3029)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$60.apply(Typers.scala:3029)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3029)
    at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2429)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5531)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5531)
    at scala.tools.nsc.typechecker.Typers$Typer.typerWithLocalContext(Typers.scala:507)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5531)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5603)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:239)
    at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:5806)
    at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:2254)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5530)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5603)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:251)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5665)
    at miniboxing.plugin.Duplicators.retyped(Duplicators.scala:42)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$46.apply(MiniboxTreeTransformation.scala:727)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$46.apply(MiniboxTreeTransformation.scala:727)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
    at scala.reflect.internal.SymbolTable.beforePhase(SymbolTable.scala:215)
    at miniboxing.plugin.MiniboxPhase$class.beforeMinibox(Minibox.scala:110)
    at miniboxing.plugin.Minibox$Component$.beforeMinibox(Minibox.scala:68)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.duplicateBody(MiniboxTreeTransformation.scala:727)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.specializeDefDefBody(MiniboxTreeTransformation.scala:693)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxTreeTransformation.scala:224)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:125)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:70)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2900)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$9.apply(MiniboxTreeTransformation.scala:174)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$9.apply(MiniboxTreeTransformation.scala:174)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxTreeTransformation.scala:174)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:125)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:70)
    at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2904)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1280)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1279)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1278)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxTreeTransformation.scala:458)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:125)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:70)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2927)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2925)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2925)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$miniboxTransform$2.apply(MiniboxTreeTransformation.scala:144)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$miniboxTransform$2.apply(MiniboxTreeTransformation.scala:141)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxTreeTransformation.scala:141)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:125)
    at miniboxing.plugin.Minibox$Component$$anon$1$$anonfun$1.apply(Minibox.scala:94)
    at miniboxing.plugin.Minibox$Component$$anon$1$$anonfun$1.apply(Minibox.scala:94)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
    at scala.reflect.internal.SymbolTable.afterPhase(SymbolTable.scala:216)
    at miniboxing.plugin.MiniboxPhase$class.afterMinibox(Minibox.scala:107)
    at miniboxing.plugin.Minibox$Component$$anon$1.transform(Minibox.scala:94)
    at miniboxing.plugin.Minibox$Component$$anon$1.transform(Minibox.scala:87)
    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:227)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:431)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:33)
    at scala.tools.nsc.Main$.doCompile(Main.scala:79)
    at scala.tools.nsc.Driver.process(Driver.scala:54)
    at scala.tools.nsc.Driver.main(Driver.scala:67)
    at scala.tools.nsc.Main.main(Main.scala)
```

**Comment by VladUreche** [comment]
There's no second bug for this, so I need to fix it completely... :(((
