### ISSUE TITLE
AbstractMethodError due to bridge removal (again)

### ISSUE THREAD

**Issue by ghost** [miniboxing/miniboxing-plugin#248]
The error has been generated by the following source(algorithms may not be correct): http://pastebin.com/uUBtZN4F
It occurs with the miniboxing plugin's presence when a newly defined collection type(a linked list) implements a hierarchy of typeclasses and gets a new method with an implicit and a typed requirement through an implicit class. Changing the collection type, adding/removing the miniboxed annotation doesn't solve the problem. The only solution so far is to override it when creating the evidence.

The build.sbt:

import sbt.Keys._

name := "eve"

version := "0.0.1"

scalaVersion := "2.11.7"

//when uncommented: AbstractMethodError
/*
resolvers += Resolver.sonatypeRepo("snapshots")

libraryDependencies += "org.scala-miniboxing.plugins" %% "miniboxing-runtime" % "0.4-SNAPSHOT"

addCompilerPlugin("org.scala-miniboxing.plugins" %% "miniboxing-plugin" % "0.4-SNAPSHOT")
*/

scalacOptions ++= Seq(
  "-deprecation",
  "-unchecked",
  "-feature",
  "-optimize"
)

**Comment by VladUreche** [comment]
Steven, thanks for the bug report! Looking into it now.

**Comment by VladUreche** [comment]
Steven, I finally found the problem. Here it is minimized further:

```
$ cat gh-bug-248-mini.scala 

trait Foo {
  def foo(f: => Int): Foo
  def bar(f: => Int): Foo
  override def toString() = "foo"
}

class Bar extends Foo {
  def foo(f: => Int): Bar = this
  def bar(f: => Int): Bar = this
  override def toString() = "bar"
}

object Test {
  def main(args: Array[String]): Unit = {
    val foo: Foo = new Bar()
    println(foo.foo(3))
    println(foo.bar(3))
  }
}

$ mb-scalac gh-bug-248-mini.scala 

$ mb-scala Test
java.lang.AbstractMethodError: Bar.foo(Lminiboxing/internal/MiniboxedFunction0;)LFoo;
    at Test$.main(gh-bug-248-mini.scala:17)
    at Test.main(gh-bug-248-mini.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
    at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
    at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
    at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
    at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
    at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
    at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
    at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
    at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
    at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:65)
    at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:87)
    at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
    at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

It's related to #228, which I fixed incorrectly :((

**Comment by VladUreche** [comment]
@stevendobay I tried running the eve test suite but I'm still seeing an AbstractMethodError. I'll reopen and diagnose this tomorrow.

**Comment by VladUreche** [comment]
Seems fixed with the last commit. On the eve repository, I get the following error:

```
[info] - when calling flatMap(x => List(x - 1, x + 1)) on List(1, 3, 2, 5) - it should be List(0, 2, 2, 4, 1, 3, 4, 6) *** FAILED ***
[info]   Cons(4,Cons(6,Cons(1,Cons(3,Cons(2,Cons(4,Cons(0,Cons(2,Nil())))))))) did not equal Cons(0,Cons(2,Cons(2,Cons(4,Cons(1,Cons(3,Cons(4,Cons(6,Nil())))))))) (ListSuite.scala:217)
```

(both with the miniboxing plugin and without)

I assume there's a problem with the fold order, but I'm too tired to debug now...

I'll mark the bug as closed, feel free to reopen (or file a new bug) if you spot any other issues.

**Comment by ghost** [comment]
The algorithm was incorrect(I was lazy) but thanks for the fix!

**Comment by VladUreche** [comment]
Great to hear that @stevendobay! :+1:
Ping me if there's anything else I can help with.
