### ISSUE TITLE
Mixin crasher

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#25]
```
package miniboxing.tests.compile
import miniboxing.plugin.minispec
import scala.annotation.tailrec
import scala.reflect.ClassTag

trait Ordering[@minispec A] {
  def eqv(x: Array[A], y: Array[A]): Boolean = false
}

trait ArrayVectorOrder[@minispec A] extends Ordering[A] {
  override def eqv(x: Array[A], y: Array[A]): Boolean = super.eqv(x, y)
}

object vectorOrder {
  implicit def arrayOrder[@minispec A](implicit ct: ClassTag[A]) = new ArrayVectorOrder[A] { }
}
sun@sun-laptop:/mnt/data-local/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ rm -rf miniboxing && ../mb-scalac mb_spire_9.scala

     while compiling: mb_spire_9.scala
        during phase: mixin
     library version: version 2.10.3-20130625-164027-d22e8d282c
    compiler version: version 2.10.3-20130627-153946-54cb6af7db
  reconstructed args: -bootclasspath /home/sun/workspace/dev/miniboxing-plugin//components/runtime/target/scala-2.10/miniboxing-runtime_2.10-0.1-SNAPSHOT.jar:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar -Xplugin:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar

  last tree to typer: TypeTree(object ArrayVectorOrder_L$class)
              symbol: object ArrayVectorOrder_L$class in package compile (flags: <module> abstract <trait> <implclass> <latemodule>)
   symbol definition: abstract class ArrayVectorOrder_L$class extends Ordering_L$class with ArrayVectorOrder with ArrayVectorOrder_L
                 tpe: miniboxing.tests.compile.ArrayVectorOrder_L$class
       symbol owners: object ArrayVectorOrder_L$class -> package compile
      context owners: anonymous class anon$1 -> package compile

== Enclosing template or block ==

Template( // val <local $anon>: <notype>, tree.tpe=miniboxing.tests.compile.anon$1
  "java.lang.Object", "miniboxing.tests.compile.ArrayVectorOrder_L" // parents
  ValDef(
    private
    "_"
    <tpt>
    <empty>
  )
  DefDef( // def <init>(): miniboxing.tests.compile.anon$1
    <method> <triedcooking>
    "<init>"
    []
    List(Nil)
    <tpt> // tree.tpe=miniboxing.tests.compile.anon$1
    Block( // tree.tpe=Unit
      // 3 statements
      Apply( // def <init>(): Object in class Object, tree.tpe=Object
        vectorOrder$$anon$1.super."<init>" // def <init>(): Object in class Object, tree.tpe=()Object
        Nil
      )
      Apply( // def $init$(): Unit in object Ordering_L$class, tree.tpe=Unit
        vectorOrder$$anon$1.this.$asInstanceOf[miniboxing.tests.compile.Ordering_L$class]()."$init$" // def $init$(): Unit in object Ordering_L$class, tree.tpe=()Unit
        Nil
      )
      Apply( // def $init$(): Unit in object ArrayVectorOrder_L$class, tree.tpe=Unit
        vectorOrder$$anon$1.this.$asInstanceOf[miniboxing.tests.compile.ArrayVectorOrder_L$class]()."$init$" // def $init$(): Unit in object ArrayVectorOrder_L$class, tree.tpe=()Unit
        Nil
      )
      ()
    )
  )
)

== Expanded type of tree ==

TypeRef(
  TypeSymbol(
    abstract class ArrayVectorOrder_L$class extends Ordering_L$class with ArrayVectorOrder with ArrayVectorOrder_L

  )
)

unhandled exception while transforming mb_spire_9.scala
error: uncaught exception during compilation: java.lang.UnsupportedOperationException
error: java.lang.UnsupportedOperationException: tail of empty list
    at scala.collection.immutable.Nil$.tail(List.scala:339)
    at scala.collection.immutable.Nil$.tail(List.scala:334)
    at scala.tools.nsc.transform.Mixin$$anonfun$scala$tools$nsc$transform$Mixin$$rebindSuper$1.apply(Mixin.scala:129)
    at scala.tools.nsc.transform.Mixin$$anonfun$scala$tools$nsc$transform$Mixin$$rebindSuper$1.apply(Mixin.scala:122)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
    at scala.reflect.internal.SymbolTable.afterPhase(SymbolTable.scala:216)
    at scala.tools.nsc.Global.afterPickler(Global.scala:1104)
    at scala.tools.nsc.transform.Mixin.scala$tools$nsc$transform$Mixin$$rebindSuper(Mixin.scala:122)
    at scala.tools.nsc.transform.Mixin$$anonfun$scala$tools$nsc$transform$Mixin$$mixinTraitMembers$1$1.apply(Mixin.scala:345)
    at scala.tools.nsc.transform.Mixin$$anonfun$scala$tools$nsc$transform$Mixin$$mixinTraitMembers$1$1.apply(Mixin.scala:298)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.reflect.internal.Scopes$Scope.foreach(Scopes.scala:315)
    at scala.tools.nsc.transform.Mixin.scala$tools$nsc$transform$Mixin$$mixinTraitMembers$1(Mixin.scala:298)
    at scala.tools.nsc.transform.Mixin$$anonfun$addMixedinMembers$3.apply(Mixin.scala:373)
    at scala.tools.nsc.transform.Mixin$$anonfun$addMixedinMembers$3.apply(Mixin.scala:369)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
    at scala.tools.nsc.transform.Mixin.addMixedinMembers(Mixin.scala:369)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.preTransform(Mixin.scala:536)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:1264)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:477)
    at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2904)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1280)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1279)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1278)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:1264)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:477)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2927)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2925)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2925)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1298)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1298)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1297)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:1264)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:477)
    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:227)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:431)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:33)
    at scala.tools.nsc.Main$.doCompile(Main.scala:79)
    at scala.tools.nsc.Driver.process(Driver.scala:54)
    at scala.tools.nsc.Driver.main(Driver.scala:67)
    at scala.tools.nsc.Main.main(Main.scala)

Exception in thread "main" java.lang.UnsupportedOperationException: tail of empty list
    at scala.collection.immutable.Nil$.tail(List.scala:339)
    at scala.collection.immutable.Nil$.tail(List.scala:334)
    at scala.tools.nsc.transform.Mixin$$anonfun$scala$tools$nsc$transform$Mixin$$rebindSuper$1.apply(Mixin.scala:129)
    at scala.tools.nsc.transform.Mixin$$anonfun$scala$tools$nsc$transform$Mixin$$rebindSuper$1.apply(Mixin.scala:122)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
    at scala.reflect.internal.SymbolTable.afterPhase(SymbolTable.scala:216)
    at scala.tools.nsc.Global.afterPickler(Global.scala:1104)
    at scala.tools.nsc.transform.Mixin.scala$tools$nsc$transform$Mixin$$rebindSuper(Mixin.scala:122)
    at scala.tools.nsc.transform.Mixin$$anonfun$scala$tools$nsc$transform$Mixin$$mixinTraitMembers$1$1.apply(Mixin.scala:345)
    at scala.tools.nsc.transform.Mixin$$anonfun$scala$tools$nsc$transform$Mixin$$mixinTraitMembers$1$1.apply(Mixin.scala:298)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.reflect.internal.Scopes$Scope.foreach(Scopes.scala:315)
    at scala.tools.nsc.transform.Mixin.scala$tools$nsc$transform$Mixin$$mixinTraitMembers$1(Mixin.scala:298)
    at scala.tools.nsc.transform.Mixin$$anonfun$addMixedinMembers$3.apply(Mixin.scala:373)
    at scala.tools.nsc.transform.Mixin$$anonfun$addMixedinMembers$3.apply(Mixin.scala:369)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
    at scala.tools.nsc.transform.Mixin.addMixedinMembers(Mixin.scala:369)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.preTransform(Mixin.scala:536)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:1264)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:477)
    at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2904)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1280)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1279)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1278)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:1264)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:477)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2927)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2925)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2925)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1298)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1298)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1297)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:1264)
    at scala.tools.nsc.transform.Mixin$MixinTransformer.transform(Mixin.scala:477)
    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:227)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:431)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:33)
    at scala.tools.nsc.Main$.doCompile(Main.scala:79)
    at scala.tools.nsc.Driver.process(Driver.scala:54)
    at scala.tools.nsc.Driver.main(Driver.scala:67)
    at scala.tools.nsc.Main.main(Main.scala)
```

**Comment by VladUreche** [comment]
Same bug affects specialization:
https://issues.scala-lang.org/browse/SI-7638
