### ISSUE TITLE
Incorrect var handling

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#27]
```
sun@sun-laptop:/mnt/data-local/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ cat mb_spire_11.scala 
package miniboxing.tests.compile
import miniboxing.plugin.minispec

trait Field2[@minispec A] {
  def zero: A
  def plus(o1: A, o2: A): A
  def times(o1: A, o2: A): A
}

trait ArrayInnerProductSpace2[@minispec A] {
  def scalar: Field2[A]
  private[this] var z: A = _

  def dot(v: Array[A], w: Array[A], zero: A): A = {
    z = scalar.zero
    var i = 0
    while (i < v.length && i < w.length) {
      z = scalar.plus(z, scalar.times(v(i), w(i)))
      i += 1
    }
    z
  }
}
sun@sun-laptop:/mnt/data-local/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ ../mb-scalac mb_spire_11.scala 
error: 
     while compiling: mb_spire_11.scala
        during phase: minibox
     library version: version 2.10.3-20130708-144415-62405227dd
    compiler version: version 2.10.3-20130708-163611-504b5f3b15
  reconstructed args: -bootclasspath /home/sun/workspace/dev/miniboxing-plugin//components/runtime/target/scala-2.10/miniboxing-runtime_2.10-0.1-SNAPSHOT.jar:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar -Xplugin:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar

  last tree to typer: term dot_J
              symbol: method dot_J in trait ArrayInnerProductSpace2_J (flags: <method>)
   symbol definition: def dot_J(val ArrayInnerProductSpace2_A_TypeTag: Byte,v: Array[Asp],w: Array[Asp],zero: Long): Long
       symbol owners: method dot_J -> trait ArrayInnerProductSpace2_J -> package compile
      context owners: method dot_J -> trait ArrayInnerProductSpace2_J -> package compile

== Enclosing template or block ==

Apply( // final def minibox2box[T](l: Long,tag: Byte): T in object MiniboxConversions
  TypeApply( // final def minibox2box[T](l: Long,tag: Byte): T in object MiniboxConversions, tree.tpe=(l: Long, tag: Byte)Asp
    MiniboxConversions.this."minibox2box" // final def minibox2box[T](l: Long,tag: Byte): T in object MiniboxConversions, tree.tpe=[T](l: Long, tag: Byte)T
    <tpt> // tree.tpe=Asp
  )
  // 2 arguments
  ArrayInnerProductSpace2.this."z" // private[this] var z: Long in trait ArrayInnerProductSpace2_J, tree.tpe=Long
  "ArrayInnerProductSpace2_A_TypeTag" // val ArrayInnerProductSpace2_A_TypeTag: Byte, tree.tpe=Byte
)

uncaught exception during compilation: scala.reflect.internal.Types$TypeError
error: scala.reflect.internal.Types$TypeError: reassignment to val
    at scala.tools.nsc.typechecker.Contexts$Context.issueCommon(Contexts.scala:397)
    at scala.tools.nsc.typechecker.Contexts$Context.issue(Contexts.scala:401)
    at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueTypeError(ContextErrors.scala:103)
    at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueNormalTypeError(ContextErrors.scala:87)
    at scala.tools.nsc.typechecker.ContextErrors$TyperContextErrors$TyperErrorGen$.AssignmentError(ContextErrors.scala:296)
    at scala.tools.nsc.typechecker.Typers$Typer.fail$3(Typers.scala:4238)
    at scala.tools.nsc.typechecker.Typers$Typer.typedAssign$1(Typers.scala:4265)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5539)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5603)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:389)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2925)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$60.apply(Typers.scala:3029)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$60.apply(Typers.scala:3029)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3029)
    at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2429)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5531)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5531)
    at scala.tools.nsc.typechecker.Typers$Typer.typerWithLocalContext(Typers.scala:507)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5531)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5603)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:239)
    at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:5806)
    at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:2254)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5530)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5603)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:251)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5665)
    at miniboxing.plugin.Duplicators.retyped(Duplicators.scala:42)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$46.apply(MiniboxTreeTransformation.scala:727)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$46.apply(MiniboxTreeTransformation.scala:727)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
    at scala.reflect.internal.SymbolTable.beforePhase(SymbolTable.scala:215)
    at miniboxing.plugin.MiniboxPhase$class.beforeMinibox(Minibox.scala:112)
    at miniboxing.plugin.Minibox$Component$.beforeMinibox(Minibox.scala:70)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.duplicateBody(MiniboxTreeTransformation.scala:727)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.specializeDefDefBody(MiniboxTreeTransformation.scala:693)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxTreeTransformation.scala:224)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:125)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:70)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2900)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$9.apply(MiniboxTreeTransformation.scala:174)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$9.apply(MiniboxTreeTransformation.scala:174)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxTreeTransformation.scala:174)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:125)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:70)
    at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2904)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1280)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1279)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1278)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxTreeTransformation.scala:458)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:125)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:70)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2927)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2925)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2925)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$miniboxTransform$2.apply(MiniboxTreeTransformation.scala:144)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$miniboxTransform$2.apply(MiniboxTreeTransformation.scala:141)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxTreeTransformation.scala:141)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:125)
    at miniboxing.plugin.Minibox$Component$$anon$1$$anonfun$1.apply(Minibox.scala:96)
    at miniboxing.plugin.Minibox$Component$$anon$1$$anonfun$1.apply(Minibox.scala:96)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
    at scala.reflect.internal.SymbolTable.afterPhase(SymbolTable.scala:216)
    at miniboxing.plugin.MiniboxPhase$class.afterMinibox(Minibox.scala:109)
    at miniboxing.plugin.Minibox$Component$$anon$1.transform(Minibox.scala:96)
    at miniboxing.plugin.Minibox$Component$$anon$1.transform(Minibox.scala:89)
    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:227)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:431)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:33)
    at scala.tools.nsc.Main$.doCompile(Main.scala:79)
    at scala.tools.nsc.Driver.process(Driver.scala:54)
    at scala.tools.nsc.Driver.main(Driver.scala:67)
    at scala.tools.nsc.Main.main(Main.scala)

Exception in thread "main" scala.reflect.internal.Types$TypeError: reassignment to val
    at scala.tools.nsc.typechecker.Contexts$Context.issueCommon(Contexts.scala:397)
    at scala.tools.nsc.typechecker.Contexts$Context.issue(Contexts.scala:401)
    at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueTypeError(ContextErrors.scala:103)
    at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueNormalTypeError(ContextErrors.scala:87)
    at scala.tools.nsc.typechecker.ContextErrors$TyperContextErrors$TyperErrorGen$.AssignmentError(ContextErrors.scala:296)
    at scala.tools.nsc.typechecker.Typers$Typer.fail$3(Typers.scala:4238)
    at scala.tools.nsc.typechecker.Typers$Typer.typedAssign$1(Typers.scala:4265)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5539)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5603)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:389)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2925)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$60.apply(Typers.scala:3029)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$60.apply(Typers.scala:3029)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3029)
    at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2429)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5531)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5531)
    at scala.tools.nsc.typechecker.Typers$Typer.typerWithLocalContext(Typers.scala:507)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5531)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5603)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:239)
    at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:5806)
    at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:2254)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5530)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5603)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:251)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5665)
    at miniboxing.plugin.Duplicators.retyped(Duplicators.scala:42)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$46.apply(MiniboxTreeTransformation.scala:727)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$46.apply(MiniboxTreeTransformation.scala:727)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
    at scala.reflect.internal.SymbolTable.beforePhase(SymbolTable.scala:215)
    at miniboxing.plugin.MiniboxPhase$class.beforeMinibox(Minibox.scala:112)
    at miniboxing.plugin.Minibox$Component$.beforeMinibox(Minibox.scala:70)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.duplicateBody(MiniboxTreeTransformation.scala:727)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.specializeDefDefBody(MiniboxTreeTransformation.scala:693)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxTreeTransformation.scala:224)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:125)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:70)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2900)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$9.apply(MiniboxTreeTransformation.scala:174)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$9.apply(MiniboxTreeTransformation.scala:174)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxTreeTransformation.scala:174)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:125)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:70)
    at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2904)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1280)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1279)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1278)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxTreeTransformation.scala:458)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:125)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:70)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2927)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2925)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2925)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$miniboxTransform$2.apply(MiniboxTreeTransformation.scala:144)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$miniboxTransform$2.apply(MiniboxTreeTransformation.scala:141)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxTreeTransformation.scala:141)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:125)
    at miniboxing.plugin.Minibox$Component$$anon$1$$anonfun$1.apply(Minibox.scala:96)
    at miniboxing.plugin.Minibox$Component$$anon$1$$anonfun$1.apply(Minibox.scala:96)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
    at scala.reflect.internal.SymbolTable.afterPhase(SymbolTable.scala:216)
    at miniboxing.plugin.MiniboxPhase$class.afterMinibox(Minibox.scala:109)
    at miniboxing.plugin.Minibox$Component$$anon$1.transform(Minibox.scala:96)
    at miniboxing.plugin.Minibox$Component$$anon$1.transform(Minibox.scala:89)
    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:227)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:431)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:33)
    at scala.tools.nsc.Main$.doCompile(Main.scala:79)
    at scala.tools.nsc.Driver.process(Driver.scala:54)
    at scala.tools.nsc.Driver.main(Driver.scala:67)
    at scala.tools.nsc.Main.main(Main.scala)
```

**Comment by VladUreche** [comment]
Trimmed down example:

```
package miniboxing.tests.compile
import miniboxing.plugin.minispec

trait SpireBug11[@minispec A] {
  private[this] var z: A = _

  def dot(zero: A)= {
    z = zero
  }
}
```

**Comment by VladUreche** [comment]
Also should think of inherited miniboxed fields...

**Comment by VladUreche** [comment]
This a pretty complicated bug to fix. I would rather not care about class fields, since managing their miniboxed variants gets hairy very quickly...
