### ISSUE TITLE
Scala Library - Incorrect methods generated for make-not-private methods

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#47]
```
sun@sun-laptop:/mnt/data-local/Work/Workspace/dev/miniboxing-plugin/tests/classloader-bench(wip)$ ./run.sh 
===============================================================================
RUNNING THE TEST PROJECT
===============================================================================
Running miniboxing tester...
Test Miniboxing
java.lang.ClassFormatError: Method miniboxing$benchmarks$collection$TraversableLike$$sliceInternal in class miniboxing/benchmarks/collection/TraversableLike$class has illegal modifiers: 0x409
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:792)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at miniboxing.benchmarks.collection.AbstractTraversable_class_J.<init>(Traversable.scala:105)
    at miniboxing.benchmarks.collection.AbstractIterable_class_J.<init>(AbstractIterable.scala:54)
    at miniboxing.benchmarks.collection.AbstractSeq_class_J.<init>(AbstractSeq.scala:40)
    at miniboxing.benchmarks.collection.immutable.Vector_class_J.<init>(Vector.scala:66)
    at miniboxing.classloader.test.TestMboxing$.main(TestMbox.scala:9)
    at miniboxing.classloader.test.TestMboxing.main(TestMbox.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:71)
    at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
    at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:139)
    at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:71)
    at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:139)
    at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:28)
    at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
    at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:35)
    at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
    at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:74)
    at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
    at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:105)
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

The problem is a stale not-private accessor method `miniboxing$benchmarks$collection$TraversableLike$$sliceInternal` to 
`private[this] def sliceInternal(from: Int, until: Int, b: Builder[A, Repr]): Repr`
in `TraversableLike$class`. The method is both static and in an interface, crashing the JVM with the above error.

No time for finding a minimalization now. :(

**Comment by VladUreche** [comment]
Better described in #86, with a test case.
