### ISSUE TITLE
REPL classes don't get rewired

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#53]
```
scala> :paste
// Entering paste mode (ctrl-D to finish)

class Z[@miniboxed T](t: T) {
  def foo() = trace(Test1.baz(t))
}


// Exiting paste mode, now interpreting.

Specializing class Z...

  // interface:
  abstract trait Z[T] extends Object {
    def foo(): Unit                                                       
  }

  // specialized class:
  class Z_J[Tsp] extends Z[Tsp] {
    def <init>(val iw$Z_J|T_TypeTag: Byte,t: Long): Z_J[Tsp]               // is a specialized implementation of constructor Z
    def foo(): Unit                                                        // is a specialized implementation of method foo
    private[this] val iw$Z_J|T_TypeTag: Byte                               // no info
    private[this] val t: Long                                              // is a specialized implementation of value t
  }

  // specialized class:
  class Z_L[Tsp] extends Z[Tsp] {
    def <init>(t: Tsp): Z_L[Tsp]                                           // is a specialized implementation of constructor Z
    def foo(): Unit                                                        // is a specialized implementation of method foo
    private[this] val t: Tsp                                               // is a specialized implementation of value t
  }




defined class Z

scala> val z_opt=new Z(2)
<console>:10: error: trait Z is abstract; cannot be instantiated
       val c_opt=new Z(2)

scala> val c_opt=new Z_J(2,2)
<console>:7: error: not found: type Z_J
       val c_opt=new Z_J(2,2)
                     ^
```

**Comment by VladUreche** [comment]
Really broken:

```
scala> :paste
// Entering paste mode (ctrl-D to finish)

object Test3 {
  class Z[@miniboxed T](t: T) {
  def foo() = trace(Test1.baz(t))
}

  val z_opt: Z[_] = new Z(3)
  val z_gen: Z[_] = new Z("x")
}

// Exiting paste mode, now interpreting.

Specializing class Z...

  // interface:
  abstract trait Z[T] extends Object {
    def foo(): Unit                                                       
  }

  // specialized class:
  class Z_J[Tsp] extends $read.$iw.$iw.Test3.Z[Tsp] {
    def <init>(val iw$Test3$Z_J|T_TypeTag: Byte,t: Long): $line19.$read.$iw.$iw.Test3.Z_J[Tsp] // is a specialized implementation of constructor Z
    def foo(): Unit                                                        // is a specialized implementation of method foo
    private[this] val iw$Test3$Z_J|T_TypeTag: Byte                         // no info
    private[this] val t: Long                                              // is a specialized implementation of value t
  }

  // specialized class:
  class Z_L[Tsp] extends $read.$iw.$iw.Test3.Z[Tsp] {
    def <init>(t: Tsp): $line19.$read.$iw.$iw.Test3.Z_L[Tsp]               // is a specialized implementation of constructor Z
    def foo(): Unit                                                        // is a specialized implementation of method foo
    private[this] val t: Tsp                                               // is a specialized implementation of value t
  }




warning: there were 1 inliner warning(s); re-run with -Yinline-warnings for details
defined module Test3

scala> trace(Test3.z_opt.foo())
java.lang.NoClassDefFoundError: Test3$Z_J
    at Test3$.<init>(<console>:15)
    at Test3$.<clinit>(<console>)
    at $anonfun$1.apply$mcV$sp(<console>:12)
    at .trace(<console>:9)
    at .<init>(<console>:12)
    at .<clinit>(<console>)
    at .<init>(<console>:7)
    at .<clinit>(<console>)
    at $print(<console>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:734)
    at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:983)
    at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:604)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
    at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:756)
    at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:801)
    at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:713)
    at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:577)
    at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:584)
    at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:587)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:878)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:833)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:833)
    at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
    at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:833)
    at scala.tools.nsc.interpreter.ILoop.main(ILoop.scala:900)
    at xsbt.ConsoleInterface.run(ConsoleInterface.scala:69)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:102)
    at sbt.compiler.AnalyzingCompiler.console(AnalyzingCompiler.scala:77)
    at sbt.Console.sbt$Console$$console0$1(Console.scala:23)
    at sbt.Console$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(Console.scala:24)
    at sbt.TrapExit$.sbt$TrapExit$$executeMain$1(TrapExit.scala:33)
    at sbt.TrapExit$$anon$1.run(TrapExit.scala:42)
Caused by: java.lang.ClassNotFoundException: Test3$Z_J
    at scala.tools.nsc.interpreter.AbstractFileClassLoader.findClass(AbstractFileClassLoader.scala:69)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 41 more
```

**Comment by VladUreche** [comment]
Underlying problem:

```
sun@sun-laptop:/mnt/data-local/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ cat gh-bug-53.scala 
package miniboxing.tests.compile.bug53

object Test {
  class BUG53[@miniboxed T]() {}
}
sun@sun-laptop:/mnt/data-local/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ ../mb-scalac -Xprint:minibox gh-bug-53.scala 
[[syntax trees at end of                   minibox]] // gh-bug-53.scala
package miniboxing.tests.compile.bug53 {
  object Test extends Object {
    def <init>(): miniboxing.tests.compile.bug53.Test.type = {
      Test.super.<init>();
      ()
    };
    abstract trait BUG53[@miniboxed T >: Nothing <: Any] extends Object
  }
}

```

Where are the specialized variants? Uh-oh, lost'em :|

**Comment by VladUreche** [comment]
REPL crasher, following d8d55948:

```
object Test1 {
  def foo[@miniboxed T](t: T): T = 
    throw new Exception("Innermost performance-critical method")
  def bar[@miniboxed T](t: T): T = foo(t)
  def baz[@miniboxed T](t: T): T = bar(t)
}  

def trace(statement: => Unit): Unit =
  try {
    statement
  } catch {
    case e: Exception => 
      // prettify the trace and output it:
      for (frame <- e.getStackTrace.take(3))
        println(frame.toString.replaceAll(".*Test", "Test"))
  }

object Test3 {
  class Z[@miniboxed T](t: T) {
    def foo() = trace(Test1.baz(t))
  }

  val z_opt: Z[_] = new Z(3)
  val z_gen: Z[_] = new Z("x")
}
```

That's:

```
sun@sun-laptop:/mnt/data-local/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ ../mb-scala
Welcome to Scala version 2.10.4-20131024-104230-05681d4def (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_45).
Type in expressions to have them evaluated.
Type :help for more information.

scala> object Test1 {
  def foo[@miniboxed T](t: T): T = 
    throw new Exception("Innermost performance-critical method")
  def bar[@miniboxed T](t: T): T = foo(t)
  def baz[@miniboxed T](t: T): T = bar(t)
}  

def trace(statement: => Unit): Unit =
  try {
    statement
  } catch {
    case e: Exception => 
      // prettify the trace and output it:
      for (frame <- e.getStackTrace.take(3))
        println(frame.toString.replaceAll(".*Test", "Test"))
  }

object Test3 {
  class Z[@miniboxed T](t: T) {
    def foo() = trace(Test1.baz(t))
  }

  val z_opt: Z[_] = new Z(3)
  val z_gen: Z[_] = new Z("x")
}
ReplGlobal.abort: iw$Test3$Z_J|T_TypeTag not in List(value iw$Test3$Z_J|T_TypeTag, value t)
error: iw$Test3$Z_J|T_TypeTag not in List(value iw$Test3$Z_J|T_TypeTag, value t)
unhandled exception while transforming <console>
error: uncaught exception during compilation: scala.reflect.internal.FatalError
scala.reflect.internal.FatalError: 
     while compiling: <console>
        during phase: constructors
     library version: version 2.10.4-20131024-104230-05681d4def
    compiler version: version 2.10.4-20131024-104230-05681d4def
  reconstructed args: -bootclasspath /home/sun/workspace/dev/miniboxing-plugin//components/runtime/target/scala-2.10/miniboxing-runtime_2.10-0.1-SNAPSHOT.jar:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar -Xplugin:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar

  last tree to typer: Assign
              symbol: null
   symbol definition: null
                 tpe: Unit
       symbol owners: 
      context owners: anonymous class $anonfun$foo$1 -> class Z_J -> object Test3 -> object $iw -> object $iw -> object $read -> package $line3

== Enclosing template or block ==

Template( // val <local $anonfun>: <notype>, tree.tpe=Test3.Z_J#$anonfun$foo$1
  "scala.runtime.AbstractFunction0$mcV$sp", "scala.Serializable" // parents
  ValDef(
    private
    "_"
    <tpt>
    <empty>
  )
  // 6 statements
  DefDef( // def <init>(arg$outer: Test3.Z_J): Test3.Z_J#$anonfun$foo$1
    <method> <triedcooking>
    "<init>"
    []
    // 1 parameter list
    ValDef( // $outer: Test3.Z_J
      <param> <triedcooking>
      "$outer"
      <tpt> // tree.tpe=Test3.Z_J
      <empty>
    )
    <tpt> // tree.tpe=Test3.Z_J#$anonfun$foo$1
    Block( // tree.tpe=Unit
      Apply( // def <init>(): scala.runtime.AbstractFunction0$mcV$sp in class AbstractFunction0$mcV$sp, tree.tpe=scala.runtime.AbstractFunction0$mcV$sp
        $anonfun$foo$1.super."<init>" // def <init>(): scala.runtime.AbstractFunction0$mcV$sp in class AbstractFunction0$mcV$sp, tree.tpe=()scala.runtime.AbstractFunction0$mcV$sp
        Nil
      )
      ()
    )
  )
  DefDef( // final def apply(): Unit
    <method> final <triedcooking>
    "apply"
    []
    List(Nil)
    <tpt> // tree.tpe=Unit
    Apply( // def apply$mcV$sp(): Unit, tree.tpe=Unit
      $anonfun$foo$1.this."apply$mcV$sp" // def apply$mcV$sp(): Unit, tree.tpe=()Unit
      Nil
    )
  )
  DefDef( // def apply$mcV$sp(): Unit
    <method> <specialized> <triedcooking>
    "apply$mcV$sp"
    []
    List(Nil)
    <tpt> // tree.tpe=Unit
    Block( // tree.tpe=Unit
      Apply( // def baz(t: Object): Object in object Test1, tree.tpe=Object
        $iw.this."Test1"."baz" // def baz(t: Object): Object in object Test1, tree.tpe=(t: Object)Object
        Apply( // final def minibox2box(l: Long,tag: Byte): Object in object MiniboxConversions, tree.tpe=Object
          MiniboxConversions.this."minibox2box" // final def minibox2box(l: Long,tag: Byte): Object in object MiniboxConversions, tree.tpe=(l: Long, tag: Byte)Object
          // 2 arguments
          $anonfun$foo$1.this."$outer "."$line3$$read$$iw$$iw$Test3$Z_J$$t" // val t: Long in class Z_J, tree.tpe=Long
          $anonfun$foo$1.this."$outer "."$line3$$read$$iw$$iw$Test3$Z_J$$$line3$$read$$iw$$iw$Test3$Z_J|T_TypeTag" // val iw$Test3$Z_J|T_TypeTag: Byte in class Z_J, tree.tpe=Byte
        )
      )
      ()
    )
  )
  ValDef( // private[this] val $outer: Test3.Z_J
    private <local> <synthetic> <paramaccessor> <triedcooking>
    "$outer "
    <tpt> // tree.tpe=Test3.Z_J
    <empty>
  )
  DefDef( // val $outer(): Test3.Z_J
    <method> <synthetic> <stable> <expandedname>
    "$line3$$read$$iw$$iw$Test3$Z_J$$anonfun$$$outer"
    []
    List(Nil)
    <tpt> // tree.tpe=Test3.Z_J
    $anonfun$foo$1.this."$outer " // private[this] val $outer: Test3.Z_J, tree.tpe=Test3.Z_J
  )
  DefDef( // final def apply(): Object
    <method> final <bridge>
    "apply"
    []
    List(Nil)
    <tpt> // tree.tpe=Object
    Block( // tree.tpe=runtime.BoxedUnit
      Apply( // final def apply(): Unit, tree.tpe=Unit
        $anonfun$foo$1.this."apply" // final def apply(): Unit, tree.tpe=()Unit
        Nil
      )
      "scala"."runtime"."BoxedUnit"."UNIT" // final val UNIT: runtime.BoxedUnit in object BoxedUnit, tree.tpe=runtime.BoxedUnit
    )
  )
)

== Expanded type of tree ==

TypeRef(TypeSymbol(final abstract class Unit extends ))

iw$Test3$Z_J|T_TypeTag not in List(value iw$Test3$Z_J|T_TypeTag, value t)
    at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:49)
    at scala.tools.nsc.Global.abort(Global.scala:254)
    at scala.tools.nsc.interpreter.IMain$$anon$1.scala$tools$nsc$interpreter$ReplGlobal$$super$abort(IMain.scala:265)
    at scala.tools.nsc.interpreter.ReplGlobal$class.abort(ReplGlobal.scala:21)
    at scala.tools.nsc.interpreter.IMain$$anon$1.abort(IMain.scala:265)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.scala$tools$nsc$transform$Constructors$ConstructorTransformer$$parameterNamed$1(Constructors.scala:71)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.scala$tools$nsc$transform$Constructors$ConstructorTransformer$$parameter$1(Constructors.scala:63)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$8.apply(Constructors.scala:268)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$8.apply(Constructors.scala:259)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transformClassTemplate(Constructors.scala:259)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transform$1.apply(Constructors.scala:575)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transform$1.apply(Constructors.scala:575)
    at scala.reflect.internal.Trees$class.deriveClassDef(Trees.scala:1616)
    at scala.reflect.internal.SymbolTable.deriveClassDef(SymbolTable.scala:13)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:575)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transformClassTemplate$2.apply(Constructors.scala:199)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transformClassTemplate$2.apply(Constructors.scala:170)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transformClassTemplate(Constructors.scala:170)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transform$1.apply(Constructors.scala:575)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transform$1.apply(Constructors.scala:575)
    at scala.reflect.internal.Trees$class.deriveClassDef(Trees.scala:1616)
    at scala.reflect.internal.SymbolTable.deriveClassDef(SymbolTable.scala:13)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:575)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transformClassTemplate$2.apply(Constructors.scala:199)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transformClassTemplate$2.apply(Constructors.scala:170)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transformClassTemplate(Constructors.scala:170)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transform$1.apply(Constructors.scala:575)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transform$1.apply(Constructors.scala:575)
    at scala.reflect.internal.Trees$class.deriveClassDef(Trees.scala:1616)
    at scala.reflect.internal.SymbolTable.deriveClassDef(SymbolTable.scala:13)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:575)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transformClassTemplate$2.apply(Constructors.scala:199)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transformClassTemplate$2.apply(Constructors.scala:170)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transformClassTemplate(Constructors.scala:170)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transform$1.apply(Constructors.scala:575)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transform$1.apply(Constructors.scala:575)
    at scala.reflect.internal.Trees$class.deriveClassDef(Trees.scala:1616)
    at scala.reflect.internal.SymbolTable.deriveClassDef(SymbolTable.scala:13)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:575)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transformClassTemplate$2.apply(Constructors.scala:199)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transformClassTemplate$2.apply(Constructors.scala:170)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transformClassTemplate(Constructors.scala:170)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transform$1.apply(Constructors.scala:575)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transform$1.apply(Constructors.scala:575)
    at scala.reflect.internal.Trees$class.deriveClassDef(Trees.scala:1616)
    at scala.reflect.internal.SymbolTable.deriveClassDef(SymbolTable.scala:13)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:575)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:30)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2927)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2925)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2925)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1298)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1298)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1297)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:577)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:30)
    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:227)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:431)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
    at scala.tools.nsc.interpreter.IMain.compileSourcesKeepingRun(IMain.scala:428)
    at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compileAndSaveRun(IMain.scala:801)
    at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:761)
    at scala.tools.nsc.interpreter.IMain$Request.compile$lzycompute(IMain.scala:936)
    at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:931)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:603)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
    at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:760)
    at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:805)
    at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:717)
    at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:581)
    at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:588)
    at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:591)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:882)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
    at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
    at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:837)
    at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:83)
    at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
    at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:105)
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

That entry seems to have slain the compiler.  Shall I replay
your session? I can re-run each line except the last one.
[y/n]
Abandoning crashed session.
```

**Comment by VladUreche** [comment]
Okay, constructors crash should be a different bug, #55.

Now, for the initial bug, the problem is that flags are not versioned according to phase. So, we run miniboxing, turn a class, say `C`, into an abstract trait and then try to type code that constructs a new instance, `new C(3)`. The typer prevents us from doing that, although this should be special-cased for miniboxed classes.

As a workaround, a small patch in Scala is necessary. Or, a correct implementation, by adding two phases before and after typer: reset the TRAIT | ABSTRACT flags and set them again.

**Comment by VladUreche** [comment]
Last one on this trail: #56.
