### ISSUE TITLE
Another crasher...

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#7]
```
$ cat ../miniboxing-plugin/test/bugs/7.scala
package miniboxing.bugs
import miniboxing.plugin.minispec

class BUG7[@minispec T](head: T, tail: BUG7[T]) {
  override def hashCode(): Int = {
    val headhash = head.##
    if (tail == null)
      headhash
    else
      (headhash >> 8 | tail.hashCode)
  }
}
$ build/quick/bin/scalac -cp ../miniboxing-plugin/components/runtime/target/scala-2.10/miniboxing-runime_2.10-0.1-SNAPSHOT.jar:../miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar -Xplugin:../miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar ../miniboxing-plugin/test/bugs/7.scala 
Specializing class BUG7...
-------------- WIDENDED CLAZZ ----------------
BUG7 [T]Object {
  private[this] val head: T
  private[this] val tail: miniboxing.bugs.BUG7[T]
  def <init>(head: T,tail: miniboxing.bugs.BUG7[T],val T_TypeTag: Byte): miniboxing.bugs.BUG7[T]
  override def hashCode(): Int
  private[this] val T_TypeTag: Byte
  override def hashCode_J(): Int
}
-------------- INTERFACE ----------------
BUG7_interface [Tsp]AnyRef {
  override def hashCode(): Int
  override def hashCode_J(): Int
}
-------------- ORIGINAL CLASS ----------------
BUG7 [T]Object
        with miniboxing.bugs.BUG7_interface[T] {
  private[this] val head: T
  private[this] val tail: miniboxing.bugs.BUG7[T]
  def <init>(head: T,tail: miniboxing.bugs.BUG7[T],val T_TypeTag: Byte): miniboxing.bugs.BUG7[T]
  override def hashCode(): Int
  private[this] val T_TypeTag: Byte
  override def hashCode_J(): Int
}
------------ SPEC CLASS ------------
BUG7_J [Tsp]Object
        with miniboxing.bugs.BUG7_interface[Tsp] {
  private[this] val head: Long
  def <init>(head: Long,tail: miniboxing.bugs.BUG7_interface[Long],val T_TypeTag: Byte): miniboxing.bugs.BUG7_J[Tsp]
  override def hashCode(): Int
  private[this] val tail: miniboxing.bugs.BUG7_interface[Long]
  private[this] val T_TypeTag: Byte
  override def hashCode_J(): Int
}
------------ SPEC CLASS ------------
BUG7_L [Tsp]Object
        with miniboxing.bugs.BUG7_interface[Tsp] {
  private[this] val head: Tsp
  def <init>(head: Tsp,tail: miniboxing.bugs.BUG7_interface[Tsp],val T_TypeTag: Byte): miniboxing.bugs.BUG7_L[Tsp]
  override def hashCode(): Int
  private[this] val tail: miniboxing.bugs.BUG7_interface[Tsp]
  private[this] val T_TypeTag: Byte
  override def hashCode_J(): Int
}
-------------- TEMPLATE MEMBERS ----------------
miniboxing.bugs.BUG7.head
miniboxing.bugs.BUG7.hashCode
miniboxing.bugs.BUG7.tail
miniboxing.bugs.BUG7.<init>
miniboxing.bugs.BUG7_interface.hashCode_J   - Interface()
miniboxing.bugs.BUG7_J.head     - SpecializedImplementationOf2(miniboxing.bugs.BUG7.head)
miniboxing.bugs.BUG7_J.hashCode_J   - SpecializedImplementationOf2(miniboxing.bugs.BUG7.hashCode)
miniboxing.bugs.BUG7_L.head     - SpecializedImplementationOf2(miniboxing.bugs.BUG7.head)
miniboxing.bugs.BUG7_J.tail     - SpecializedImplementationOf2(miniboxing.bugs.BUG7.tail)
miniboxing.bugs.BUG7_L.hashCode_J   - ForwardTo(miniboxing.bugs.BUG7_L.hashCode)
miniboxing.bugs.BUG7_L.hashCode     - SpecializedImplementationOf2(miniboxing.bugs.BUG7.hashCode)
miniboxing.bugs.BUG7.hashCode_J     - ForwardTo(miniboxing.bugs.BUG7.hashCode)
miniboxing.bugs.BUG7_J.<init>   - SpecializedImplementationOf2(miniboxing.bugs.BUG7.<init>)
miniboxing.bugs.BUG7_L.<init>   - SpecializedImplementationOf2(miniboxing.bugs.BUG7.<init>)
miniboxing.bugs.BUG7_J.hashCode     - ForwardTo(miniboxing.bugs.BUG7_J.hashCode_J)
miniboxing.bugs.BUG7.hashCode   - ForwardTo(miniboxing.bugs.BUG7.hashCode)
miniboxing.bugs.BUG7_interface.hashCode     - Interface()
miniboxing.bugs.BUG7_L.tail     - SpecializedImplementationOf2(miniboxing.bugs.BUG7.tail)
creating class - BUG7_interface: List(class Object)
creating class - BUG7_L: List(class Object, trait BUG7_interface)
creating class - BUG7_J: List(class Object, trait BUG7_interface)
collected miniboxing.bugs.BUG7.head
collected miniboxing.bugs.BUG7.tail
collected miniboxing.bugs.BUG7.<init>
collected miniboxing.bugs.BUG7.hashCode
creating tree for miniboxing.bugs.BUG7.T_TypeTag
creating tree for miniboxing.bugs.BUG7.hashCode_J
creating tree for miniboxing.bugs.BUG7_interface.hashCode
creating tree for miniboxing.bugs.BUG7_interface.hashCode_J
creating tree for miniboxing.bugs.BUG7_L.head
creating tree for miniboxing.bugs.BUG7_L.<init>
creating tree for miniboxing.bugs.BUG7_L.hashCode
creating tree for miniboxing.bugs.BUG7_L.tail
creating tree for miniboxing.bugs.BUG7_L.T_TypeTag
creating tree for miniboxing.bugs.BUG7_L.hashCode_J
Duplicators default case: Ident(Tsp)
 ---> Tsp
Duplicators default case: Ident(Tsp)
 ---> Tsp
miniboxing.bugs.BUG7_L.<init>
Duplicators default case: Ident(Tsp)
 ---> Tsp
Duplicators default case: Ident(Tsp)
 ---> Tsp
Duplicators default case: Ident(Tsp)
 ---> Tsp
Duplicators default case: Ident(Tsp)
 ---> Tsp
Duplicators default case: Apply(constructor Object)
 ---> BUG7.super.<init>()
Duplicators default case: Select(Super(class BUG7), <init>)
 ---> BUG7.super.<init>
Duplicators default case: Super(class BUG7)
 ---> BUG7.super
Duplicators default case: Literal(Constant(()))
 ---> ()
 *** hashCode : class BUG7_L
  *  hashCode
miniboxing.bugs.BUG7_L.hashCode
Duplicators default case: Apply(method ##)
 ---> BUG7.this.head.##()
Duplicators default case: Select(Select(This(class BUG7), head), ##)
 ---> BUG7.this.head.##
Duplicators default case: If
 ---> if (BUG7.this.tail.==(null))
  headhash
else
  headhash.>>(8).|(BUG7.this.tail.hashCode()())
Duplicators default case: Apply(method ==)
 ---> BUG7.this.tail.==(null)
Duplicators default case: Select(Select(This(class BUG7), tail), ==)
 ---> BUG7.this.tail.==
Duplicators default case: Literal(Constant(null))
 ---> null
Duplicators default case: Ident(headhash)
 ---> headhash
Duplicators default case: Apply(method |)
 ---> headhash.>>(8).|(BUG7.this.tail.hashCode()())
Duplicators default case: Select(Apply(method >>), |)
 ---> headhash.>>(8).|
Duplicators default case: Apply(method >>)
 ---> headhash.>>(8)
Duplicators default case: Select(Ident(headhash), >>)
 ---> headhash.>>
Duplicators default case: Ident(headhash)
 ---> headhash
Duplicators default case: Literal(Constant(8))
 ---> 8
Duplicators default case: Apply(method hashCode)
 ---> BUG7.this.tail.hashCode()()
Duplicators default case: Apply(method hashCode)
 ---> BUG7.this.tail.hashCode()
Duplicators default case: Select(Select(This(class BUG7), tail), hashCode)
 ---> BUG7.this.tail.hashCode
ERROR:
BUG7.this.tail.hashCode()()
BUG7_L.this.tail.hashCode()


error: 
     while compiling: ../miniboxing-plugin/test/bugs/7.scala
        during phase: minibox
     library version: version 2.10.0-20121014-154054-f3550d25e0
    compiler version: version 2.10.0-20121011-125927-25ad7876a9
  reconstructed args: -Xplugin:../miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar -classpath ../miniboxing-plugin/components/runtime/target/scala-2.10/miniboxing-runime_2.10-0.1-SNAPSHOT.jar:../miniboxing-plugin/components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.1-SNAPSHOT.jar

  last tree to typer: Select(Select(This(class BUG7), tail), hashCode)
              symbol: method hashCode in trait BUG7_interface (flags: <method> override <triedcooking> <synchronized>)
   symbol definition: override def hashCode(): Int
       symbol owners: method hashCode -> trait BUG7_interface -> package bugs
      context owners: method hashCode -> class BUG7_L -> package bugs

== Enclosing template or block ==

Apply( // override def hashCode(): Int in trait BUG7_interface
  BUG7.this."tail"."hashCode" // override def hashCode(): Int in trait BUG7_interface
  Nil
)

uncaught exception during compilation: scala.reflect.internal.Types$TypeError
error: scala.reflect.internal.Types$TypeError: Int does not take parameters
    at scala.tools.nsc.typechecker.Contexts$Context.issueCommon(Contexts.scala:375)
    at scala.tools.nsc.typechecker.Contexts$Context.issue(Contexts.scala:379)
    at scala.tools.nsc.typechecker.Infer$Inferencer.issue(Infer.scala:281)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$duplErrorTree$1(Typers.scala:2943)
    at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3254)
    at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4461)
    at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4493)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5366)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5443)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:415)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$56.apply(Typers.scala:2864)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$56.apply(Typers.scala:2864)
    at scala.tools.nsc.typechecker.Typers$Typer.withCondConstrTyper(Typers.scala:488)
    at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:2864)
    at scala.tools.nsc.typechecker.Typers$Typer.loop$1(Typers.scala:2891)
    at scala.tools.nsc.typechecker.Typers$Typer.typedArgs(Typers.scala:2897)
    at scala.tools.nsc.typechecker.Typers$Typer.handleMonomorphicCall$1(Typers.scala:3156)
    at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3200)
    at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4461)
    at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4493)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5366)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5443)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:415)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5510)
    at scala.tools.nsc.typechecker.Typers$Typer.typedIf$1(Typers.scala:4169)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5373)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5443)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:415)
    at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2335)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5372)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5372)
    at scala.tools.nsc.typechecker.Typers$Typer.typerWithLocalContext(Typers.scala:497)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5372)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5443)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:273)
    at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:5642)
    at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:2163)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5371)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5443)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:285)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5494)
    at miniboxing.plugin.Duplicators$BodyDuplicator.retypedMethodMB(Duplicators.scala:219)
    at miniboxing.plugin.Duplicators.retypedMethod(Duplicators.scala:50)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.addDefDefBody(MiniboxTreeTransformation.scala:300)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.addBody(MiniboxTreeTransformation.scala:264)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:111)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:52)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2819)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2819)
    at scala.collection.immutable.List.loop$1(List.scala:164)
    at scala.collection.immutable.List.mapConserve(List.scala:180)
    at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2819)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$transform$2.apply(MiniboxTreeTransformation.scala:87)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$transform$2.apply(MiniboxTreeTransformation.scala:87)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2855)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:87)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:52)
    at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2823)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1238)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1237)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2855)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1236)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2816)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:152)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:52)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2846)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2844)
    at scala.collection.immutable.List.loop$1(List.scala:164)
    at scala.collection.immutable.List.mapConserve(List.scala:180)
    at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2844)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$transform$1.apply(MiniboxTreeTransformation.scala:72)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$transform$1.apply(MiniboxTreeTransformation.scala:66)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2855)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:66)
    at miniboxing.plugin.Minibox$Component$$anon$1$$anonfun$transform$1.apply(Minibox.scala:41)
    at miniboxing.plugin.Minibox$Component$$anon$1$$anonfun$transform$1.apply(Minibox.scala:41)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:201)
    at scala.reflect.internal.SymbolTable.afterPhase(SymbolTable.scala:210)
    at miniboxing.plugin.MiniboxPhase$class.afterMinibox(Minibox.scala:51)
    at miniboxing.plugin.Minibox$Component$.afterMinibox(Minibox.scala:20)
    at miniboxing.plugin.Minibox$Component$$anon$1.transform(Minibox.scala:41)
    at miniboxing.plugin.Minibox$Component$$anon$1.transform(Minibox.scala:38)
    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:227)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:461)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:428)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:428)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1156)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:428)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1574)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1548)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1544)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1654)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:33)
    at scala.tools.nsc.Main$.doCompile(Main.scala:79)
    at scala.tools.nsc.Driver.process(Driver.scala:54)
    at scala.tools.nsc.Driver.main(Driver.scala:67)
    at scala.tools.nsc.Main.main(Main.scala)

Exception in thread "main" scala.reflect.internal.Types$TypeError: Int does not take parameters
    at scala.tools.nsc.typechecker.Contexts$Context.issueCommon(Contexts.scala:375)
    at scala.tools.nsc.typechecker.Contexts$Context.issue(Contexts.scala:379)
    at scala.tools.nsc.typechecker.Infer$Inferencer.issue(Infer.scala:281)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$duplErrorTree$1(Typers.scala:2943)
    at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3254)
    at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4461)
    at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4493)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5366)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5443)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:415)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$56.apply(Typers.scala:2864)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$56.apply(Typers.scala:2864)
    at scala.tools.nsc.typechecker.Typers$Typer.withCondConstrTyper(Typers.scala:488)
    at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:2864)
    at scala.tools.nsc.typechecker.Typers$Typer.loop$1(Typers.scala:2891)
    at scala.tools.nsc.typechecker.Typers$Typer.typedArgs(Typers.scala:2897)
    at scala.tools.nsc.typechecker.Typers$Typer.handleMonomorphicCall$1(Typers.scala:3156)
    at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3200)
    at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4461)
    at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4493)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5366)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5443)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:415)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5510)
    at scala.tools.nsc.typechecker.Typers$Typer.typedIf$1(Typers.scala:4169)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5373)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5443)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:415)
    at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2335)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5372)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5372)
    at scala.tools.nsc.typechecker.Typers$Typer.typerWithLocalContext(Typers.scala:497)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5372)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5443)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:273)
    at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:5642)
    at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:2163)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5371)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5443)
    at miniboxing.plugin.Duplicators$BodyDuplicator.typed(Duplicators.scala:285)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5494)
    at miniboxing.plugin.Duplicators$BodyDuplicator.retypedMethodMB(Duplicators.scala:219)
    at miniboxing.plugin.Duplicators.retypedMethod(Duplicators.scala:50)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.addDefDefBody(MiniboxTreeTransformation.scala:300)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.addBody(MiniboxTreeTransformation.scala:264)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:111)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:52)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2819)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2819)
    at scala.collection.immutable.List.loop$1(List.scala:164)
    at scala.collection.immutable.List.mapConserve(List.scala:180)
    at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2819)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$transform$2.apply(MiniboxTreeTransformation.scala:87)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$transform$2.apply(MiniboxTreeTransformation.scala:87)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2855)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:87)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:52)
    at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2823)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1238)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1237)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2855)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1236)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:12)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2816)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:152)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:52)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2846)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2844)
    at scala.collection.immutable.List.loop$1(List.scala:164)
    at scala.collection.immutable.List.mapConserve(List.scala:180)
    at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2844)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$transform$1.apply(MiniboxTreeTransformation.scala:72)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer$$anonfun$transform$1.apply(MiniboxTreeTransformation.scala:66)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2855)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at miniboxing.plugin.MiniboxTreeTransformation$MiniboxTreeTransformer.transform(MiniboxTreeTransformation.scala:66)
    at miniboxing.plugin.Minibox$Component$$anon$1$$anonfun$transform$1.apply(Minibox.scala:41)
    at miniboxing.plugin.Minibox$Component$$anon$1$$anonfun$transform$1.apply(Minibox.scala:41)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:201)
    at scala.reflect.internal.SymbolTable.afterPhase(SymbolTable.scala:210)
    at miniboxing.plugin.MiniboxPhase$class.afterMinibox(Minibox.scala:51)
    at miniboxing.plugin.Minibox$Component$.afterMinibox(Minibox.scala:20)
    at miniboxing.plugin.Minibox$Component$$anon$1.transform(Minibox.scala:41)
    at miniboxing.plugin.Minibox$Component$$anon$1.transform(Minibox.scala:38)
    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:227)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:461)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:428)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:428)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1156)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:428)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1574)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1548)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1544)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1654)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:33)
    at scala.tools.nsc.Main$.doCompile(Main.scala:79)
    at scala.tools.nsc.Driver.process(Driver.scala:54)
    at scala.tools.nsc.Driver.main(Driver.scala:67)
    at scala.tools.nsc.Main.main(Main.scala)
```

**Comment by VladUreche** [comment]
Reduced:

```
package miniboxing.bugs
import miniboxing.plugin.minispec

class BUG7[@minispec T](head: T, tail: BUG7[T]) {
  override def hashCode(): Int = tail.hashCode
}
```
