### ISSUE TITLE
Compiling the project doesn't work on Windows 7

### ISSUE THREAD

**Issue by MelodyLucid** [miniboxing/miniboxing-plugin#77]
Compiling the project with `sbt compile package test` doesn't work on Windows 7.

If I follow the guide [install the project](https://github.com/miniboxing/miniboxing-plugin/wiki/Try-%7C-Local-installation#wiki-installing-sbt) from the wiki on my Windows environment, the command `sbt compile package test` outputs the following

```
[...]

[info] Test run started
[info] Test miniboxing.classloader.test.ClassloaderTest.testTargetDirect started
[error] Test miniboxing.classloader.test.ClassloaderTest.testTargetDirect failed: assertion failed: "print(5, 1) by miniboxing.classloader.test.Target_class_J
" != "print(5, 1) by miniboxing.classloader.test.Target_class_J"

[info] Test miniboxing.classloader.test.ClassloaderTest.testTargetDispatcherDirect started
[error] Test miniboxing.classloader.test.ClassloaderTest.testTargetDispatcherDirect failed: assertion failed: "print(5, IntDispatcher) by miniboxing.classloader.test.TargetDispatcher_class_J
" != "print(5, IntDispatcher) by miniboxing.classloader.test.TargetDispatcher_class_J"

[info] Test miniboxing.classloader.test.ClassloaderTest.testTargetInnerClass started
[error] Test miniboxing.classloader.test.ClassloaderTest.testTargetInnerClass failed: assertion failed: "printInnerClass: miniboxing.classloader.test.Target_class_J$$anon$1
" != "printInnerClass: miniboxing.classloader.test.Target_class_J$$anon$1"

[info] Test miniboxing.classloader.test.ClassloaderTest.testTargetTrait started
[error] Test miniboxing.classloader.test.ClassloaderTest.testTargetTrait failed: assertion failed: "printSuper: miniboxing.classloader.test.TargetSuper_class_J
" != "printSuper: miniboxing.classloader.test.TargetSuper_class_J"

[info] Test miniboxing.classloader.test.ClassloaderTest.testTargetSuper started
[error] Test miniboxing.classloader.test.ClassloaderTest.testTargetSuper failed: assertion failed: "printTrait: miniboxing.classloader.test.TargetTrait_class_J$class
" != "printTrait: miniboxing.classloader.test.TargetTrait_class_J$class"

[info] Test miniboxing.classloader.test.ClassloaderTest.testTargetDispatcherFactoryClassLoaderInt started
[error] Test miniboxing.classloader.test.ClassloaderTest.testTargetDispatcherFactoryClassLoaderInt failed: assertion failed: "print(5, IntDispatcher) by miniboxing.classloader.test.TargetDispatcher_class_0
" != "print(5, IntDispatcher) by miniboxing.classloader.test.TargetDispatcher_class_0"

[info] Test miniboxing.classloader.test.ClassloaderTest.testTargetDispatcherFactoryClassLoaderLong started
[error] Test miniboxing.classloader.test.ClassloaderTest.testTargetDispatcherFactoryClassLoaderLong failed: assertion failed: "print(5, LongDispatcher) by miniboxing.classloader.test.TargetDispatcher_class_1
" != "print(5, LongDispatcher) by miniboxing.classloader.test.TargetDispatcher_class_1"

[info] Test miniboxing.classloader.test.ClassloaderTest.testTargetFactoryClassLoaderInnerClass started
[error] Test miniboxing.classloader.test.ClassloaderTest.testTargetFactoryClassLoaderInnerClass failed: assertion failed: "printInnerClass: miniboxing.classloader.test.Target_class_1$$anon$1
" != "printInnerClass: miniboxing.classloader.test.Target_class_1$$anon$1"

[info] Test miniboxing.classloader.test.ClassloaderTest.testTargetFactoryClassLoaderTrait started
[error] Test miniboxing.classloader.test.ClassloaderTest.testTargetFactoryClassLoaderTrait failed: assertion failed: "printTrait: miniboxing.classloader.test.TargetTrait_class_1$class
" != "printTrait: miniboxing.classloader.test.TargetTrait_class_1$class"

[info] Test miniboxing.classloader.test.ClassloaderTest.testTargetFactoryClassLoaderSuper started
[error] Test miniboxing.classloader.test.ClassloaderTest.testTargetFactoryClassLoaderSuper failed: assertion failed: "printSuper: miniboxing.classloader.test.TargetSuper_class_1
" != "printSuper: miniboxing.classloader.test.TargetSuper_class_1"

[info] Test miniboxing.classloader.test.ClassloaderTest.testTargetFactoryClassLoaderTarget started
[error] Test miniboxing.classloader.test.ClassloaderTest.testTargetFactoryClassLoaderTarget failed: assertion failed: "print(5, 1) by miniboxing.classloader.test.Target_class_1
" != "print(5, 1) by miniboxing.classloader.test.Target_class_1"

[info] Test run finished: 11 failed, 0 ignored, 11 total, 0.138s
[error] Failed: Total 11, Failed 11, Errors 0, Passed 0
[error] Failed tests:
[error]     miniboxing.classloader.test.ClassloaderTest

[info] Test run started
[info] Test miniboxing.infrastructure.TestSuite.testCompileOutput started
[error] Test miniboxing.infrastructure.TestSuite.testCompileOutput failed: object scala.runtime in compiler mirror not found.
[error]     at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
[error]     at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
[error]     at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:48)
[error]     at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
[error]     at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
[error]     at scala.reflect.internal.Mirrors$RootsBase.getPackage(Mirrors.scala:172)
[error]     at scala.reflect.internal.Mirrors$RootsBase.getRequiredPackage(Mirrors.scala:175)
[error]     at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage$lzycompute(Definitions.scala:183)
[error]     at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage(Definitions.scala:183)
[error]     at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackageClass$lzycompute(Definitions.scala:184)
[error]     at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackageClass(Definitions.scala:184)
[error]     at scala.reflect.internal.Definitions$DefinitionsClass.AnnotationDefaultAttr$lzycompute(Definitions.scala:1024)
[error]     at scala.reflect.internal.Definitions$DefinitionsClass.AnnotationDefaultAttr(Definitions.scala:1023)
[error]     at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses$lzycompute(Definitions.scala:1153)
[error]     at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses(Definitions.scala:1152)
[error]     at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1196)
[error]     at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1196)
[error]     at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1261)
[error]     at scala.tools.nsc.Global$Run.<init>(Global.scala:1290)
[error]     at scala.tools.partest.DirectTest.withRun(DirectTest.scala:88)
[error]     at scala.tools.partest.DirectTest.compileString(DirectTest.scala:62)
[error]     at scala.tools.partest.DirectTest.compile(DirectTest.scala:92)
[error]     at miniboxing.infrastructure.CompileTest.compilationOutput(CompileTest.scala:31)
[error]     at miniboxing.infrastructure.TestSuite$$anonfun$testCompileOutput$1.apply(TestSuite.scala:55)
[error]     at miniboxing.infrastructure.TestSuite$$anonfun$testCompileOutput$1.apply(TestSuite.scala:47)
[error]     at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[error]     at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
[error]     at miniboxing.infrastructure.TestSuite.testCompileOutput(TestSuite.scala:47)
[error]     ...

[info] Test run finished: 1 failed, 0 ignored, 1 total, 0.944s
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0

[error] Failed tests:
[error]     miniboxing.infrastructure.TestSuite
[error] (miniboxing-tests/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] (miniboxing-classloader/test:test) sbt.TestsFailedException: Tests unsuccessful
```

I don't know if it works on Windows 8.

**Comment by VladUreche** [comment]
Thanks for the error report @MelodyLucid!

**Comment by VladUreche** [comment]
Unfortunately I've exhausted my time budget on windows. It's broken in so many ways, it shouldn't even be considered by developers.
