### ISSUE TITLE
Constructors crash

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#82]
```
sun@sun-laptop:~/workspace/dev/miniboxing-plugin(wip)$ ./mb-scala
Picked up _JAVA_OPTIONS: -Xms2g -Xmx2g -Xss4m -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=256m -XX:+UseParallelGC -XX:PermSize=256m -XX:+TieredCompilation -XX:+UseNUMA
Welcome to Scala version 2.10.4-20140209-180020-b66a39653b (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_51).
Type in expressions to have them evaluated.
Type :help for more information.

scala>  class C[@miniboxed T](val t1: T, val t2: T) { var s: T = t1; s = t2 }
ReplGlobal.abort: t1_J not in List(value $line3|$read|$iw|$iw|C_J|T_TypeTag, value t1, value t2)
error: t1_J not in List(value $line3|$read|$iw|$iw|C_J|T_TypeTag, value t1, value t2)
unhandled exception while transforming <console>
error: uncaught exception during compilation: scala.reflect.internal.FatalError
scala.reflect.internal.FatalError: 
     while compiling: <console>
        during phase: constructors
     library version: version 2.10.4-20140209-180020-b66a39653b
    compiler version: version 2.10.4-20140209-180020-b66a39653b
  reconstructed args: -bootclasspath /home/sun/workspace/dev/miniboxing-plugin//components/runtime/target/scala-2.10/miniboxing-runtime_2.10-0.2-SNAPSHOT.jar:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.2-SNAPSHOT.jar -Xplugin:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.2-SNAPSHOT.jar

  last tree to typer: term s 
              symbol: variable s in class C_L (flags: <mutable> <triedcooking> private[this])
   symbol definition: private[this] var s: Object
                 tpe: <notype>
       symbol owners: variable s -> class C_L -> object $iw -> object $iw -> object $read -> package $line3
      context owners: class C_J -> object $iw -> object $iw -> object $read -> package $line3

== Enclosing template or block ==

Template( // val <local C_J>: <notype> in class C_J, tree.tpe=C_J
  "java.lang.Object", "$line3.$read.$iw.$iw.C" // parents
  ValDef(
    private
    "_"
    <tpt>
    <empty>
  )
  // 13 statements
  DefDef( // def <init>(val $line3|$read|$iw|$iw|C_J|T_TypeTag: Byte,t1: Long,t2: Long): C_J in class C_J
    <method>
    "<init>"
    []
    // 1 parameter list
    ValDef( // val $line3|$read|$iw|$iw|C_J|T_TypeTag: Byte
      0
      "$line3|$read|$iw|$iw|C_J|T_TypeTag"
      <tpt> // tree.tpe=Byte
      <empty>
    )
    ValDef( // t1: Long
      <param>
      "t1"
      <tpt> // tree.tpe=Long
      <empty>
    )
    ValDef( // t2: Long
      <param>
      "t2"
      <tpt> // tree.tpe=Long
      <empty>
    )
    <tpt> // tree.tpe=C_J
    Block( // tree.tpe=Unit
      // 2 statements
      Apply( // def <init>(): Object in class Object, tree.tpe=Object
        C_J.super."<init>" // def <init>(): Object in class Object, tree.tpe=()Object
        Nil
      )
      Apply( // def $init$(): Unit in class C$class, tree.tpe=Unit
        C_J.this.$asInstanceOf[C$class]()."$init$" // def $init$(): Unit in class C$class, tree.tpe=()Unit
        Nil
      )
      ()
    )
  )
  DefDef( // def s(): Object in class C_J
    <method> <accessor> <triedcooking>
    "s"
    []
    List(Nil)
    <tpt> // tree.tpe=Object
    Apply( // final def minibox2box(l: Long,tag: Byte): Object in object MiniboxConversions, tree.tpe=Object
      MiniboxConversions.this."minibox2box" // final def minibox2box(l: Long,tag: Byte): Object in object MiniboxConversions, tree.tpe=(l: Long, tag: Byte)Object
      // 2 arguments
      Apply( // def s_J(val T_TypeTag: Byte): Long in class C_J, tree.tpe=Long
        C_J.this."s_J" // def s_J(val T_TypeTag: Byte): Long in class C_J, tree.tpe=(val T_TypeTag: Byte)Long
        C_J.this."$line3|$read|$iw|$iw|C_J|T_TypeTag" // private[this] val $line3|$read|$iw|$iw|C_J|T_TypeTag: Byte in class C_J, tree.tpe=Byte
      )
      C_J.this."$line3|$read|$iw|$iw|C_J|T_TypeTag" // private[this] val $line3|$read|$iw|$iw|C_J|T_TypeTag: Byte in class C_J, tree.tpe=Byte
    )
  )
  DefDef( // def s_=(x$1: Object): Unit in class C_J
    <method> <accessor> <triedcooking>
    "s_$eq"
    []
    // 1 parameter list
    ValDef( // x$1: Object
      <param> <synthetic> <triedcooking>
      "x$1"
      <tpt> // tree.tpe=Object
      <empty>
    )
    <tpt> // tree.tpe=Unit
    Apply( // def s_J_=(val T_TypeTag: Byte,x$1: Long): Unit in class C_J, tree.tpe=Unit
      C_J.this."s_J_$eq" // def s_J_=(val T_TypeTag: Byte,x$1: Long): Unit in class C_J, tree.tpe=(val T_TypeTag: Byte, x$1: Long)Unit
      // 2 arguments
      C_J.this."$line3|$read|$iw|$iw|C_J|T_TypeTag" // private[this] val $line3|$read|$iw|$iw|C_J|T_TypeTag: Byte in class C_J, tree.tpe=Byte
      Apply( // final def box2minibox_tt(a: Object,tag: Byte): Long in object MiniboxConversions, tree.tpe=Long
        MiniboxConversions.this."box2minibox_tt" // final def box2minibox_tt(a: Object,tag: Byte): Long in object MiniboxConversions, tree.tpe=(a: Object, tag: Byte)Long
        // 2 arguments
        "x$1" // x$1: Object, tree.tpe=Object
        C_J.this."$line3|$read|$iw|$iw|C_J|T_TypeTag" // private[this] val $line3|$read|$iw|$iw|C_J|T_TypeTag: Byte in class C_J, tree.tpe=Byte
      )
    )
  )
  DefDef( // def s_J(val T_TypeTag: Byte): Long in class C_J
    <method> <accessor> <triedcooking>
    "s_J"
    []
    // 1 parameter list
    ValDef( // val T_TypeTag: Byte
      0
      "T_TypeTag"
      <tpt> // tree.tpe=Byte
      <empty>
    )
    <tpt> // tree.tpe=Long
    C_J.this."s " // private[this] var s: Long in class C_J, tree.tpe=Long
  )
  DefDef( // def s_J_=(val T_TypeTag: Byte,x$1: Long): Unit in class C_J
    <method> <accessor> <triedcooking>
    "s_J_$eq"
    []
    // 1 parameter list
    ValDef( // val T_TypeTag: Byte
      0
      "T_TypeTag"
      <tpt> // tree.tpe=Byte
      <empty>
    )
    ValDef( // x$1: Long
      <param> <synthetic> <triedcooking>
      "x$1"
      <tpt> // tree.tpe=Long
      <empty>
    )
    <tpt> // tree.tpe=Unit
    Assign( // tree.tpe=Unit
      C_J.this."s " // private[this] var s: Long in class C_J, tree.tpe=Long
      "x$1" // x$1: Long, tree.tpe=Long
    )
  )
  ValDef( // private[this] val $line3|$read|$iw|$iw|C_J|T_TypeTag: Byte in class C_J
    private <local> <paramaccessor> <triedcooking>
    "$line3|$read|$iw|$iw|C_J|T_TypeTag"
    <tpt> // tree.tpe=Byte
    <empty>
  )
  ValDef( // private[this] val t1: Long in class C_J
    private <local> <paramaccessor> <triedcooking>
    "t1 "
    <tpt> // tree.tpe=Long
    <empty>
  )
  ValDef( // private[this] val t2: Long in class C_J
    private <local> <paramaccessor> <triedcooking>
    "t2 "
    <tpt> // tree.tpe=Long
    <empty>
  )
  ValDef( // private[this] var s: Long in class C_J
    private <mutable> <local> <triedcooking>
    "s "
    <tpt> // tree.tpe=Long
    Apply( // val t1_J(val T_TypeTag: Byte): Long in class C_J, tree.tpe=Long
      C_J.this."t1_J" // val t1_J(val T_TypeTag: Byte): Long in class C_J, tree.tpe=(val T_TypeTag: Byte)Long
      C_J.this."$line3|$read|$iw|$iw|C_J|T_TypeTag" // private[this] val $line3|$read|$iw|$iw|C_J|T_TypeTag: Byte in class C_J, tree.tpe=Byte
    )
  )
  DefDef( // val t1(): Object in class C_J
    <method> <stable> <accessor> <paramaccessor> <triedcooking>
    "t1"
    []
    List(Nil)
    <tpt> // tree.tpe=Object
    Apply( // final def minibox2box(l: Long,tag: Byte): Object in object MiniboxConversions, tree.tpe=Object
      MiniboxConversions.this."minibox2box" // final def minibox2box(l: Long,tag: Byte): Object in object MiniboxConversions, tree.tpe=(l: Long, tag: Byte)Object
      // 2 arguments
      Apply( // val t1_J(val T_TypeTag: Byte): Long in class C_J, tree.tpe=Long
        C_J.this."t1_J" // val t1_J(val T_TypeTag: Byte): Long in class C_J, tree.tpe=(val T_TypeTag: Byte)Long
        C_J.this."$line3|$read|$iw|$iw|C_J|T_TypeTag" // private[this] val $line3|$read|$iw|$iw|C_J|T_TypeTag: Byte in class C_J, tree.tpe=Byte
      )
      C_J.this."$line3|$read|$iw|$iw|C_J|T_TypeTag" // private[this] val $line3|$read|$iw|$iw|C_J|T_TypeTag: Byte in class C_J, tree.tpe=Byte
    )
  )
  DefDef( // val t1_J(val T_TypeTag: Byte): Long in class C_J
    <method> <stable> <accessor> <paramaccessor> <triedcooking>
    "t1_J"
    []
    // 1 parameter list
    ValDef( // val T_TypeTag: Byte
      0
      "T_TypeTag"
      <tpt> // tree.tpe=Byte
      <empty>
    )
    <tpt> // tree.tpe=Long
    C_J.this."t1 " // private[this] val t1: Long in class C_J, tree.tpe=Long
  )
  DefDef( // val t2(): Object in class C_J
    <method> <stable> <accessor> <paramaccessor> <triedcooking>
    "t2"
    []
    List(Nil)
    <tpt> // tree.tpe=Object
    Apply( // final def minibox2box(l: Long,tag: Byte): Object in object MiniboxConversions, tree.tpe=Object
      MiniboxConversions.this."minibox2box" // final def minibox2box(l: Long,tag: Byte): Object in object MiniboxConversions, tree.tpe=(l: Long, tag: Byte)Object
      // 2 arguments
      Apply( // val t2_J(val T_TypeTag: Byte): Long in class C_J, tree.tpe=Long
        C_J.this."t2_J" // val t2_J(val T_TypeTag: Byte): Long in class C_J, tree.tpe=(val T_TypeTag: Byte)Long
        C_J.this."$line3|$read|$iw|$iw|C_J|T_TypeTag" // private[this] val $line3|$read|$iw|$iw|C_J|T_TypeTag: Byte in class C_J, tree.tpe=Byte
      )
      C_J.this."$line3|$read|$iw|$iw|C_J|T_TypeTag" // private[this] val $line3|$read|$iw|$iw|C_J|T_TypeTag: Byte in class C_J, tree.tpe=Byte
    )
  )
  DefDef( // val t2_J(val T_TypeTag: Byte): Long in class C_J
    <method> <stable> <accessor> <paramaccessor> <triedcooking>
    "t2_J"
    []
    // 1 parameter list
    ValDef( // val T_TypeTag: Byte
      0
      "T_TypeTag"
      <tpt> // tree.tpe=Byte
      <empty>
    )
    <tpt> // tree.tpe=Long
    C_J.this."t2 " // private[this] val t2: Long in class C_J, tree.tpe=Long
  )
)

== Expanded type of tree ==

<notype>

t1_J not in List(value $line3|$read|$iw|$iw|C_J|T_TypeTag, value t1, value t2)
    at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:49)
    at scala.tools.nsc.Global.abort(Global.scala:254)
    at scala.tools.nsc.interpreter.IMain$$anon$1.scala$tools$nsc$interpreter$ReplGlobal$$super$abort(IMain.scala:265)
    at scala.tools.nsc.interpreter.ReplGlobal$class.abort(ReplGlobal.scala:21)
    at scala.tools.nsc.interpreter.IMain$$anon$1.abort(IMain.scala:265)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.scala$tools$nsc$transform$Constructors$ConstructorTransformer$$parameterNamed$1(Constructors.scala:71)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.scala$tools$nsc$transform$Constructors$ConstructorTransformer$$parameter$1(Constructors.scala:63)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anon$1.transform(Constructors.scala:99)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anon$1.transform(Constructors.scala:79)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1219)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anon$1.transform(Constructors.scala:105)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anon$1.transform(Constructors.scala:79)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.scala$tools$nsc$transform$Constructors$ConstructorTransformer$$intoConstructor$1(Constructors.scala:111)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transformClassTemplate$2.apply(Constructors.scala:191)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transformClassTemplate$2.apply(Constructors.scala:170)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transformClassTemplate(Constructors.scala:170)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transform$1.apply(Constructors.scala:575)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transform$1.apply(Constructors.scala:575)
    at scala.reflect.internal.Trees$class.deriveClassDef(Trees.scala:1616)
    at scala.reflect.internal.SymbolTable.deriveClassDef(SymbolTable.scala:13)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:575)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transformClassTemplate$2.apply(Constructors.scala:199)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transformClassTemplate$2.apply(Constructors.scala:170)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transformClassTemplate(Constructors.scala:170)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transform$1.apply(Constructors.scala:575)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transform$1.apply(Constructors.scala:575)
    at scala.reflect.internal.Trees$class.deriveClassDef(Trees.scala:1616)
    at scala.reflect.internal.SymbolTable.deriveClassDef(SymbolTable.scala:13)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:575)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transformClassTemplate$2.apply(Constructors.scala:199)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transformClassTemplate$2.apply(Constructors.scala:170)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transformClassTemplate(Constructors.scala:170)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transform$1.apply(Constructors.scala:575)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transform$1.apply(Constructors.scala:575)
    at scala.reflect.internal.Trees$class.deriveClassDef(Trees.scala:1616)
    at scala.reflect.internal.SymbolTable.deriveClassDef(SymbolTable.scala:13)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:575)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transformClassTemplate$2.apply(Constructors.scala:199)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transformClassTemplate$2.apply(Constructors.scala:170)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transformClassTemplate(Constructors.scala:170)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transform$1.apply(Constructors.scala:575)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer$$anonfun$transform$1.apply(Constructors.scala:575)
    at scala.reflect.internal.Trees$class.deriveClassDef(Trees.scala:1616)
    at scala.reflect.internal.SymbolTable.deriveClassDef(SymbolTable.scala:13)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:575)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:30)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2927)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2925)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2925)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1298)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1298)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1297)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:577)
    at scala.tools.nsc.transform.Constructors$ConstructorTransformer.transform(Constructors.scala:30)
    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:227)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:431)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
    at scala.tools.nsc.interpreter.IMain.compileSourcesKeepingRun(IMain.scala:428)
    at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compileAndSaveRun(IMain.scala:801)
    at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:761)
    at scala.tools.nsc.interpreter.IMain$Request.compile$lzycompute(IMain.scala:936)
    at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:931)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:603)
    at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:568)
    at scala.tools.nsc.interpreter.ILoop.reallyInterpret$1(ILoop.scala:760)
    at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:805)
    at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:717)
    at scala.tools.nsc.interpreter.ILoop.processLine$1(ILoop.scala:581)
    at scala.tools.nsc.interpreter.ILoop.innerLoop$1(ILoop.scala:588)
    at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:591)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:882)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
    at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:837)
    at scala.tools.nsc.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:135)
    at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:837)
    at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:83)
    at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
    at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:105)
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

That entry seems to have slain the compiler.  Shall I replay
your session? I can re-run each line except the last one.
[y/n]
```

**Comment by VladUreche** [comment]
Constructors is so broken :(
