### ISSUE TITLE
Duplicator relies on name resolution => crash

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#84]
Here's a crasher that's most likely related to name resolution in the duplicated code.
Just commenting out `class G` and cleaning up the classpath avoids the problem:

```
sun@sun-laptop:/mnt/data-local/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ cat crasher3.scala 
package miniboxing.tests.compile

class G

class Error[@miniboxed U, G](g: G) {
  def foo[X](x: X) = ???
  def test(u: U) =
    foo(g)
}
sun@sun-laptop:/mnt/data-local/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ ../mb-scalac crasher3.scala 
error: 
     while compiling: crasher3.scala
        during phase: minibox-dupl
     library version: version 2.10.4-20140209-180020-b66a39653b
    compiler version: version 2.10.4-20140209-180020-b66a39653b
  reconstructed args: -bootclasspath /home/sun/workspace/dev/miniboxing-plugin//components/runtime/target/scala-2.10/miniboxing-runtime_2.10-0.2-SNAPSHOT.jar:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.2-SNAPSHOT.jar -Xplugin:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.2-SNAPSHOT.jar

  last tree to typer: term test
              symbol: method test in class Error_J (flags: <method>)
   symbol definition: def test(u: Usp): Nothing
                 tpe: <notype>
       symbol owners: method test -> class Error_J -> package compile
      context owners: method test_J -> class Error_J -> package compile

== Enclosing template or block ==

Apply( // def foo[X](x: X): Nothing in class Error
  TypeApply( // def foo[X](x: X): Nothing in class Error, tree.tpe=(x: G)Nothing
    Error.this."foo" // def foo[X](x: X): Nothing in class Error, tree.tpe=[X](x: X)Nothing
    <tpt> // tree.tpe=G
  )
  Error.this."g" // private[this] val g: G in class Error, tree.tpe=G
)

== Expanded type of tree ==

<notype>

uncaught exception during compilation: scala.reflect.internal.Types$TypeError
error: scala.reflect.internal.Types$TypeError: type mismatch;
 found   : Gsp
 required: G
    at scala.tools.nsc.typechecker.Contexts$Context.issueCommon(Contexts.scala:397)
    at scala.tools.nsc.typechecker.Contexts$Context.issue(Contexts.scala:401)
    at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueTypeError(ContextErrors.scala:103)
    at scala.tools.nsc.typechecker.ContextErrors$ErrorUtils$.issueNormalTypeError(ContextErrors.scala:87)
    at scala.tools.nsc.typechecker.ContextErrors$TyperContextErrors$TyperErrorGen$.AdaptTypeError(ContextErrors.scala:195)
    at scala.tools.nsc.typechecker.Typers$Typer.fallBack$1(Typers.scala:1278)
    at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1283)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5660)
    at miniboxing.plugin.transform.dupl.Duplicators$BodyDuplicator.typed(Duplicators.scala:456)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$62.apply(Typers.scala:3042)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$62.apply(Typers.scala:3042)
    at scala.tools.nsc.typechecker.Typers$Typer.withCondConstrTyper(Typers.scala:498)
    at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:3042)
    at scala.tools.nsc.typechecker.Typers$Typer.loop$1(Typers.scala:3069)
    at scala.tools.nsc.typechecker.Typers$Typer.typedArgs(Typers.scala:3074)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$handleMonomorphicCall$1(Typers.scala:3354)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$doTypedApply$2.apply(Typers.scala:3399)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$doTypedApply$2.apply(Typers.scala:3399)
    at scala.tools.nsc.typechecker.TypeDiagnostics$TyperDiagnostics$checkDead$.updateExpr(TypeDiagnostics.scala:462)
    at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3398)
    at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4627)
    at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4659)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5564)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
    at miniboxing.plugin.transform.dupl.Duplicators$BodyDuplicator.typed(Duplicators.scala:486)
    at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:5845)
    at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:2257)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5569)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
    at miniboxing.plugin.transform.dupl.Duplicators$BodyDuplicator.typed(Duplicators.scala:374)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5704)
    at miniboxing.plugin.transform.dupl.Duplicators.retyped(Duplicators.scala:44)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$54.apply(MiniboxDuplTreeTransformation.scala:719)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$54.apply(MiniboxDuplTreeTransformation.scala:719)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
    at scala.reflect.internal.SymbolTable.beforePhase(SymbolTable.scala:215)
    at miniboxing.plugin.MiniboxDuplComponent$class.beforeMiniboxDupl(Minibox.scala:37)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$.beforeMiniboxDupl(Minibox.scala:159)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.duplicateBody(MiniboxDuplTreeTransformation.scala:719)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.specializeDefDefBody(MiniboxDuplTreeTransformation.scala:690)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:251)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:66)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2900)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$14.apply(MiniboxDuplTreeTransformation.scala:191)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$14.apply(MiniboxDuplTreeTransformation.scala:191)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:191)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:66)
    at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2904)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1280)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1279)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1278)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:475)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:66)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2927)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2925)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2925)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$miniboxTransform$2.apply(MiniboxDuplTreeTransformation.scala:165)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$miniboxTransform$2.apply(MiniboxDuplTreeTransformation.scala:162)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:162)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$$anon$4$$anonfun$1.apply(Minibox.scala:180)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$$anon$4$$anonfun$1.apply(Minibox.scala:180)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
    at scala.reflect.internal.SymbolTable.afterPhase(SymbolTable.scala:216)
    at miniboxing.plugin.MiniboxDuplComponent$class.afterMiniboxDupl(Minibox.scala:36)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$.afterMiniboxDupl(Minibox.scala:159)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$$anon$4.transform(Minibox.scala:180)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$$anon$4.transform(Minibox.scala:177)
    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:227)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:431)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:33)
    at scala.tools.nsc.Main$.doCompile(Main.scala:79)
    at scala.tools.nsc.Driver.process(Driver.scala:54)
    at scala.tools.nsc.Driver.main(Driver.scala:67)
    at scala.tools.nsc.Main.main(Main.scala)
```

Thanks to @HaprianVlad for finding the bug, the hard way :))

**Comment by VladUreche** [comment]
Inherited from specialization => https://issues.scala-lang.org/browse/SI-8473
