### ISSUE TITLE
java.lang.AbstractMethodError in generated class

### ISSUE THREAD

**Issue by non** [miniboxing/miniboxing-plugin#85]
I'm not sure if this is expected to work, but I figured I'd report it.

I was interested in trying out miniboxing with a simplified `Function1` type. Here's the code I wrote:

``` scala
package test

trait F1[@miniboxed A, @miniboxed B] { self =>
  def apply(a: A): B

  def andThen[@miniboxed C](f: F1[B, C]): F1[A, C] =
    new F1[A, C] { def apply(a: A): C = f(self(a)) }

  def compose[@miniboxed Z](f: F1[Z, A]): F1[Z, B] =
    new F1[Z, B] { def apply(z: Z): B = self(f(z)) }
}

object Main {
  def main(args: Array[String]): Unit = {
    val f1 = new F1[Int, Double] { def apply(x: Int): Double = (x + 1).toDouble }
    val f2 = new F1[Double, String] { def apply(n: Double): String = (n / 2).toString }
    val f3: F1[Int, String] = f1 andThen f2
    println(f3(10))
  }
}
```

The exception I get is:

```
java.lang.AbstractMethodError: test.F1_JJ$$anon$3.apply_JL(BJ)Ljava/lang/Object;
        at test.Main$.main(test.scala:18)
        at test.Main.main(test.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
```

Looking in the bytecode, I can see that this method is not defined. I'm compiling with 0.2-SNAPSHOT for the plugin and runtime, using Scala 2.10.2 and -optimize for scalac. If there's other information I can provide or testing I can do please let me know.

**Comment by VladUreche** [comment]
@non, thanks a lot for your bug report! I will have a look tonight.

Also keep in mind this won't be optimized due to #32. I plan to have that bug fixed within the next month.

**Comment by VladUreche** [comment]
Btw, have a look at https://github.com/MelodyLucid/freezing-ironman where we do benchmarks for different miniboxed data structures.

**Comment by non** [comment]
Oooh, I will definitely look at your data structures! No hurry, I just wanted to peek in and see how things were going.

**Comment by VladUreche** [comment]
I've spotted the problem, it's a stupid mistake in the specialization logic:

```
  // specialized class:
  abstract trait F1_JJ[Asp, Bsp] extends F1[Asp,Bsp] {
    def andThen[C](f: miniboxing.tests.compile.bug85.F1[Bsp,C]): miniboxing.tests.compile.bug85.F1[Asp,C] // is a specialized implementation of method andThen
    def andThen_n_J[C](val C_TypeTag: Byte,f: miniboxing.tests.compile.bug85.F1[Bsp,C]): miniboxing.tests.compile.bug85.F1[Asp,C] // is a specialized implementation of method andThen
    def apply(a: Asp): Bsp                                                 // is an interface method
    def apply_JJ(val A_TypeTag: Byte,val B_TypeTag: Byte,a: Asp @storage): Bsp @storage // is an interface method
    def apply_JL(val A_TypeTag: Byte,a: Asp @storage): Bsp                 // is an interface method
    def apply_LJ(val B_TypeTag: Byte,a: Asp): Bsp @storage                 // is an interface method
    def miniboxing|tests|compile|bug85|F1_JJ|A_TypeTag(): Byte             // is a type tag
    def miniboxing|tests|compile|bug85|F1_JJ|B_TypeTag(): Byte             // is a type tag
  }
```

Only the most specific overload should be interface, the rest are redirectors.
