### ISSUE TITLE
Private flag in non-specialized classes => invalid class file

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#86]
```
sun@sun-laptop:/mnt/data-local/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ cat gh-bug-86.scala 
package miniboxing.tests.compile.bug86

class C[@miniboxed T](t: T) {
  private def foo(t: Any): Nothing = ???
  def bar(t: T): T = foo(t)
}

object Test {
  def main(args: Array[String]): Unit = {
    (new C[String]("x")).bar("y")
    (new C[Double](1.0)).bar(2.0)
  }
}
sun@sun-laptop:/mnt/data-local/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ ../mb-scalac gh-bug-86.scala 
sun@sun-laptop:/mnt/data-local/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ ../mb-scala miniboxing.tests.compile.bug86.Test
java.lang.ClassFormatError: Method foo in class miniboxing/tests/compile/bug87/C$class has illegal modifiers: 0x40A
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at miniboxing.tests.compile.bug87.C_L.<init>(gh-bug-86.scala:3)
    at miniboxing.tests.compile.bug87.Test$.main(gh-bug-86.scala:10)
    at miniboxing.tests.compile.bug87.Test.main(gh-bug-86.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:71)
    at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
    at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:139)
    at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:71)
    at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:139)
    at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:28)
    at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
    at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:35)
    at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
    at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:74)
    at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
    at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:105)
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

Removing `private` or making it `protected` will make the example work.

**Comment by VladUreche** [comment]
Same issue for specalized members:

```
package miniboxing.tests.compile.bug86

class C[@miniboxed T](t: T) {
  private def foo(t: T): T = ???
  def bar(t: T): T = foo(t)
}

object Test {
  def main(args: Array[String]): Unit = {
    (new C[Double](1.0)).bar(2.0)
  }
}
```

**Comment by VladUreche** [comment]
Full test:

```
package miniboxing.tests.compile.bug86

class C[@miniboxed T](t: T) {
  private def foo1(t: T): T         = ???
  private def foo2(t: Any): Nothing = ???

  def bar(t: T, first: Boolean): T =
    if (first)
      foo1(t)
    else
      foo2(t)
}

object Test {
  def main(args: Array[String]): Unit = {
    (new C[Double](1.0)).bar(2.0, true)
  }
}
```
