### ISSUE TITLE
Nested class crasher 2

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#88]
```
sun@sun-laptop:/mnt/data-local/Work/Workspace/dev/miniboxing-plugin/sandbox/x(wip)$ cat mb_nested_class_third.scala 
package miniboxing.tests.compile.nested



class CCC[@miniboxed T](val c: T) {
  class DDD[@miniboxed U](val d: U) {
    def foo() = println(c == d)
  }
  def test() = {
    new DDD(c).foo
  }
}
sun@sun-laptop:/mnt/data-local/Work/Workspace/dev/miniboxing-plugin/sandbox/x(wip)$ ../../mb-scalac mb_nested_class_third.scala 

     while compiling: mb_nested_class_third.scala
        during phase: minibox-dupl
     library version: version 2.10.4-20140209-180020-b66a39653b
    compiler version: version 2.10.4-20140209-180020-b66a39653b
  reconstructed args: -bootclasspath /home/sun/workspace/dev/miniboxing-plugin//components/runtime/target/scala-2.10/miniboxing-runtime_2.10-0.2-SNAPSHOT.jar:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.2-SNAPSHOT.jar -Xplugin:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.2-SNAPSHOT.jar

  last tree to typer: Select(This(trait CCC), c_J)
              symbol: value c_J in trait CCC (flags: <method> <deferred> <stable> <accessor> <triedcooking>)
   symbol definition: val c_J(val T_TypeTag: Byte): T @storage
                 tpe: (val T_TypeTag: Byte)T @storage
       symbol owners: value c_J -> trait CCC -> package nested
      context owners: method foo -> class DDD_J -> trait CCC -> package nested

== Enclosing template or block ==

Apply( // val d_J(val U_TypeTag: Byte): Usp @storage in class DDD_J, tree.tpe=Usp @storage
  DDD_J.this."d_J" // val d_J(val U_TypeTag: Byte): Usp @storage in class DDD_J, tree.tpe=(val U_TypeTag: Byte)Usp @storage
  DDD_J.this."miniboxing|tests|compile|nested|CCC|DDD_J|U_TypeTag" // private[this] val miniboxing|tests|compile|nested|CCC|DDD_J|U_TypeTag: Byte in class DDD_J, tree.tpe=Byte
)

== Expanded type of tree ==

MethodType(
  params = List(TermSymbol(val T_TypeTag: Byte))
  resultType = AnnotatedType(
    annotations = List(
      AnnotationInfo(
        atp = TypeRef(
          TypeSymbol(
            class storage extends Annotation with TypeConstraint
          )
        )
      )
    )
    underlying = TypeParamTypeRef(TypeParam(T))
  )
)

unhandled exception while transforming mb_nested_class_third.scala
error: uncaught exception during compilation: java.util.NoSuchElementException
error: java.util.NoSuchElementException: key not found: type T
    at scala.collection.MapLike$class.default(MapLike.scala:228)
    at scala.collection.AbstractMap.default(Map.scala:58)
    at scala.collection.MapLike$class.apply(MapLike.scala:141)
    at scala.collection.AbstractMap.apply(Map.scala:58)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:459)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:319)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:414)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$30.apply(MiniboxDuplTreeTransformation.scala:411)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$30.apply(MiniboxDuplTreeTransformation.scala:411)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:411)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:66)
    at scala.reflect.internal.Trees$$anonfun$itransform$2.apply(Trees.scala:1235)
    at scala.reflect.internal.Trees$$anonfun$itransform$2.apply(Trees.scala:1233)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1232)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:253)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:66)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2900)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$14.apply(MiniboxDuplTreeTransformation.scala:191)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$14.apply(MiniboxDuplTreeTransformation.scala:191)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:191)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:66)
    at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2904)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1280)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1279)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1278)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:475)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:66)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2900)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$14.apply(MiniboxDuplTreeTransformation.scala:191)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$14.apply(MiniboxDuplTreeTransformation.scala:191)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:191)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:66)
    at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2904)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1280)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1279)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1278)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:475)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:66)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2927)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2925)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2925)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$miniboxTransform$2.apply(MiniboxDuplTreeTransformation.scala:165)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$miniboxTransform$2.apply(MiniboxDuplTreeTransformation.scala:162)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:162)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$$anon$4$$anonfun$1.apply(Minibox.scala:180)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$$anon$4$$anonfun$1.apply(Minibox.scala:180)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
    at scala.reflect.internal.SymbolTable.afterPhase(SymbolTable.scala:216)
    at miniboxing.plugin.MiniboxDuplComponent$class.afterMiniboxDupl(Minibox.scala:36)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$.afterMiniboxDupl(Minibox.scala:159)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$$anon$4.transform(Minibox.scala:180)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$$anon$4.transform(Minibox.scala:177)
    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:227)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:431)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:33)
    at scala.tools.nsc.Main$.doCompile(Main.scala:79)
    at scala.tools.nsc.Driver.process(Driver.scala:54)
    at scala.tools.nsc.Driver.main(Driver.scala:67)
    at scala.tools.nsc.Main.main(Main.scala)

Exception in thread "main" java.util.NoSuchElementException: key not found: type T
    at scala.collection.MapLike$class.default(MapLike.scala:228)
    at scala.collection.AbstractMap.default(Map.scala:58)
    at scala.collection.MapLike$class.apply(MapLike.scala:141)
    at scala.collection.AbstractMap.apply(Map.scala:58)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:459)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:319)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:414)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$30.apply(MiniboxDuplTreeTransformation.scala:411)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$30.apply(MiniboxDuplTreeTransformation.scala:411)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:411)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:66)
    at scala.reflect.internal.Trees$$anonfun$itransform$2.apply(Trees.scala:1235)
    at scala.reflect.internal.Trees$$anonfun$itransform$2.apply(Trees.scala:1233)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1232)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:253)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:66)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2900)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$14.apply(MiniboxDuplTreeTransformation.scala:191)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$14.apply(MiniboxDuplTreeTransformation.scala:191)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:191)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:66)
    at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2904)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1280)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1279)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1278)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:475)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:66)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformTrees$1.apply(Trees.scala:2900)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2900)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$14.apply(MiniboxDuplTreeTransformation.scala:191)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$14.apply(MiniboxDuplTreeTransformation.scala:191)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:191)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:66)
    at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2904)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1280)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1279)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1278)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:475)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:66)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2927)
    at scala.reflect.api.Trees$Transformer$$anonfun$transformStats$1.apply(Trees.scala:2925)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2925)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$miniboxTransform$2.apply(MiniboxDuplTreeTransformation.scala:165)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$miniboxTransform$2.apply(MiniboxDuplTreeTransformation.scala:162)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.miniboxTransform(MiniboxDuplTreeTransformation.scala:162)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.transform(MiniboxDuplTreeTransformation.scala:112)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$$anon$4$$anonfun$1.apply(Minibox.scala:180)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$$anon$4$$anonfun$1.apply(Minibox.scala:180)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
    at scala.reflect.internal.SymbolTable.afterPhase(SymbolTable.scala:216)
    at miniboxing.plugin.MiniboxDuplComponent$class.afterMiniboxDupl(Minibox.scala:36)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$.afterMiniboxDupl(Minibox.scala:159)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$$anon$4.transform(Minibox.scala:180)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$$anon$4.transform(Minibox.scala:177)
    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:227)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:431)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:33)
    at scala.tools.nsc.Main$.doCompile(Main.scala:79)
    at scala.tools.nsc.Driver.process(Driver.scala:54)
    at scala.tools.nsc.Driver.main(Driver.scala:67)
    at scala.tools.nsc.Main.main(Main.scala)
```

**Comment by VladUreche** [comment]
Reduced:

```
package miniboxing.tests.compile.bug88

class CCC[@miniboxed T](val c: T) {
  class DDD[@miniboxed U](val d: U) {
    def foo() = println(c == d)
  }
}
```
