### ISSUE TITLE
Collection crasher

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#90]
```
sun@sun-cpu:~/workspace/dev/miniboxing-plugin/sandbox(wip)$ cat gh-bug-XX.scala 
package miniboxing.tests.compile.bugXX

trait Fun0[@miniboxed -T, @miniboxed +R] {
  def apply(r: T): R
}

object Test {
  def main(args: Array[String]): Unit = {
    val fun = 
      new Fun0[Double, Double] {
        def apply(r: Double): Double = {
          println(r.toString)
          r
        }
      }
    run(fun, 3.0)
  }

  def run[@miniboxed T](f: Fun0[T, Any], t: T): Any = {
    f(t)
  }
}
sun@sun-cpu:~/workspace/dev/miniboxing-plugin/sandbox(wip)$ rm -rf miniboxing
sun@sun-cpu:~/workspace/dev/miniboxing-plugin/sandbox(wip)$ ../mb-scalac gh-bug-XX.scala 
sun@sun-cpu:~/workspace/dev/miniboxing-plugin/sandbox(wip)$ ../mb-scala miniboxing.tests.compile.bugXX.Test
java.lang.AbstractMethodError: miniboxing.tests.compile.bugXX.Test$$anon$1.miniboxing|tests|compile|bugXX|Fun0_JJ|R_TypeTag()B
    at miniboxing.tests.compile.bugXX.Fun0_JJ$class.apply_JL(gh-bug-XX.scala)
    at miniboxing.tests.compile.bugXX.Test$$anon$1.apply_JL(gh-bug-XX.scala:10)
    at miniboxing.tests.compile.bugXX.Test$.run_n_J(gh-bug-XX.scala:20)
    at miniboxing.tests.compile.bugXX.Test$.main(gh-bug-XX.scala:16)
    at miniboxing.tests.compile.bugXX.Test.main(gh-bug-XX.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:71)
    at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
    at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:139)
    at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:71)
    at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:139)
    at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:28)
    at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
    at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:35)
    at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
    at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:74)
    at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
    at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:105)
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```

**Comment by VladUreche** [comment]
Root cause = wrong flags:

```
sun@sun-cpu:~/workspace/dev/miniboxing-plugin/sandbox(wip)$ javap -cp miniboxing/tests/compile/bugXX/ 'Test$$anon$1'
Warning: Binary file Test$$anon$1 contains miniboxing.tests.compile.bugXX.Test$$anon$1
Compiled from "gh-bug-XX.scala"
public final class miniboxing.tests.compile.bugXX.Test$$anon$1 implements miniboxing.tests.compile.bugXX.Fun0_JJ<java.lang.Object, java.lang.Object> {
  public java.lang.Object apply_JL(byte, long);
  public long apply_LJ(byte, java.lang.Object);
  public double apply(double);
  public abstract byte miniboxing|tests|compile|bugXX|Fun0_JJ|R_TypeTag();
  public abstract byte miniboxing|tests|compile|bugXX|Fun0_JJ|T_TypeTag();
  public long apply_JJ(byte, byte, long);
  public java.lang.Object apply(java.lang.Object);
  public miniboxing.tests.compile.bugXX.Test$$anon$1();
}
```

Note this:

```
  public abstract byte miniboxing|tests|compile|bugXX|Fun0_JJ|R_TypeTag();
  public abstract byte miniboxing|tests|compile|bugXX|Fun0_JJ|T_TypeTag();
```
