### ISSUE TITLE
Crash in duplicator

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#94]
```
sun@sun-cpu:/mnt/data1/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ cat gh-bug-94.scala 
package miniboxing.tests.compile.bug94

class C[@miniboxed T, @miniboxed U]

class D[@miniboxed S] {
  def bar() = {
    class F[@miniboxed T] {
      class Z extends C[S, T]
      def foo(t: T) = new Z
    }
    ???
  }
}
sun@sun-cpu:/mnt/data1/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ ../mb-scalac gh-bug-94.scala 
Picked up _JAVA_OPTIONS: -Xms2g -Xmx2g -Xss4m -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=256m -XX:PermSize=256m -XX:+TieredCompilation -XX:+UseNUMA
error: no-symbol does not have an owner
unhandled exception while transforming gh-bug-94.scala
error: uncaught exception during compilation: scala.reflect.internal.FatalError
error: scala.reflect.internal.FatalError: 
     while compiling: gh-bug-94.scala
        during phase: minibox-dupl
     library version: version 2.10.5-20140407-165700-ec05aeb3d6
    compiler version: version 2.10.5-20140407-165700-ec05aeb3d6
  reconstructed args: -bootclasspath /home/sun/workspace/dev/miniboxing-plugin//components/runtime/target/scala-2.10/miniboxing-runtime_2.10-0.2-SNAPSHOT.jar:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.2-SNAPSHOT.jar -Xplugin:/home/sun/workspace/dev/miniboxing-plugin//components/plugin/target/scala-2.10/miniboxing-plugin_2.10-0.2-SNAPSHOT.jar

  last tree to typer: term <init>
              symbol: constructor D_J in class D_J (flags: <method>)
   symbol definition: def <init>(val miniboxing|tests|compile|bug94|D_J|S_TypeTag: Byte): miniboxing.tests.compile.bug94.D_J[Ssp]
                 tpe: <notype>
       symbol owners: constructor D_J -> class D_J -> package bug94
      context owners: value t -> method foo -> class F -> method bar -> class D_J -> package bug94

== Enclosing template or block ==

DefDef( // def foo(t: T): F.this.<none> in class F
  <method>
  "foo"
  []
  // 1 parameter list
  ValDef( // t: T
    <param>
    "t"
    <tpt> // tree.tpe=T
    <empty>
  )
  <tpt> // tree.tpe=F.this.<none>
  Apply( // def <init>(): F.this.Z in class Z, tree.tpe=F.this.Z
    new F.this.Z."<init>" // def <init>(): F.this.Z in class Z, tree.tpe=()F.this.Z
    Nil
  )
)

== Expanded type of tree ==

<notype>

no-symbol does not have an owner
    at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:49)
    at scala.tools.nsc.Global.abort(Global.scala:254)
    at scala.reflect.internal.Symbols$NoSymbol.owner(Symbols.scala:3257)
    at scala.tools.nsc.typechecker.Typers$Typer$checkNoEscaping$.checkNoEscape$1(Typers.scala:429)
    at scala.tools.nsc.typechecker.Typers$Typer$checkNoEscaping$.apply(Typers.scala:445)
    at scala.tools.nsc.typechecker.Typers$Typer$checkNoEscaping$.check(Typers.scala:402)
    at scala.tools.nsc.typechecker.Typers$Typer$checkNoEscaping$.privates(Typers.scala:385)
    at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:2240)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5569)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
    at miniboxing.plugin.transform.dupl.Duplicators$BodyDuplicator.typed(Duplicators.scala:391)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2928)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3032)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3032)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3032)
    at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1919)
    at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1759)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5583)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
    at miniboxing.plugin.transform.dupl.Duplicators$BodyDuplicator.typed(Duplicators.scala:383)
    at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2928)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3032)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3032)
    at scala.collection.immutable.List.loop$1(List.scala:170)
    at scala.collection.immutable.List.mapConserve(List.scala:186)
    at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3032)
    at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2432)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5570)
    at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$typed1$1.apply(Typers.scala:5570)
    at scala.tools.nsc.typechecker.Typers$Typer.typerWithLocalContext(Typers.scala:507)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5570)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
    at miniboxing.plugin.transform.dupl.Duplicators$BodyDuplicator.typed(Duplicators.scala:376)
    at scala.tools.nsc.typechecker.Typers$Typer.transformedOrTyped(Typers.scala:5845)
    at scala.tools.nsc.typechecker.Typers$Typer.typedDefDef(Typers.scala:2257)
    at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5569)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
    at miniboxing.plugin.transform.dupl.Duplicators$BodyDuplicator.typed(Duplicators.scala:391)
    at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5704)
    at miniboxing.plugin.transform.dupl.Duplicators.retyped(Duplicators.scala:46)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$71$$anonfun$apply$18.apply(MiniboxDuplTreeTransformation.scala:678)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$71$$anonfun$apply$18.apply(MiniboxDuplTreeTransformation.scala:678)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
    at scala.reflect.internal.SymbolTable.beforePhase(SymbolTable.scala:215)
    at miniboxing.plugin.MiniboxDuplComponent$class.beforeMiniboxDupl(Minibox.scala:39)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$.beforeMiniboxDupl(Minibox.scala:161)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$71.apply(MiniboxDuplTreeTransformation.scala:678)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$71.apply(MiniboxDuplTreeTransformation.scala:678)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$class.reportError(MiniboxDuplTreeTransformation.scala:40)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$.reportError(Minibox.scala:161)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.duplicateBody(MiniboxDuplTreeTransformation.scala:686)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.addDefDefBody(MiniboxDuplTreeTransformation.scala:743)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.rewrite(MiniboxDuplTreeTransformation.scala:230)
    at miniboxing.plugin.transform.dupl.TreeRewriters$TreeRewriter$$anonfun$transformStats$1.apply(TreeRewriter.scala:32)
    at miniboxing.plugin.transform.dupl.TreeRewriters$TreeRewriter$$anonfun$transformStats$1.apply(TreeRewriter.scala:30)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
    at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
    at miniboxing.plugin.transform.dupl.TreeRewriters$TreeRewriter.transformStats(TreeRewriter.scala:30)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$16.apply(MiniboxDuplTreeTransformation.scala:176)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$16.apply(MiniboxDuplTreeTransformation.scala:176)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.rewrite(MiniboxDuplTreeTransformation.scala:176)
    at miniboxing.plugin.transform.dupl.TreeRewriters$TreeRewriter.transform(TreeRewriter.scala:22)
    at miniboxing.plugin.transform.dupl.TreeRewriters$TreeRewriter.transform(TreeRewriter.scala:13)
    at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2904)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1280)
    at scala.reflect.internal.Trees$$anonfun$itransform$4.apply(Trees.scala:1279)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1278)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:48)
    at miniboxing.plugin.transform.dupl.TreeRewriters$TreeRewriter.transform(TreeRewriter.scala:23)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$11.apply(MiniboxDuplTreeTransformation.scala:136)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer$$anonfun$11.apply(MiniboxDuplTreeTransformation.scala:132)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at miniboxing.plugin.transform.dupl.MiniboxDuplTreeTransformation$MiniboxTreeTransformer.rewrite(MiniboxDuplTreeTransformation.scala:132)
    at miniboxing.plugin.transform.dupl.TreeRewriters$TreeRewriter$$anonfun$transformStats$1.apply(TreeRewriter.scala:32)
    at miniboxing.plugin.transform.dupl.TreeRewriters$TreeRewriter$$anonfun$transformStats$1.apply(TreeRewriter.scala:30)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:251)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:251)
    at scala.collection.AbstractTraversable.flatMap(Traversable.scala:105)
    at miniboxing.plugin.transform.dupl.TreeRewriters$TreeRewriter.transformStats(TreeRewriter.scala:30)
    at miniboxing.plugin.transform.dupl.TreeRewriters$TreeRewriter.transformStats(TreeRewriter.scala:13)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1298)
    at scala.reflect.internal.Trees$$anonfun$itransform$7.apply(Trees.scala:1298)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:19)
    at scala.reflect.internal.Trees$class.itransform(Trees.scala:1297)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:13)
    at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2897)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.scala$tools$nsc$transform$TypingTransformers$TypingTransformer$$super$transform(TypingTransformers.scala:44)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$2.apply(TypingTransformers.scala:46)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer$$anonfun$transform$2.apply(TypingTransformers.scala:46)
    at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2936)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:34)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.atOwner(TypingTransformers.scala:28)
    at scala.tools.nsc.transform.TypingTransformers$TypingTransformer.transform(TypingTransformers.scala:46)
    at miniboxing.plugin.transform.dupl.TreeRewriters$TreeRewriter.transform(TreeRewriter.scala:23)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$$anon$4$$anonfun$1.apply(Minibox.scala:182)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$$anon$4$$anonfun$1.apply(Minibox.scala:182)
    at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
    at scala.reflect.internal.SymbolTable.afterPhase(SymbolTable.scala:216)
    at miniboxing.plugin.MiniboxDuplComponent$class.afterMiniboxDupl(Minibox.scala:38)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$.afterMiniboxDupl(Minibox.scala:161)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$$anon$4.transform(Minibox.scala:182)
    at miniboxing.plugin.Minibox$MiniboxDuplPhase$$anon$4.transform(Minibox.scala:179)
    at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:227)
    at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:30)
    at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:431)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:431)
    at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1583)
    at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1557)
    at scala.tools.nsc.Global$Run.compileSources(Global.scala:1553)
    at scala.tools.nsc.Global$Run.compile(Global.scala:1662)
    at scala.tools.nsc.Driver.doCompile(Driver.scala:33)
    at scala.tools.nsc.Main$.doCompile(Main.scala:79)
    at scala.tools.nsc.Driver.process(Driver.scala:54)
    at scala.tools.nsc.Driver.main(Driver.scala:67)
    at scala.tools.nsc.Main.main(Main.scala)

```

**Comment by VladUreche** [comment]
If you replace

```
def foo(t: T) = new Z
```

by

```
def foo(t: T): Any = new Z
```

It compiles successfully. :|
