### ISSUE TITLE
Incorrect override generated since it's not taking outside specialzation into account

### ISSUE THREAD

**Issue by VladUreche** [miniboxing/miniboxing-plugin#98]
```
sun@sun-cpu:/mnt/data1/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ cat gh-bug-97.scala 
package miniboxing.tests.compile.collctions2

trait Iterator[@miniboxed +T] {
  def next(): T
}

abstract class List[@miniboxed +T] {
  def iterator: Iterator[T] = new Iterator[T] {
    def next(): T = ???
  }
}
sun@sun-cpu:/mnt/data1/Work/Workspace/dev/miniboxing-plugin/sandbox(wip)$ ../mb-scalac gh-bug-97.scala -Xprint:minibox-spec
Picked up _JAVA_OPTIONS: -Xms2g -Xmx2g -Xss4m -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=256m -XX:PermSize=256m -XX:+TieredCompilation -XX:+UseNUMA
[[syntax trees at end of              minibox-spec]] // gh-bug-97.scala
package miniboxing.tests.compile.collctions2 {
  abstract trait Iterator[@miniboxed T >: Nothing <: Any] extends Object {
    def next(): T;
    def next_J(T_TypeTag: Byte): Long
  };
  abstract trait Iterator_J[Tsp >: Nothing <: Any] extends Object with miniboxing.tests.compile.collctions2.Iterator[Tsp] {
    def miniboxing|tests|compile|collctions2|Iterator_J|T_TypeTag(): Byte;
    def next(): Tsp = MiniboxConversions.this.minibox2box[Tsp](Iterator_J.this.next_J(Iterator_J.this.miniboxing|tests|compile|collctions2|Iterator_J|T_TypeTag()), Iterator_J.this.miniboxing|tests|compile|collctions2|Iterator_J|T_TypeTag());
    def next_J(T_TypeTag: Byte): Long
  };
  abstract trait Iterator_L[Tsp >: Nothing <: Any] extends Object with miniboxing.tests.compile.collctions2.Iterator[Tsp] {
    def next(): Tsp;
    def next_J(T_TypeTag: Byte): Long = MiniboxConversions.this.box2minibox_tt[Tsp](Iterator_L.this.next(), T_TypeTag)
  };
  abstract trait List[@miniboxed T >: Nothing <: Any] extends Object {
    def iterator(): miniboxing.tests.compile.collctions2.Iterator[T]
  };
  abstract class List_J[Tsp >: Nothing <: Any] extends Object with miniboxing.tests.compile.collctions2.List[Tsp] {
    def <init>(miniboxing|tests|compile|collctions2|List_J|T_TypeTag: Byte): miniboxing.tests.compile.collctions2.List_J[Tsp] = {
      List_J.super.<init>();
      ()
    };
    def iterator(): miniboxing.tests.compile.collctions2.Iterator[Tsp] = {
      final class $anon extends Object with miniboxing.tests.compile.collctions2.Iterator_J[Tsp] {
        def <init>(): anonymous class $anon = {
          $anon.super.<init>();
          ()
        };
        def next(): Tsp = scala.this.Predef.???();
        def miniboxing|tests|compile|collctions2|Iterator_J|T_TypeTag(): Byte = List_J.this.miniboxing|tests|compile|collctions2|List_J|T_TypeTag
      };
      new anonymous class $anon()
    };
    <paramaccessor> private[this] val miniboxing|tests|compile|collctions2|List_J|T_TypeTag: Byte = _
  };
  abstract class List_L[Tsp >: Nothing <: Any] extends Object with miniboxing.tests.compile.collctions2.List[Tsp] {
    def <init>(): miniboxing.tests.compile.collctions2.List_L[Tsp] = {
      List_L.super.<init>();
      ()
    };
    def iterator(): miniboxing.tests.compile.collctions2.Iterator[Tsp] = {
      final class $anon extends Object with miniboxing.tests.compile.collctions2.Iterator_L[Tsp] {
        def <init>(): anonymous class $anon = {
          $anon.super.<init>();
          ()
        };
        def next(): Tsp = scala.this.Predef.???()
      };
      new anonymous class $anon()
    }
  }
}
```

**Comment by VladUreche** [comment]
The exact part is:

```
      final class $anon extends Object with miniboxing.tests.compile.collctions2.Iterator_J[Tsp] {
        def <init>(): anonymous class $anon = {
          $anon.super.<init>();
          ()
        };
        def next(): Tsp = scala.this.Predef.???();
        def miniboxing|tests|compile|collctions2|Iterator_J|T_TypeTag(): Byte = List_J.this.miniboxing|tests|compile|collctions2|List_J|T_TypeTag
      };
```

It should move the code from `next` to `next_J` and make `next` a redirect.

**Comment by VladUreche** [comment]
When I try to execute the program:

```
$ cat gh-bug-97.scala 
package miniboxing.tests.compile.bug97

trait Iterator[@miniboxed +T] {
  def next(): T
}

class List[@miniboxed +T](val t: T) {
  def iterator: Iterator[T] = new Iterator[T] {
    def next(): T = t
  }
}

object Test {
  def main(args: Array[String]): Unit = {
    println((new List(3)).iterator.next())
  }
}
$ ../mb-scalac gh-bug-97.scala && ../mb-scala miniboxing.tests.compile.bug97.Test
java.lang.AbstractMethodError: miniboxing.tests.compile.bug97.List_J$$anon$1.next_J(B)J
    at miniboxing.tests.compile.bug97.Test$.main(gh-bug-97.scala:15)
    at miniboxing.tests.compile.bug97.Test.main(gh-bug-97.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at scala.tools.nsc.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:71)
    at scala.tools.nsc.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
    at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:139)
    at scala.tools.nsc.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:71)
    at scala.tools.nsc.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:139)
    at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:28)
    at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
    at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:35)
    at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
    at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:74)
    at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:96)
    at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:105)
    at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```
